import jsPDF from "jspdf";

interface Bulleted {
  bullets: string[];
}
export interface ResumeOutput {
  header: { name: string; email?: string; phone?: string; city?: string; linkedin?: string; website?: string };
  summary: string;
  education: Array<{
    school: string; location?: string; graduationDate?: string; gpa?: string;
    curriculum?: string; classRank?: string; relevantCourses?: string;
  }>;
  experience?: Array<{ role: string; organization: string; location?: string; startDate?: string; endDate?: string } & Bulleted>;
  activities?: Array<{ role: string; organization: string; startDate?: string; endDate?: string } & Bulleted>;
  projects?: Array<{ name: string; tech?: string; link?: string } & Bulleted>;
  research?: Array<{ title: string; advisor?: string; organization?: string; startDate?: string; endDate?: string } & Bulleted>;
  honors?: Array<{ title: string; level?: string; year?: string; description?: string }>;
  certifications?: Array<{ name: string; issuer?: string; year?: string }>;
  coursework?: string[];
  skills?: { technical?: string[]; languages?: string[]; interests?: string[] };
}

/**
 * Classic ATS-friendly one-page resume. Times-style serif, single column, tight spacing.
 */
export function exportResumePDF(r: ResumeOutput) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth(); // 612
  const pageH = doc.internal.pageSize.getHeight(); // 792
  const margin = 48;
  const maxW = pageW - margin * 2;
  let y = margin;

  // Brand color (Pathforge accent blue): #2563EB
  const BRAND_R = 37, BRAND_G = 99, BRAND_B = 235;

  const drawWatermarks = (pageNum: number, pageCount: number) => {
    // Top watermark
    doc.setFont("times", "italic");
    doc.setFontSize(8);
    doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
    doc.text("Generated by Pathforge", pageW - margin, 24, { align: "right" });
    // Footer watermark + page number
    doc.setFont("times", "italic");
    doc.setFontSize(8);
    doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
    const footerY = pageH - 24;
    doc.text("Generated by Pathforge — pathforge.co.in", margin, footerY);
    if (pageCount > 1) {
      doc.setTextColor(140, 140, 140);
      doc.text(`Page ${pageNum} of ${pageCount}`, pageW - margin, footerY, { align: "right" });
    }
    // restore default text color for body
    doc.setTextColor(20, 20, 20);
  };

  // Reserve top space for the header watermark on every page
  const TOP_RESERVED = 36;
  y = TOP_RESERVED;

  const ensure = (need: number) => {
    if (y + need > pageH - margin - 16 /* footer reserve */) {
      doc.addPage();
      y = TOP_RESERVED;
    }
  };

  const setFont = (style: "normal" | "bold" | "italic", size: number) => {
    doc.setFont("times", style);
    doc.setFontSize(size);
    doc.setTextColor(20, 20, 20);
  };

  const writeWrapped = (text: string, size = 10.5, style: "normal" | "italic" = "normal", indent = 0) => {
    setFont(style, size);
    const lines = doc.splitTextToSize(text || "", maxW - indent);
    for (const line of lines) {
      ensure(size + 2);
      doc.text(line, margin + indent, y);
      y += size + 2;
    }
  };

  const sectionRule = (title: string) => {
    ensure(26);
    y += 4;
    setFont("bold", 11);
    doc.setTextColor(0, 0, 0);
    doc.text(title.toUpperCase(), margin, y);
    y += 4;
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.6);
    doc.line(margin, y, pageW - margin, y);
    y += 8;
  };

  const itemHeader = (left: string, right?: string) => {
    ensure(16);
    setFont("bold", 11);
    doc.text(left, margin, y);
    if (right) {
      setFont("italic", 10);
      const w = doc.getTextWidth(right);
      doc.text(right, pageW - margin - w, y);
    }
    y += 13;
  };

  const subLine = (text: string) => {
    if (!text) return;
    setFont("italic", 10);
    ensure(12);
    doc.text(text, margin, y);
    y += 12;
  };

  const bullet = (text: string) => {
    if (!text) return;
    setFont("normal", 10.5);
    const lines = doc.splitTextToSize(text, maxW - 14);
    ensure(lines.length * 12);
    doc.text("•", margin + 2, y);
    lines.forEach((ln: string, i: number) => {
      doc.text(ln, margin + 14, y);
      if (i < lines.length - 1) y += 12;
    });
    y += 12;
  };

  // ── HEADER ──────────────────────────────────────────────
  setFont("bold", 20);
  const name = r.header.name || "Student Name";
  const nameW = doc.getTextWidth(name);
  doc.text(name, (pageW - nameW) / 2, y + 4);
  y += 22;

  const contactBits = [
    r.header.city,
    r.header.phone,
    r.header.email,
    r.header.linkedin,
    r.header.website,
  ].filter(Boolean) as string[];
  if (contactBits.length) {
    setFont("normal", 10);
    const contactStr = contactBits.join("  •  ");
    const w = doc.getTextWidth(contactStr);
    if (w <= maxW) {
      doc.text(contactStr, (pageW - w) / 2, y);
      y += 12;
    } else {
      const half = Math.ceil(contactBits.length / 2);
      const a = contactBits.slice(0, half).join("  •  ");
      const b = contactBits.slice(half).join("  •  ");
      const aw = doc.getTextWidth(a); doc.text(a, (pageW - aw) / 2, y); y += 12;
      const bw = doc.getTextWidth(b); doc.text(b, (pageW - bw) / 2, y); y += 12;
    }
  }
  y += 4;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  // ── SUMMARY ─────────────────────────────────────────────
  if (r.summary && r.summary.trim()) {
    writeWrapped(r.summary.trim(), 10.5, "italic");
    y += 2;
  }

  // ── EDUCATION ───────────────────────────────────────────
  if (r.education?.length) {
    sectionRule("Education");
    r.education.forEach((e) => {
      itemHeader(e.school || "—", e.location || "");
      const sub = [e.curriculum, e.graduationDate ? `Grad: ${e.graduationDate}` : "", e.gpa ? `GPA: ${e.gpa}` : "", e.classRank ? `Rank: ${e.classRank}` : ""].filter(Boolean).join("  •  ");
      if (sub) subLine(sub);
      if (e.relevantCourses) writeWrapped(`Relevant coursework: ${e.relevantCourses}`, 10);
      y += 2;
    });
  }

  // ── EXPERIENCE ──────────────────────────────────────────
  if (r.experience?.length) {
    sectionRule("Experience");
    r.experience.forEach((x) => {
      const dates = `${x.startDate || ""}${x.endDate ? ` – ${x.endDate}` : x.startDate ? " – Present" : ""}`;
      itemHeader(`${x.role} — ${x.organization}`, dates);
      if (x.location) subLine(x.location);
      x.bullets?.forEach(bullet);
      y += 2;
    });
  }

  // ── ACTIVITIES ──────────────────────────────────────────
  if (r.activities?.length) {
    sectionRule("Activities & Leadership");
    r.activities.forEach((a) => {
      const dates = `${a.startDate || ""}${a.endDate ? ` – ${a.endDate}` : a.startDate ? " – Present" : ""}`;
      itemHeader(`${a.role} — ${a.organization}`, dates);
      a.bullets?.forEach(bullet);
      y += 2;
    });
  }

  // ── PROJECTS ────────────────────────────────────────────
  if (r.projects?.length) {
    sectionRule("Projects");
    r.projects.forEach((p) => {
      itemHeader(p.name, p.link || "");
      if (p.tech) subLine(p.tech);
      p.bullets?.forEach(bullet);
      y += 2;
    });
  }

  // ── RESEARCH ────────────────────────────────────────────
  if (r.research?.length) {
    sectionRule("Research & Publications");
    r.research.forEach((rs) => {
      const dates = `${rs.startDate || ""}${rs.endDate ? ` – ${rs.endDate}` : ""}`;
      itemHeader(rs.title, dates);
      const sub = [rs.advisor ? `Advisor: ${rs.advisor}` : "", rs.organization || ""].filter(Boolean).join("  •  ");
      if (sub) subLine(sub);
      rs.bullets?.forEach(bullet);
      y += 2;
    });
  }

  // ── HONORS ──────────────────────────────────────────────
  if (r.honors?.length) {
    sectionRule("Honors & Awards");
    r.honors.forEach((h) => {
      const right = [h.level, h.year].filter(Boolean).join(" • ");
      itemHeader(h.title, right);
      if (h.description) writeWrapped(h.description, 10);
      y += 2;
    });
  }

  // ── CERTIFICATIONS ──────────────────────────────────────
  if (r.certifications?.length) {
    sectionRule("Certifications");
    r.certifications.forEach((c) => {
      const right = [c.issuer, c.year].filter(Boolean).join(" • ");
      itemHeader(c.name, right);
    });
  }

  // ── COURSEWORK ──────────────────────────────────────────
  if (r.coursework?.length) {
    sectionRule("Relevant Coursework");
    writeWrapped(r.coursework.join(" • "), 10.5);
  }

  // ── SKILLS ──────────────────────────────────────────────
  const s = r.skills;
  const hasSkills = s && (s.technical?.length || s.languages?.length || s.interests?.length);
  if (hasSkills) {
    sectionRule("Skills & Interests");
    if (s?.technical?.length) {
      setFont("bold", 10.5);
      ensure(14);
      doc.text("Technical:", margin, y);
      setFont("normal", 10.5);
      const text = s.technical.join(", ");
      const lines = doc.splitTextToSize(text, maxW - 60);
      lines.forEach((ln: string, i: number) => {
        doc.text(ln, margin + 60, y);
        if (i < lines.length - 1) y += 12;
      });
      y += 14;
    }
    if (s?.languages?.length) {
      setFont("bold", 10.5);
      ensure(14);
      doc.text("Languages:", margin, y);
      setFont("normal", 10.5);
      doc.text(s.languages.join(", "), margin + 60, y);
      y += 14;
    }
    if (s?.interests?.length) {
      setFont("bold", 10.5);
      ensure(14);
      doc.text("Interests:", margin, y);
      setFont("normal", 10.5);
      doc.text(s.interests.join(", "), margin + 60, y);
      y += 14;
    }
  }

  // Apply watermarks to every page now that pagination is finalized
  // jsPDF API: getNumberOfPages / setPage
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    drawWatermarks(p, pageCount);
  }

  doc.save(`${(r.header.name || "resume").replace(/\s+/g, "_")}_resume.pdf`);
}
