// Global high schools database with searchable autocomplete
// This is a comprehensive list of notable high schools worldwide

export interface School {
  name: string;
  city: string;
  country: string;
  type?: string;
}

// Notable high schools from around the world
const baseSchools: School[] = [
  // United States - Top Public Schools
  { name: "Thomas Jefferson High School for Science and Technology", city: "Alexandria, VA", country: "United States" },
  { name: "Stuyvesant High School", city: "New York, NY", country: "United States" },
  { name: "Bronx High School of Science", city: "New York, NY", country: "United States" },
  { name: "Illinois Mathematics and Science Academy", city: "Aurora, IL", country: "United States" },
  { name: "Whitney M. Young Magnet High School", city: "Chicago, IL", country: "United States" },
  { name: "BASIS Scottsdale", city: "Scottsdale, AZ", country: "United States" },
  { name: "Academic Magnet High School", city: "North Charleston, SC", country: "United States" },
  { name: "School for Advanced Studies", city: "Miami, FL", country: "United States" },
  { name: "Gwinnett School of Mathematics, Science, and Technology", city: "Lawrenceville, GA", country: "United States" },
  { name: "High Technology High School", city: "Lincroft, NJ", country: "United States" },
  { name: "Bergen County Academies", city: "Hackensack, NJ", country: "United States" },
  { name: "North Carolina School of Science and Mathematics", city: "Durham, NC", country: "United States" },
  { name: "Payton College Preparatory High School", city: "Chicago, IL", country: "United States" },
  { name: "Pine View School", city: "Osprey, FL", country: "United States" },
  { name: "Lowell High School", city: "San Francisco, CA", country: "United States" },
  { name: "Mission San Jose High School", city: "Fremont, CA", country: "United States" },
  { name: "Monta Vista High School", city: "Cupertino, CA", country: "United States" },
  { name: "Gunn High School", city: "Palo Alto, CA", country: "United States" },
  { name: "Palo Alto High School", city: "Palo Alto, CA", country: "United States" },
  { name: "Lynbrook High School", city: "San Jose, CA", country: "United States" },
  { name: "Westlake High School", city: "Austin, TX", country: "United States" },
  { name: "Plano West Senior High School", city: "Plano, TX", country: "United States" },
  { name: "Montgomery Blair High School", city: "Silver Spring, MD", country: "United States" },
  { name: "Arcadia High School", city: "Arcadia, CA", country: "United States" },
  { name: "Troy High School", city: "Fullerton, CA", country: "United States" },
  
  // United States - Top Private Schools
  { name: "Phillips Academy Andover", city: "Andover, MA", country: "United States" },
  { name: "Phillips Exeter Academy", city: "Exeter, NH", country: "United States" },
  { name: "Choate Rosemary Hall", city: "Wallingford, CT", country: "United States" },
  { name: "The Lawrenceville School", city: "Lawrenceville, NJ", country: "United States" },
  { name: "St. Paul's School", city: "Concord, NH", country: "United States" },
  { name: "Deerfield Academy", city: "Deerfield, MA", country: "United States" },
  { name: "Milton Academy", city: "Milton, MA", country: "United States" },
  { name: "Hotchkiss School", city: "Lakeville, CT", country: "United States" },
  { name: "Groton School", city: "Groton, MA", country: "United States" },
  { name: "Middlesex School", city: "Concord, MA", country: "United States" },
  { name: "Trinity School", city: "New York, NY", country: "United States" },
  { name: "Horace Mann School", city: "New York, NY", country: "United States" },
  { name: "Dalton School", city: "New York, NY", country: "United States" },
  { name: "Collegiate School", city: "New York, NY", country: "United States" },
  { name: "Brearley School", city: "New York, NY", country: "United States" },
  { name: "Harvard-Westlake School", city: "Los Angeles, CA", country: "United States" },
  { name: "The College Preparatory School", city: "Oakland, CA", country: "United States" },
  { name: "Lakeside School", city: "Seattle, WA", country: "United States" },
  { name: "The Harker School", city: "San Jose, CA", country: "United States" },
  { name: "Sidwell Friends School", city: "Washington, DC", country: "United States" },
  
  // United Kingdom
  { name: "Eton College", city: "Windsor", country: "United Kingdom" },
  { name: "Westminster School", city: "London", country: "United Kingdom" },
  { name: "St Paul's School", city: "London", country: "United Kingdom" },
  { name: "Winchester College", city: "Winchester", country: "United Kingdom" },
  { name: "Harrow School", city: "London", country: "United Kingdom" },
  { name: "Rugby School", city: "Rugby", country: "United Kingdom" },
  { name: "Charterhouse", city: "Godalming", country: "United Kingdom" },
  { name: "Dulwich College", city: "London", country: "United Kingdom" },
  { name: "Merchant Taylors' School", city: "Northwood", country: "United Kingdom" },
  { name: "North London Collegiate School", city: "London", country: "United Kingdom" },
  { name: "Brighton College", city: "Brighton", country: "United Kingdom" },
  { name: "Manchester Grammar School", city: "Manchester", country: "United Kingdom" },
  { name: "King's College School", city: "London", country: "United Kingdom" },
  { name: "Sevenoaks School", city: "Sevenoaks", country: "United Kingdom" },
  { name: "Tonbridge School", city: "Tonbridge", country: "United Kingdom" },
  
  // India - Comprehensive list (CBSE / ICSE / IB / IGCSE / State / International)
  // Delhi NCR
  { name: "Delhi Public School, R.K. Puram", city: "New Delhi", country: "India" },
  { name: "Delhi Public School, Vasant Kunj", city: "New Delhi", country: "India" },
  { name: "Delhi Public School, Mathura Road", city: "New Delhi", country: "India" },
  { name: "Delhi Public School, Dwarka", city: "New Delhi", country: "India" },
  { name: "Delhi Public School, Rohini", city: "New Delhi", country: "India" },
  { name: "Delhi Public School, Noida", city: "Noida", country: "India" },
  { name: "Delhi Public School, Gurgaon (Sushant Lok)", city: "Gurgaon", country: "India" },
  { name: "Delhi Public School, Ghaziabad", city: "Ghaziabad", country: "India" },
  { name: "Delhi Public School, Faridabad", city: "Faridabad", country: "India" },
  { name: "Modern School, Barakhamba Road", city: "New Delhi", country: "India" },
  { name: "Modern School, Vasant Vihar", city: "New Delhi", country: "India" },
  { name: "Sanskriti School", city: "New Delhi", country: "India" },
  { name: "Springdales School, Pusa Road", city: "New Delhi", country: "India" },
  { name: "Springdales School, Dhaula Kuan", city: "New Delhi", country: "India" },
  { name: "The Shri Ram School, Aravali", city: "Gurgaon", country: "India" },
  { name: "The Shri Ram School, Moulsari", city: "Gurgaon", country: "India" },
  { name: "Vasant Valley School", city: "New Delhi", country: "India" },
  { name: "Mother's International School", city: "New Delhi", country: "India" },
  { name: "Bluebells School International", city: "New Delhi", country: "India" },
  { name: "British School, New Delhi", city: "New Delhi", country: "India" },
  { name: "American Embassy School", city: "New Delhi", country: "India" },
  { name: "G.D. Goenka Public School", city: "New Delhi", country: "India" },
  { name: "Sardar Patel Vidyalaya", city: "New Delhi", country: "India" },
  { name: "Air Force Bal Bharati School", city: "New Delhi", country: "India" },
  { name: "Mount St. Mary's School", city: "New Delhi", country: "India" },
  { name: "Carmel Convent School", city: "New Delhi", country: "India" },
  { name: "St. Columba's School", city: "New Delhi", country: "India" },
  { name: "St. Xavier's School, Delhi", city: "New Delhi", country: "India" },
  { name: "Loreto Convent School", city: "New Delhi", country: "India" },
  { name: "Convent of Jesus and Mary, New Delhi", city: "New Delhi", country: "India" },
  { name: "Tagore International School", city: "New Delhi", country: "India" },
  { name: "Bal Bharati Public School, Pitampura", city: "New Delhi", country: "India" },
  { name: "Apeejay School, Saket", city: "New Delhi", country: "India" },
  { name: "Amity International School, Saket", city: "New Delhi", country: "India" },
  { name: "Amity International School, Sector 46", city: "Gurgaon", country: "India" },
  { name: "Amity International School, Noida", city: "Noida", country: "India" },
  { name: "Pathways School Gurgaon", city: "Gurgaon", country: "India" },
  { name: "Pathways School Noida", city: "Noida", country: "India" },
  { name: "Pathways World School, Aravali", city: "Gurgaon", country: "India" },
  { name: "GD Goenka World School", city: "Gurgaon", country: "India" },
  { name: "Heritage Xperiential Learning School", city: "Gurgaon", country: "India" },
  { name: "Lancers International School", city: "Gurgaon", country: "India" },
  { name: "Scottish High International School", city: "Gurgaon", country: "India" },
  { name: "DPS International, Saket", city: "New Delhi", country: "India" },
  { name: "DPS International, Gurgaon", city: "Gurgaon", country: "India" },
  { name: "Step by Step School, Noida", city: "Noida", country: "India" },
  { name: "Genesis Global School", city: "Noida", country: "India" },
  { name: "Lotus Valley International School", city: "Noida", country: "India" },
  { name: "Cambridge School, Noida", city: "Noida", country: "India" },
  { name: "Manav Rachna International School", city: "Faridabad", country: "India" },
  { name: "K.R. Mangalam World School", city: "New Delhi", country: "India" },
  { name: "Salwan Public School", city: "New Delhi", country: "India" },
  { name: "Ramjas School, R.K. Puram", city: "New Delhi", country: "India" },

  // Mumbai
  { name: "Cathedral and John Connon School", city: "Mumbai", country: "India" },
  { name: "Dhirubhai Ambani International School", city: "Mumbai", country: "India" },
  { name: "Jamnabai Narsee School", city: "Mumbai", country: "India" },
  { name: "Bombay Scottish School, Mahim", city: "Mumbai", country: "India" },
  { name: "Bombay Scottish School, Powai", city: "Mumbai", country: "India" },
  { name: "Campion School", city: "Mumbai", country: "India" },
  { name: "St. Mary's School (ICSE)", city: "Mumbai", country: "India" },
  { name: "St. Xavier's High School, Fort", city: "Mumbai", country: "India" },
  { name: "Don Bosco High School, Matunga", city: "Mumbai", country: "India" },
  { name: "Bombay International School", city: "Mumbai", country: "India" },
  { name: "Ecole Mondiale World School", city: "Mumbai", country: "India" },
  { name: "American School of Bombay", city: "Mumbai", country: "India" },
  { name: "Aditya Birla World Academy", city: "Mumbai", country: "India" },
  { name: "Oberoi International School, JVLR", city: "Mumbai", country: "India" },
  { name: "Oberoi International School, OGC", city: "Mumbai", country: "India" },
  { name: "Singapore International School", city: "Mumbai", country: "India" },
  { name: "JBCN International School", city: "Mumbai", country: "India" },
  { name: "Hiranandani Foundation School", city: "Mumbai", country: "India" },
  { name: "Podar International School", city: "Mumbai", country: "India" },
  { name: "Arya Vidya Mandir, Bandra (West)", city: "Mumbai", country: "India" },
  { name: "Greenlawns High School", city: "Mumbai", country: "India" },
  { name: "Activity High School", city: "Mumbai", country: "India" },
  { name: "Smt. Sulochanadevi Singhania School", city: "Thane", country: "India" },
  { name: "C.P. Goenka International School", city: "Mumbai", country: "India" },
  { name: "Lilavatibai Podar High School", city: "Mumbai", country: "India" },

  // Bangalore
  { name: "Bishop Cotton Boys' School", city: "Bangalore", country: "India" },
  { name: "Bishop Cotton Girls' School", city: "Bangalore", country: "India" },
  { name: "National Public School, Indiranagar", city: "Bangalore", country: "India" },
  { name: "National Public School, Koramangala", city: "Bangalore", country: "India" },
  { name: "National Public School, Rajajinagar", city: "Bangalore", country: "India" },
  { name: "National Public School, HSR Layout", city: "Bangalore", country: "India" },
  { name: "Inventure Academy", city: "Bangalore", country: "India" },
  { name: "Indus International School, Bangalore", city: "Bangalore", country: "India" },
  { name: "Greenwood High International School", city: "Bangalore", country: "India" },
  { name: "Stonehill International School", city: "Bangalore", country: "India" },
  { name: "Canadian International School, Bangalore", city: "Bangalore", country: "India" },
  { name: "The International School Bangalore (TISB)", city: "Bangalore", country: "India" },
  { name: "Mallya Aditi International School", city: "Bangalore", country: "India" },
  { name: "Vidyashilp Academy", city: "Bangalore", country: "India" },
  { name: "Delhi Public School, Bangalore South", city: "Bangalore", country: "India" },
  { name: "Delhi Public School, Bangalore North", city: "Bangalore", country: "India" },
  { name: "Delhi Public School, Bangalore East", city: "Bangalore", country: "India" },
  { name: "Sishu Griha Senior School", city: "Bangalore", country: "India" },
  { name: "Frank Anthony Public School", city: "Bangalore", country: "India" },
  { name: "Baldwin Boys' High School", city: "Bangalore", country: "India" },
  { name: "Baldwin Girls' High School", city: "Bangalore", country: "India" },
  { name: "Sophia High School", city: "Bangalore", country: "India" },
  { name: "St. Joseph's Indian High School", city: "Bangalore", country: "India" },
  { name: "Cluny Convent High School", city: "Bangalore", country: "India" },
  { name: "Mount Carmel Central School", city: "Bangalore", country: "India" },
  { name: "Christ Academy", city: "Bangalore", country: "India" },
  { name: "Ryan International School, Bangalore", city: "Bangalore", country: "India" },
  { name: "Bethany High School", city: "Bangalore", country: "India" },
  { name: "Whitefield Global School", city: "Bangalore", country: "India" },
  { name: "Treamis World School", city: "Bangalore", country: "India" },

  // Chennai
  { name: "PSBB Senior Secondary School", city: "Chennai", country: "India" },
  { name: "PSBB Millennium School", city: "Chennai", country: "India" },
  { name: "Don Bosco Matriculation, Egmore", city: "Chennai", country: "India" },
  { name: "Sishya School, Adyar", city: "Chennai", country: "India" },
  { name: "Chettinad Vidyashram", city: "Chennai", country: "India" },
  { name: "DAV Boys Senior Secondary School", city: "Chennai", country: "India" },
  { name: "Vidya Mandir Senior Secondary School", city: "Chennai", country: "India" },
  { name: "Sir Sivaswami Kalalaya", city: "Chennai", country: "India" },
  { name: "Lady Andal Venkatasubba Rao School", city: "Chennai", country: "India" },
  { name: "American International School Chennai", city: "Chennai", country: "India" },
  { name: "Chennai Public School, Anna Nagar", city: "Chennai", country: "India" },
  { name: "The School, KFI", city: "Chennai", country: "India" },
  { name: "Akshara Vaani International School", city: "Chennai", country: "India" },
  { name: "British International School, Chennai", city: "Chennai", country: "India" },

  // Hyderabad
  { name: "Hyderabad Public School, Begumpet", city: "Hyderabad", country: "India" },
  { name: "Hyderabad Public School, Ramanthapur", city: "Hyderabad", country: "India" },
  { name: "Chirec International School", city: "Hyderabad", country: "India" },
  { name: "Oakridge International School, Gachibowli", city: "Hyderabad", country: "India" },
  { name: "Oakridge International School, Bachupally", city: "Hyderabad", country: "India" },
  { name: "Indus International School, Hyderabad", city: "Hyderabad", country: "India" },
  { name: "International School of Hyderabad", city: "Hyderabad", country: "India" },
  { name: "Glendale Academy", city: "Hyderabad", country: "India" },
  { name: "Delhi Public School, Hyderabad", city: "Hyderabad", country: "India" },
  { name: "Meridian School", city: "Hyderabad", country: "India" },
  { name: "Bharatiya Vidya Bhavan's Public School", city: "Hyderabad", country: "India" },
  { name: "Johnson Grammar School", city: "Hyderabad", country: "India" },
  { name: "Jubilee Hills Public School", city: "Hyderabad", country: "India" },

  // Kolkata
  { name: "La Martiniere for Boys, Kolkata", city: "Kolkata", country: "India" },
  { name: "La Martiniere for Girls, Kolkata", city: "Kolkata", country: "India" },
  { name: "St. Xavier's Collegiate School, Kolkata", city: "Kolkata", country: "India" },
  { name: "Don Bosco School, Park Circus", city: "Kolkata", country: "India" },
  { name: "South Point High School", city: "Kolkata", country: "India" },
  { name: "Modern High School for Girls", city: "Kolkata", country: "India" },
  { name: "Calcutta Boys' School", city: "Kolkata", country: "India" },
  { name: "Calcutta Girls' High School", city: "Kolkata", country: "India" },
  { name: "Loreto House", city: "Kolkata", country: "India" },
  { name: "Heritage School, Kolkata", city: "Kolkata", country: "India" },
  { name: "Delhi Public School, Ruby Park", city: "Kolkata", country: "India" },
  { name: "Mahadevi Birla World Academy", city: "Kolkata", country: "India" },
  { name: "Calcutta International School", city: "Kolkata", country: "India" },
  { name: "Lakshmipat Singhania Academy", city: "Kolkata", country: "India" },

  // Pune
  { name: "Bishop's School, Camp", city: "Pune", country: "India" },
  { name: "Bishop's School, Kalyani Nagar", city: "Pune", country: "India" },
  { name: "St. Mary's School, Pune", city: "Pune", country: "India" },
  { name: "St. Vincent's High School", city: "Pune", country: "India" },
  { name: "The Bishop's Co-Ed School, Undri", city: "Pune", country: "India" },
  { name: "Symbiosis International School", city: "Pune", country: "India" },
  { name: "Mahindra United World College", city: "Pune", country: "India" },
  { name: "Indus International School, Pune", city: "Pune", country: "India" },
  { name: "Mercedes-Benz International School", city: "Pune", country: "India" },
  { name: "Vibgyor High School, Pune", city: "Pune", country: "India" },
  { name: "Delhi Public School, Pune", city: "Pune", country: "India" },
  { name: "Hutchings High School", city: "Pune", country: "India" },
  { name: "St. Helena's School", city: "Pune", country: "India" },
  { name: "Loyola High School, Pune", city: "Pune", country: "India" },

  // Other major Indian cities
  { name: "Doon School", city: "Dehradun", country: "India" },
  { name: "Welham Boys' School", city: "Dehradun", country: "India" },
  { name: "Welham Girls' School", city: "Dehradun", country: "India" },
  { name: "Mayo College", city: "Ajmer", country: "India" },
  { name: "Mayo College Girls' School", city: "Ajmer", country: "India" },
  { name: "Scindia School", city: "Gwalior", country: "India" },
  { name: "Daly College", city: "Indore", country: "India" },
  { name: "Bishop Cotton School, Shimla", city: "Shimla", country: "India" },
  { name: "Lawrence School, Sanawar", city: "Sanawar", country: "India" },
  { name: "Lawrence School, Lovedale", city: "Ooty", country: "India" },
  { name: "Woodstock School", city: "Mussoorie", country: "India" },
  { name: "Ecole Globale International Girls' School", city: "Dehradun", country: "India" },
  { name: "St. George's College, Mussoorie", city: "Mussoorie", country: "India" },
  { name: "Sherwood College, Nainital", city: "Nainital", country: "India" },
  { name: "St. Joseph's College, Nainital", city: "Nainital", country: "India" },
  { name: "Rishi Valley School", city: "Chittoor", country: "India" },
  { name: "Rishikul Vidyapeeth", city: "Sonepat", country: "India" },
  { name: "Yadavindra Public School, Patiala", city: "Patiala", country: "India" },
  { name: "Punjab Public School, Nabha", city: "Nabha", country: "India" },
  { name: "Sainik School (Various)", city: "Multiple Cities", country: "India" },
  { name: "Kendriya Vidyalaya (Various)", city: "Multiple Cities", country: "India" },
  { name: "Jawahar Navodaya Vidyalaya (Various)", city: "Multiple Cities", country: "India" },
  { name: "Ryan International School", city: "Multiple Cities", country: "India" },
  { name: "DAV Public School (Various)", city: "Multiple Cities", country: "India" },
  { name: "Kendriya Vidyalaya, IIT Kanpur", city: "Kanpur", country: "India" },
  { name: "City Montessori School, Lucknow", city: "Lucknow", country: "India" },
  { name: "La Martiniere College, Lucknow", city: "Lucknow", country: "India" },
  { name: "Loyola School, Jamshedpur", city: "Jamshedpur", country: "India" },
  { name: "DAV Public School, Jamshedpur", city: "Jamshedpur", country: "India" },
  { name: "Kendriya Vidyalaya, Bhubaneswar", city: "Bhubaneswar", country: "India" },
  { name: "DPS Kalinga, Cuttack", city: "Cuttack", country: "India" },
  { name: "St. Joseph's School, Bhubaneswar", city: "Bhubaneswar", country: "India" },
  { name: "Birla Public School, Pilani", city: "Pilani", country: "India" },
  { name: "Maharaja Sawai Man Singh Vidyalaya", city: "Jaipur", country: "India" },
  { name: "St. Xavier's School, Jaipur", city: "Jaipur", country: "India" },
  { name: "Neerja Modi School", city: "Jaipur", country: "India" },
  { name: "Jayshree Periwal International School", city: "Jaipur", country: "India" },
  { name: "Step by Step High School, Jaipur", city: "Jaipur", country: "India" },
  { name: "Delhi Public School, Jaipur", city: "Jaipur", country: "India" },
  { name: "Sanskar School", city: "Jaipur", country: "India" },
  { name: "Choithram School", city: "Indore", country: "India" },
  { name: "Emerald Heights International School", city: "Indore", country: "India" },
  { name: "The Heritage School, Vadodara", city: "Vadodara", country: "India" },
  { name: "Delhi Public School, Vadodara", city: "Vadodara", country: "India" },
  { name: "Nirma Vidyavihar", city: "Ahmedabad", country: "India" },
  { name: "Udgam School for Children", city: "Ahmedabad", country: "India" },
  { name: "Delhi Public School, Bopal", city: "Ahmedabad", country: "India" },
  { name: "Anand Niketan School", city: "Ahmedabad", country: "India" },
  { name: "Mahatma Gandhi International School", city: "Ahmedabad", country: "India" },
  { name: "Ahmedabad International School", city: "Ahmedabad", country: "India" },
  { name: "Eklavya School", city: "Ahmedabad", country: "India" },
  { name: "Calorx Public School", city: "Ahmedabad", country: "India" },
  { name: "Loyola Hall, Ahmedabad", city: "Ahmedabad", country: "India" },
  { name: "Loyola School, Trivandrum", city: "Thiruvananthapuram", country: "India" },
  { name: "Bhavans Munshi Vidyashram", city: "Kochi", country: "India" },
  { name: "Choice School, Kochi", city: "Kochi", country: "India" },
  { name: "Global Public School, Kochi", city: "Kochi", country: "India" },
  { name: "Toc H Public School", city: "Kochi", country: "India" },
  { name: "Naval Public School, Kochi", city: "Kochi", country: "India" },
  { name: "Hill Spring International School", city: "Mumbai", country: "India" },
  { name: "St. Joseph's Boys' High School, Bangalore", city: "Bangalore", country: "India" },
  { name: "St. Anthony's High School, Shillong", city: "Shillong", country: "India" },
  { name: "Don Bosco School, Liluah", city: "Howrah", country: "India" },
  { name: "Birla High School, Mukundapur", city: "Kolkata", country: "India" },
  { name: "Vivekananda Mission School", city: "Kolkata", country: "India" },

  
  // Singapore
  { name: "Raffles Institution", city: "Singapore", country: "Singapore" },
  { name: "Hwa Chong Institution", city: "Singapore", country: "Singapore" },
  { name: "National Junior College", city: "Singapore", country: "Singapore" },
  { name: "Victoria Junior College", city: "Singapore", country: "Singapore" },
  { name: "Anglo-Chinese School (Independent)", city: "Singapore", country: "Singapore" },
  { name: "Singapore American School", city: "Singapore", country: "Singapore" },
  { name: "United World College of South East Asia", city: "Singapore", country: "Singapore" },
  { name: "Tanglin Trust School", city: "Singapore", country: "Singapore" },
  { name: "Canadian International School", city: "Singapore", country: "Singapore" },
  { name: "Dulwich College Singapore", city: "Singapore", country: "Singapore" },
  
  // China
  { name: "High School Affiliated to Peking University", city: "Beijing", country: "China" },
  { name: "High School Affiliated to Renmin University", city: "Beijing", country: "China" },
  { name: "Beijing No. 4 High School", city: "Beijing", country: "China" },
  { name: "Shanghai High School", city: "Shanghai", country: "China" },
  { name: "Shanghai Foreign Language School", city: "Shanghai", country: "China" },
  { name: "Shenzhen Middle School", city: "Shenzhen", country: "China" },
  { name: "Nanjing Foreign Language School", city: "Nanjing", country: "China" },
  { name: "Hangzhou No. 2 High School", city: "Hangzhou", country: "China" },
  { name: "Dulwich College Beijing", city: "Beijing", country: "China" },
  { name: "Shanghai American School", city: "Shanghai", country: "China" },
  
  // UAE
  { name: "Dubai College", city: "Dubai", country: "UAE" },
  { name: "GEMS Dubai American Academy", city: "Dubai", country: "UAE" },
  { name: "American School of Dubai", city: "Dubai", country: "UAE" },
  { name: "Dubai British School", city: "Dubai", country: "UAE" },
  { name: "GEMS World Academy", city: "Dubai", country: "UAE" },
  { name: "Kings' School Dubai", city: "Dubai", country: "UAE" },
  { name: "Repton School Dubai", city: "Dubai", country: "UAE" },
  { name: "Dubai International Academy", city: "Dubai", country: "UAE" },
  { name: "American Community School Abu Dhabi", city: "Abu Dhabi", country: "UAE" },
  { name: "Cranleigh Abu Dhabi", city: "Abu Dhabi", country: "UAE" },
  
  // Canada
  { name: "Upper Canada College", city: "Toronto", country: "Canada" },
  { name: "Ridley College", city: "St. Catharines", country: "Canada" },
  { name: "Trinity College School", city: "Port Hope", country: "Canada" },
  { name: "Havergal College", city: "Toronto", country: "Canada" },
  { name: "St. Andrew's College", city: "Aurora", country: "Canada" },
  { name: "Appleby College", city: "Oakville", country: "Canada" },
  { name: "Shawnigan Lake School", city: "Shawnigan Lake", country: "Canada" },
  { name: "Brentwood College School", city: "Mill Bay", country: "Canada" },
  { name: "St. George's School", city: "Vancouver", country: "Canada" },
  { name: "West Point Grey Academy", city: "Vancouver", country: "Canada" },
  
  // Australia
  { name: "Sydney Grammar School", city: "Sydney", country: "Australia" },
  { name: "Melbourne Grammar School", city: "Melbourne", country: "Australia" },
  { name: "The King's School", city: "Sydney", country: "Australia" },
  { name: "Scotch College", city: "Melbourne", country: "Australia" },
  { name: "Brisbane Grammar School", city: "Brisbane", country: "Australia" },
  { name: "Perth Modern School", city: "Perth", country: "Australia" },
  { name: "James Ruse Agricultural High School", city: "Sydney", country: "Australia" },
  { name: "North Sydney Boys High School", city: "Sydney", country: "Australia" },
  { name: "Geelong Grammar School", city: "Geelong", country: "Australia" },
  { name: "Wesley College", city: "Melbourne", country: "Australia" },
  
  // Germany
  { name: "Berlin International School", city: "Berlin", country: "Germany" },
  { name: "International School of Hamburg", city: "Hamburg", country: "Germany" },
  { name: "Munich International School", city: "Munich", country: "Germany" },
  { name: "Frankfurt International School", city: "Frankfurt", country: "Germany" },
  { name: "St. George's School Cologne", city: "Cologne", country: "Germany" },
  { name: "UWC Robert Bosch College", city: "Freiburg", country: "Germany" },
  { name: "Salem International College", city: "Salem", country: "Germany" },
  { name: "Phorms School Berlin", city: "Berlin", country: "Germany" },
  { name: "Bavarian International School", city: "Munich", country: "Germany" },
  { name: "Leipzig International School", city: "Leipzig", country: "Germany" },
  
  // France
  { name: "Lycée Louis-le-Grand", city: "Paris", country: "France" },
  { name: "Lycée Henri-IV", city: "Paris", country: "France" },
  { name: "International School of Paris", city: "Paris", country: "France" },
  { name: "American School of Paris", city: "Paris", country: "France" },
  { name: "Lycée International", city: "Saint-Germain-en-Laye", country: "France" },
  { name: "British School of Paris", city: "Paris", country: "France" },
  { name: "Lycée Stanislas", city: "Paris", country: "France" },
  { name: "Lycée du Parc", city: "Lyon", country: "France" },
  { name: "Marymount International School", city: "Paris", country: "France" },
  { name: "Ecole Jeannine Manuel", city: "Paris", country: "France" },
  
  // Japan
  { name: "Nada High School", city: "Kobe", country: "Japan" },
  { name: "Kaisei Academy", city: "Tokyo", country: "Japan" },
  { name: "Azabu High School", city: "Tokyo", country: "Japan" },
  { name: "American School in Japan", city: "Tokyo", country: "Japan" },
  { name: "International School of the Sacred Heart", city: "Tokyo", country: "Japan" },
  { name: "Yokohama International School", city: "Yokohama", country: "Japan" },
  { name: "Canadian Academy", city: "Kobe", country: "Japan" },
  { name: "St. Mary's International School", city: "Tokyo", country: "Japan" },
  { name: "Hiroo Gakuen High School", city: "Tokyo", country: "Japan" },
  { name: "Keio Shonan Fujisawa", city: "Kanagawa", country: "Japan" },
  
  // South Korea
  { name: "Seoul International School", city: "Seoul", country: "South Korea" },
  { name: "Korea International School", city: "Seoul", country: "South Korea" },
  { name: "Yongsan International School of Seoul", city: "Seoul", country: "South Korea" },
  { name: "Dwight School Seoul", city: "Seoul", country: "South Korea" },
  { name: "Branksome Hall Asia", city: "Jeju", country: "South Korea" },
  { name: "North London Collegiate School Jeju", city: "Jeju", country: "South Korea" },
  { name: "Chadwick International", city: "Incheon", country: "South Korea" },
  { name: "Seoul Foreign School", city: "Seoul", country: "South Korea" },
  { name: "Gyeonggi Suwon International School", city: "Suwon", country: "South Korea" },
  { name: "Korea Kent Foreign School", city: "Seoul", country: "South Korea" },
  
  // Switzerland
  { name: "Le Rosey", city: "Rolle", country: "Switzerland" },
  { name: "Aiglon College", city: "Chesières-Villars", country: "Switzerland" },
  { name: "Leysin American School", city: "Leysin", country: "Switzerland" },
  { name: "TASIS The American School in Switzerland", city: "Montagnola", country: "Switzerland" },
  { name: "College du Leman", city: "Versoix", country: "Switzerland" },
  { name: "International School of Geneva", city: "Geneva", country: "Switzerland" },
  { name: "Zurich International School", city: "Zurich", country: "Switzerland" },
  { name: "Brillantmont International School", city: "Lausanne", country: "Switzerland" },
  { name: "Institut Le Rosey", city: "Gstaad", country: "Switzerland" },
  { name: "Ecole Internationale de Genève", city: "Geneva", country: "Switzerland" },
  
  // Hong Kong
  { name: "Hong Kong International School", city: "Hong Kong", country: "Hong Kong" },
  { name: "Chinese International School", city: "Hong Kong", country: "Hong Kong" },
  { name: "Diocesan Boys' School", city: "Hong Kong", country: "Hong Kong" },
  { name: "St. Paul's Co-educational College", city: "Hong Kong", country: "Hong Kong" },
  { name: "Victoria Shanghai Academy", city: "Hong Kong", country: "Hong Kong" },
  { name: "South Island School", city: "Hong Kong", country: "Hong Kong" },
  { name: "Island School", city: "Hong Kong", country: "Hong Kong" },
  { name: "King George V School", city: "Hong Kong", country: "Hong Kong" },
  { name: "German Swiss International School", city: "Hong Kong", country: "Hong Kong" },
  { name: "Harrow International School Hong Kong", city: "Hong Kong", country: "Hong Kong" },
  
  // Netherlands
  { name: "International School of Amsterdam", city: "Amsterdam", country: "Netherlands" },
  { name: "British School of Amsterdam", city: "Amsterdam", country: "Netherlands" },
  { name: "Rotterdam International Secondary School", city: "Rotterdam", country: "Netherlands" },
  { name: "American School of The Hague", city: "The Hague", country: "Netherlands" },
  { name: "International School of The Hague", city: "The Hague", country: "Netherlands" },
  { name: "Leiden International School", city: "Leiden", country: "Netherlands" },
  { name: "International School Hilversum", city: "Hilversum", country: "Netherlands" },
  { name: "Nord Anglia International School", city: "Rotterdam", country: "Netherlands" },
  { name: "European School The Hague", city: "The Hague", country: "Netherlands" },
  { name: "Maastricht International School", city: "Maastricht", country: "Netherlands" },
  
  // Spain
  { name: "American School of Madrid", city: "Madrid", country: "Spain" },
  { name: "British Council School", city: "Madrid", country: "Spain" },
  { name: "American School of Barcelona", city: "Barcelona", country: "Spain" },
  { name: "Benjamin Franklin International School", city: "Barcelona", country: "Spain" },
  { name: "International School of Barcelona", city: "Barcelona", country: "Spain" },
  { name: "Sotogrande International School", city: "Sotogrande", country: "Spain" },
  { name: "The Lady Elizabeth School", city: "Alicante", country: "Spain" },
  { name: "Aloha College", city: "Marbella", country: "Spain" },
  { name: "King's College Madrid", city: "Madrid", country: "Spain" },
  { name: "Runnymede College", city: "Madrid", country: "Spain" },
  
  // Thailand
  { name: "International School Bangkok", city: "Bangkok", country: "Thailand" },
  { name: "NIST International School", city: "Bangkok", country: "Thailand" },
  { name: "Bangkok Patana School", city: "Bangkok", country: "Thailand" },
  { name: "Shrewsbury International School", city: "Bangkok", country: "Thailand" },
  { name: "Ruamrudee International School", city: "Bangkok", country: "Thailand" },
  { name: "Harrow International School Bangkok", city: "Bangkok", country: "Thailand" },
  { name: "St. Andrews International School", city: "Bangkok", country: "Thailand" },
  { name: "Wellington College International", city: "Bangkok", country: "Thailand" },
  { name: "Prem Tinsulanonda International School", city: "Chiang Mai", country: "Thailand" },
  { name: "Regent's International School", city: "Bangkok", country: "Thailand" },
  
  // Mexico
  { name: "American School Foundation", city: "Mexico City", country: "Mexico" },
  { name: "Colegio Peterson", city: "Mexico City", country: "Mexico" },
  { name: "Greengates School", city: "Mexico City", country: "Mexico" },
  { name: "American School of Guadalajara", city: "Guadalajara", country: "Mexico" },
  { name: "Tecnológico de Monterrey High School", city: "Monterrey", country: "Mexico" },
  { name: "Instituto México de Monterrey", city: "Monterrey", country: "Mexico" },
  { name: "Colegio Americano de Puebla", city: "Puebla", country: "Mexico" },
  { name: "American School of Puerto Vallarta", city: "Puerto Vallarta", country: "Mexico" },
  { name: "British American School", city: "Mexico City", country: "Mexico" },
  { name: "Colegio Vista Hermosa", city: "Mexico City", country: "Mexico" },
  
  // Brazil
  { name: "Graded School", city: "São Paulo", country: "Brazil" },
  { name: "American School of Rio de Janeiro", city: "Rio de Janeiro", country: "Brazil" },
  { name: "Escola Americana de Brasília", city: "Brasília", country: "Brazil" },
  { name: "St. Paul's School", city: "São Paulo", country: "Brazil" },
  { name: "Chapel School", city: "São Paulo", country: "Brazil" },
  { name: "Pan American School of Porto Alegre", city: "Porto Alegre", country: "Brazil" },
  { name: "Escola Americana de Belo Horizonte", city: "Belo Horizonte", country: "Brazil" },
  { name: "British School of Rio de Janeiro", city: "Rio de Janeiro", country: "Brazil" },
  { name: "American School of Campinas", city: "Campinas", country: "Brazil" },
  { name: "International School of Curitiba", city: "Curitiba", country: "Brazil" },
  
  // South Africa
  { name: "American International School of Johannesburg", city: "Johannesburg", country: "South Africa" },
  { name: "International School of South Africa", city: "Mafikeng", country: "South Africa" },
  { name: "Bishops Diocesan College", city: "Cape Town", country: "South Africa" },
  { name: "Hilton College", city: "Hilton", country: "South Africa" },
  { name: "Michaelhouse", city: "Balgowan", country: "South Africa" },
  { name: "St. Stithians College", city: "Johannesburg", country: "South Africa" },
  { name: "Rondebosch Boys' High School", city: "Cape Town", country: "South Africa" },
  { name: "Pretoria Boys High School", city: "Pretoria", country: "South Africa" },
  { name: "Reddam House", city: "Cape Town", country: "South Africa" },
  { name: "Waterford Kamhlaba", city: "Mbabane", country: "South Africa" },
  
  // Nigeria
  { name: "American International School of Lagos", city: "Lagos", country: "Nigeria" },
  { name: "British International School Lagos", city: "Lagos", country: "Nigeria" },
  { name: "Corona Secondary School", city: "Lagos", country: "Nigeria" },
  { name: "Loyola Jesuit College", city: "Abuja", country: "Nigeria" },
  { name: "Atlantic Hall", city: "Lagos", country: "Nigeria" },
  { name: "Greensprings School", city: "Lagos", country: "Nigeria" },
  { name: "Whitesands School", city: "Lagos", country: "Nigeria" },
  { name: "Meadow Hall", city: "Lagos", country: "Nigeria" },
  { name: "Christ the King College", city: "Onitsha", country: "Nigeria" },
  { name: "Federal Government College", city: "Lagos", country: "Nigeria" },
  
  // Kenya
  { name: "International School of Kenya", city: "Nairobi", country: "Kenya" },
  { name: "Brookhouse School", city: "Nairobi", country: "Kenya" },
  { name: "Braeburn International School", city: "Nairobi", country: "Kenya" },
  { name: "Hillcrest International Schools", city: "Nairobi", country: "Kenya" },
  { name: "Aga Khan Academy", city: "Nairobi", country: "Kenya" },
  { name: "Rosslyn Academy", city: "Nairobi", country: "Kenya" },
  { name: "Peponi School", city: "Nairobi", country: "Kenya" },
  { name: "Banda School", city: "Nairobi", country: "Kenya" },
  { name: "Riara School", city: "Nairobi", country: "Kenya" },
  { name: "St. Andrew's Turi", city: "Molo", country: "Kenya" },
  
  // Egypt
  { name: "Cairo American College", city: "Cairo", country: "Egypt" },
  { name: "American International School in Egypt", city: "Cairo", country: "Egypt" },
  { name: "British International School in Cairo", city: "Cairo", country: "Egypt" },
  { name: "Maadi British International School", city: "Cairo", country: "Egypt" },
  { name: "GEMS American Academy", city: "Cairo", country: "Egypt" },
  { name: "Modern English School Cairo", city: "Cairo", country: "Egypt" },
  { name: "Schutz American School", city: "Alexandria", country: "Egypt" },
  { name: "Deutsche Evangelische Oberschule", city: "Cairo", country: "Egypt" },
  { name: "International School of Choueifat", city: "Cairo", country: "Egypt" },
  { name: "New Cairo British International School", city: "Cairo", country: "Egypt" },
  
  // Philippines
  { name: "International School Manila", city: "Manila", country: "Philippines" },
  { name: "Brent International School", city: "Manila", country: "Philippines" },
  { name: "British School Manila", city: "Manila", country: "Philippines" },
  { name: "Chinese International School Manila", city: "Manila", country: "Philippines" },
  { name: "Beacon Academy", city: "Laguna", country: "Philippines" },
  { name: "Southville International School", city: "Manila", country: "Philippines" },
  { name: "Ateneo de Manila High School", city: "Manila", country: "Philippines" },
  { name: "De La Salle Zobel", city: "Manila", country: "Philippines" },
  { name: "Xavier School", city: "Manila", country: "Philippines" },
  { name: "Philippine Science High School", city: "Manila", country: "Philippines" },
  
  // Indonesia
  { name: "Jakarta Intercultural School", city: "Jakarta", country: "Indonesia" },
  { name: "British School Jakarta", city: "Jakarta", country: "Indonesia" },
  { name: "Singapore International School", city: "Jakarta", country: "Indonesia" },
  { name: "ACG School Jakarta", city: "Jakarta", country: "Indonesia" },
  { name: "Bali Island School", city: "Bali", country: "Indonesia" },
  { name: "Bandung International School", city: "Bandung", country: "Indonesia" },
  { name: "Surabaya Intercultural School", city: "Surabaya", country: "Indonesia" },
  { name: "Sekolah Pelita Harapan", city: "Jakarta", country: "Indonesia" },
  { name: "Gandhi Memorial Intercontinental School", city: "Jakarta", country: "Indonesia" },
  { name: "Mentari Intercultural School", city: "Jakarta", country: "Indonesia" },
  
  // Malaysia
  { name: "International School of Kuala Lumpur", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Garden International School", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Alice Smith School", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Cempaka Schools", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Mont'Kiara International School", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Marlborough College Malaysia", city: "Johor Bahru", country: "Malaysia" },
  { name: "Epsom College in Malaysia", city: "Selangor", country: "Malaysia" },
  { name: "GEMS International School", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Nexus International School", city: "Kuala Lumpur", country: "Malaysia" },
  { name: "Sri KDU International School", city: "Kuala Lumpur", country: "Malaysia" },
  
  // Vietnam
  { name: "Saigon South International School", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "British International School Ho Chi Minh City", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "United Nations International School Hanoi", city: "Hanoi", country: "Vietnam" },
  { name: "American International School Vietnam", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "European International School", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Australian International School", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Singapore International School", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Concordia International School Hanoi", city: "Hanoi", country: "Vietnam" },
  { name: "International School of Vietnam", city: "Hanoi", country: "Vietnam" },
  { name: "Renaissance International School Saigon", city: "Ho Chi Minh City", country: "Vietnam" },
  
  // Pakistan
  { name: "Karachi American School", city: "Karachi", country: "Pakistan" },
  { name: "Lahore American School", city: "Lahore", country: "Pakistan" },
  { name: "Islamabad College for Girls", city: "Islamabad", country: "Pakistan" },
  { name: "Aitchison College", city: "Lahore", country: "Pakistan" },
  { name: "Lahore Grammar School", city: "Lahore", country: "Pakistan" },
  { name: "Beaconhouse School System", city: "Multiple Cities", country: "Pakistan" },
  { name: "The City School", city: "Multiple Cities", country: "Pakistan" },
  { name: "Karachi Grammar School", city: "Karachi", country: "Pakistan" },
  { name: "Roots School System", city: "Islamabad", country: "Pakistan" },
  { name: "International School of Islamabad", city: "Islamabad", country: "Pakistan" },
  
  // Turkey
  { name: "Robert College", city: "Istanbul", country: "Turkey" },
  { name: "American Collegiate Institute", city: "Izmir", country: "Turkey" },
  { name: "Koç School", city: "Istanbul", country: "Turkey" },
  { name: "UWC Atlantic College Turkey", city: "Istanbul", country: "Turkey" },
  { name: "Istanbul International Community School", city: "Istanbul", country: "Turkey" },
  { name: "British International School Istanbul", city: "Istanbul", country: "Turkey" },
  { name: "Enka Schools", city: "Istanbul", country: "Turkey" },
  { name: "MEF International School", city: "Istanbul", country: "Turkey" },
  { name: "TED Ankara College", city: "Ankara", country: "Turkey" },
  { name: "Bilkent Laboratory and International School", city: "Ankara", country: "Turkey" },
  
  // Saudi Arabia
  { name: "American International School Riyadh", city: "Riyadh", country: "Saudi Arabia" },
  { name: "British International School Riyadh", city: "Riyadh", country: "Saudi Arabia" },
  { name: "KAUST Schools", city: "Thuwal", country: "Saudi Arabia" },
  { name: "American International School Jeddah", city: "Jeddah", country: "Saudi Arabia" },
  { name: "British International School Jeddah", city: "Jeddah", country: "Saudi Arabia" },
  { name: "Dhahran Ahliyya Schools", city: "Dhahran", country: "Saudi Arabia" },
  { name: "International Schools Group", city: "Dammam", country: "Saudi Arabia" },
  { name: "Riyadh Schools", city: "Riyadh", country: "Saudi Arabia" },
  { name: "Al-Yasmin International School", city: "Riyadh", country: "Saudi Arabia" },
  { name: "Dammam International School", city: "Dammam", country: "Saudi Arabia" },
  
  // Qatar
  { name: "American School of Doha", city: "Doha", country: "Qatar" },
  { name: "Doha College", city: "Doha", country: "Qatar" },
  { name: "Qatar Academy", city: "Doha", country: "Qatar" },
  { name: "Park House English School", city: "Doha", country: "Qatar" },
  { name: "ACS Doha International School", city: "Doha", country: "Qatar" },
  { name: "Swiss International School Qatar", city: "Doha", country: "Qatar" },
  { name: "Compass International School", city: "Doha", country: "Qatar" },
  { name: "Newton International School", city: "Doha", country: "Qatar" },
  { name: "Doha British School", city: "Doha", country: "Qatar" },
  { name: "SEK International School", city: "Doha", country: "Qatar" },
  
  // Kuwait
  { name: "American School of Kuwait", city: "Kuwait City", country: "Kuwait" },
  { name: "British School of Kuwait", city: "Kuwait City", country: "Kuwait" },
  { name: "American International School Kuwait", city: "Kuwait City", country: "Kuwait" },
  { name: "Universal American School", city: "Kuwait City", country: "Kuwait" },
  { name: "Kuwait English School", city: "Kuwait City", country: "Kuwait" },
  { name: "American Creativity Academy", city: "Kuwait City", country: "Kuwait" },
  { name: "Fawzia Sultan International School", city: "Kuwait City", country: "Kuwait" },
  { name: "Dasman Bilingual School", city: "Kuwait City", country: "Kuwait" },
  { name: "American Baccalaureate School", city: "Kuwait City", country: "Kuwait" },
  { name: "New English School", city: "Kuwait City", country: "Kuwait" },
  
  // Bahrain
  { name: "Bahrain Bayan School", city: "Manama", country: "Bahrain" },
  { name: "British School of Bahrain", city: "Manama", country: "Bahrain" },
  { name: "St. Christopher's School", city: "Manama", country: "Bahrain" },
  { name: "Ibn Khuldoon National School", city: "Manama", country: "Bahrain" },
  { name: "Al Raja School", city: "Manama", country: "Bahrain" },
  { name: "Bahrain School", city: "Manama", country: "Bahrain" },
  { name: "AMA International School", city: "Manama", country: "Bahrain" },
  { name: "Nadeen School", city: "Manama", country: "Bahrain" },
  { name: "Shaikha Hessa Girls School", city: "Manama", country: "Bahrain" },
  { name: "Al Noor International School", city: "Manama", country: "Bahrain" },
  
  // Israel
  { name: "American International School in Israel", city: "Even Yehuda", country: "Israel" },
  { name: "Walworth Barbour American International School", city: "Even Yehuda", country: "Israel" },
  { name: "Anglican International School Jerusalem", city: "Jerusalem", country: "Israel" },
  { name: "Eastern Mediterranean International School", city: "Tel Aviv", country: "Israel" },
  { name: "Tabeetha School", city: "Jaffa", country: "Israel" },
  { name: "Jerusalem American International School", city: "Jerusalem", country: "Israel" },
  
  // New Zealand
  { name: "Auckland Grammar School", city: "Auckland", country: "New Zealand" },
  { name: "Christ's College", city: "Christchurch", country: "New Zealand" },
  { name: "Kristin School", city: "Auckland", country: "New Zealand" },
  { name: "St Cuthbert's College", city: "Auckland", country: "New Zealand" },
  { name: "Wellington College", city: "Wellington", country: "New Zealand" },
  { name: "King's College", city: "Auckland", country: "New Zealand" },
  { name: "ACG Parnell College", city: "Auckland", country: "New Zealand" },
  { name: "Scots College", city: "Wellington", country: "New Zealand" },
  { name: "Diocesan School for Girls", city: "Auckland", country: "New Zealand" },
  { name: "Rangitoto College", city: "Auckland", country: "New Zealand" },
  
  // Poland
  { name: "American School of Warsaw", city: "Warsaw", country: "Poland" },
  { name: "British School Warsaw", city: "Warsaw", country: "Poland" },
  { name: "International American School of Warsaw", city: "Warsaw", country: "Poland" },
  { name: "International School of Krakow", city: "Krakow", country: "Poland" },
  { name: "Wroclaw International School", city: "Wroclaw", country: "Poland" },
  { name: "British International School of Krakow", city: "Krakow", country: "Poland" },
  { name: "Canadian School of Warsaw", city: "Warsaw", country: "Poland" },
  { name: "International School of Poznan", city: "Poznan", country: "Poland" },
  { name: "Meridian International School", city: "Warsaw", country: "Poland" },
  { name: "The International School of Gdansk", city: "Gdansk", country: "Poland" },
  
  // Czech Republic
  { name: "International School of Prague", city: "Prague", country: "Czech Republic" },
  { name: "Prague British International School", city: "Prague", country: "Czech Republic" },
  { name: "Riverside School Prague", city: "Prague", country: "Czech Republic" },
  { name: "English International School of Prague", city: "Prague", country: "Czech Republic" },
  { name: "Gymnázium PORG", city: "Prague", country: "Czech Republic" },
  
  // Russia
  { name: "Anglo-American School of Moscow", city: "Moscow", country: "Russia" },
  { name: "British International School Moscow", city: "Moscow", country: "Russia" },
  { name: "Moscow Economic School", city: "Moscow", country: "Russia" },
  { name: "International School of Moscow", city: "Moscow", country: "Russia" },
  { name: "St. Petersburg International School", city: "St. Petersburg", country: "Russia" },
  
  // Ireland
  { name: "St Andrew's College", city: "Dublin", country: "Ireland" },
  { name: "Blackrock College", city: "Dublin", country: "Ireland" },
  { name: "Gonzaga College", city: "Dublin", country: "Ireland" },
  { name: "St Michael's College", city: "Dublin", country: "Ireland" },
  { name: "Sutton Park School", city: "Dublin", country: "Ireland" },
  
  // Sweden
  { name: "International School of Stockholm", city: "Stockholm", country: "Sweden" },
  { name: "British International School of Stockholm", city: "Stockholm", country: "Sweden" },
  { name: "International School of Gothenburg", city: "Gothenburg", country: "Sweden" },
  { name: "Sigtunaskolan Humanistiska Läroverket", city: "Sigtuna", country: "Sweden" },
  { name: "Stockholm International School", city: "Stockholm", country: "Sweden" },
  
  // Norway
  { name: "Oslo International School", city: "Oslo", country: "Norway" },
  { name: "International School of Bergen", city: "Bergen", country: "Norway" },
  { name: "International School of Stavanger", city: "Stavanger", country: "Norway" },
  { name: "UWC Red Cross Nordic", city: "Flekke", country: "Norway" },
  { name: "Kristiansand International School", city: "Kristiansand", country: "Norway" },
  
  // Denmark
  { name: "Copenhagen International School", city: "Copenhagen", country: "Denmark" },
  { name: "International School of Billund", city: "Billund", country: "Denmark" },
  { name: "Rygaards International School", city: "Copenhagen", country: "Denmark" },
  { name: "Bjørns International School", city: "Copenhagen", country: "Denmark" },
  { name: "Herlufsholm School", city: "Næstved", country: "Denmark" },
  
  // Finland
  { name: "International School of Helsinki", city: "Helsinki", country: "Finland" },
  { name: "Finnish International School of Tampere", city: "Tampere", country: "Finland" },
  { name: "Ressu IB World School", city: "Helsinki", country: "Finland" },
  { name: "Mattlidens gymnasium", city: "Espoo", country: "Finland" },
  { name: "Oulu International School", city: "Oulu", country: "Finland" },
  
  // Austria
  { name: "American International School Vienna", city: "Vienna", country: "Austria" },
  { name: "Vienna International School", city: "Vienna", country: "Austria" },
  { name: "Danube International School", city: "Vienna", country: "Austria" },
  { name: "International School Salzburg", city: "Salzburg", country: "Austria" },
  { name: "St. Gilgen International School", city: "St. Gilgen", country: "Austria" },
  
  // Belgium
  { name: "International School of Brussels", city: "Brussels", country: "Belgium" },
  { name: "British School of Brussels", city: "Brussels", country: "Belgium" },
  { name: "St John's International School", city: "Waterloo", country: "Belgium" },
  { name: "Antwerp International School", city: "Antwerp", country: "Belgium" },
  { name: "International School of Antwerp", city: "Antwerp", country: "Belgium" },
  
  // Portugal
  { name: "American International School of Lisbon", city: "Lisbon", country: "Portugal" },
  { name: "St. Julian's School", city: "Lisbon", country: "Portugal" },
  { name: "Carlucci American International School of Lisbon", city: "Lisbon", country: "Portugal" },
  { name: "Oporto British School", city: "Porto", country: "Portugal" },
  { name: "International School of the Algarve", city: "Algarve", country: "Portugal" },
  
  // Italy
  { name: "American Overseas School of Rome", city: "Rome", country: "Italy" },
  { name: "St. Stephen's School Rome", city: "Rome", country: "Italy" },
  { name: "International School of Milan", city: "Milan", country: "Italy" },
  { name: "American School of Milan", city: "Milan", country: "Italy" },
  { name: "United World College of the Adriatic", city: "Duino", country: "Italy" },
  { name: "International School of Como", city: "Como", country: "Italy" },
  { name: "Marymount International School Rome", city: "Rome", country: "Italy" },
  { name: "John Cabot University High School", city: "Rome", country: "Italy" },
  { name: "International School of Florence", city: "Florence", country: "Italy" },
  { name: "H-FARM International School", city: "Treviso", country: "Italy" },
  
  // Greece
  { name: "American Community Schools of Athens", city: "Athens", country: "Greece" },
  { name: "Campion School", city: "Athens", country: "Greece" },
  { name: "St. Catherine's British School", city: "Athens", country: "Greece" },
  { name: "Pinewood International School", city: "Thessaloniki", country: "Greece" },
  { name: "International School of Athens", city: "Athens", country: "Greece" },
  
  // Argentina
  { name: "American Community School of Buenos Aires", city: "Buenos Aires", country: "Argentina" },
  { name: "Lincoln School Buenos Aires", city: "Buenos Aires", country: "Argentina" },
  { name: "Northlands School", city: "Buenos Aires", country: "Argentina" },
  { name: "St. Andrew's Scots School", city: "Buenos Aires", country: "Argentina" },
  { name: "Belgrano Day School", city: "Buenos Aires", country: "Argentina" },
  
  // Chile
  { name: "Santiago College", city: "Santiago", country: "Chile" },
  { name: "Nido de Aguilas", city: "Santiago", country: "Chile" },
  { name: "The Grange School", city: "Santiago", country: "Chile" },
  { name: "Redland School", city: "Santiago", country: "Chile" },
  { name: "International School Nido de Aguilas", city: "Santiago", country: "Chile" },
  
  // Colombia
  { name: "Colegio Nueva Granada", city: "Bogotá", country: "Colombia" },
  { name: "Colegio Anglo Colombiano", city: "Bogotá", country: "Colombia" },
  { name: "Columbus School", city: "Medellín", country: "Colombia" },
  { name: "Colegio Karl C. Parrish", city: "Barranquilla", country: "Colombia" },
  { name: "Colegio Bolívar", city: "Cali", country: "Colombia" },
  
  // Peru
  { name: "Colegio Franklin Delano Roosevelt", city: "Lima", country: "Peru" },
  { name: "Markham College", city: "Lima", country: "Peru" },
  { name: "Newton College", city: "Lima", country: "Peru" },
  { name: "San Silvestre School", city: "Lima", country: "Peru" },
  { name: "American School of Lima", city: "Lima", country: "Peru" },
  
  // Costa Rica
  { name: "Country Day School", city: "San José", country: "Costa Rica" },
  { name: "Lincoln School Costa Rica", city: "San José", country: "Costa Rica" },
  { name: "British School of Costa Rica", city: "San José", country: "Costa Rica" },
  { name: "International School of Costa Rica", city: "San José", country: "Costa Rica" },
  { name: "European School Costa Rica", city: "San José", country: "Costa Rica" },
  
  // Panama
  { name: "International School of Panama", city: "Panama City", country: "Panama" },
  { name: "Balboa Academy", city: "Panama City", country: "Panama" },
  { name: "Metropolitan School of Panama", city: "Panama City", country: "Panama" },
  { name: "King's College Panama", city: "Panama City", country: "Panama" },
  { name: "Oxford International School", city: "Panama City", country: "Panama" },

  // ── Middle East ──────────────────────────────────────────────────────
  { name: "American Community School of Abu Dhabi", city: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "American School of Dubai", city: "Dubai", country: "United Arab Emirates" },
  { name: "Dubai College", city: "Dubai", country: "United Arab Emirates" },
  { name: "GEMS Wellington International School", city: "Dubai", country: "United Arab Emirates" },
  { name: "Jumeirah College", city: "Dubai", country: "United Arab Emirates" },
  { name: "Cranleigh Abu Dhabi", city: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "King's Academy", city: "Madaba", country: "Jordan" },
  { name: "Amman Baccalaureate School", city: "Amman", country: "Jordan" },
  { name: "American School of Doha", city: "Doha", country: "Qatar" },
  { name: "Doha College", city: "Doha", country: "Qatar" },
  { name: "American School of Kuwait", city: "Kuwait City", country: "Kuwait" },
  { name: "British School Muscat", city: "Muscat", country: "Oman" },
  { name: "American International School of Riyadh", city: "Riyadh", country: "Saudi Arabia" },
  { name: "KAUST School", city: "Thuwal", country: "Saudi Arabia" },
  { name: "Eastern Mediterranean International School", city: "Hod HaSharon", country: "Israel" },

  // ── Africa ────────────────────────────────────────────────────────────
  { name: "African Leadership Academy", city: "Johannesburg", country: "South Africa" },
  { name: "St John's College", city: "Johannesburg", country: "South Africa" },
  { name: "Hilton College", city: "Hilton", country: "South Africa" },
  { name: "Bishops Diocesan College", city: "Cape Town", country: "South Africa" },
  { name: "International School of Kenya", city: "Nairobi", country: "Kenya" },
  { name: "Brookhouse School", city: "Nairobi", country: "Kenya" },
  { name: "American International School of Lagos", city: "Lagos", country: "Nigeria" },
  { name: "British International School Lagos", city: "Lagos", country: "Nigeria" },
  { name: "Loyola Jesuit College", city: "Abuja", country: "Nigeria" },
  { name: "SOS-Hermann Gmeiner International College", city: "Tema", country: "Ghana" },
  { name: "Cairo American College", city: "Cairo", country: "Egypt" },
  { name: "Schutz American School", city: "Alexandria", country: "Egypt" },
  { name: "American International School of Mozambique", city: "Maputo", country: "Mozambique" },

  // ── Additional Asia (under-represented) ──────────────────────────────
  { name: "United World College of South East Asia (Dover)", city: "Singapore", country: "Singapore" },
  { name: "Raffles Institution", city: "Singapore", country: "Singapore" },
  { name: "Hwa Chong Institution", city: "Singapore", country: "Singapore" },
  { name: "NUS High School of Mathematics and Science", city: "Singapore", country: "Singapore" },
  { name: "Anglo-Chinese School (Independent)", city: "Singapore", country: "Singapore" },
  { name: "International School Manila", city: "Manila", country: "Philippines" },
  { name: "Philippine Science High School", city: "Quezon City", country: "Philippines" },
  { name: "Jakarta Intercultural School", city: "Jakarta", country: "Indonesia" },
  { name: "Sekolah Pelita Harapan", city: "Tangerang", country: "Indonesia" },
  { name: "International School Bangkok", city: "Bangkok", country: "Thailand" },
  { name: "NIST International School", city: "Bangkok", country: "Thailand" },
  { name: "Mahidol Wittayanusorn School", city: "Nakhon Pathom", country: "Thailand" },
  { name: "Vietnam National University High School for the Gifted", city: "Hanoi", country: "Vietnam" },
  { name: "United Nations International School of Hanoi", city: "Hanoi", country: "Vietnam" },
  { name: "Saigon South International School", city: "Ho Chi Minh City", country: "Vietnam" },
  { name: "International School Dhaka", city: "Dhaka", country: "Bangladesh" },
  { name: "Aga Khan Academy Karachi", city: "Karachi", country: "Pakistan" },
  { name: "Karachi Grammar School", city: "Karachi", country: "Pakistan" },
  { name: "Lahore Grammar School", city: "Lahore", country: "Pakistan" },

  // ===== EXPANDED COVERAGE — additional high schools students often attend =====
  // United States — additional top public, magnet, and independent high schools
  { name: "Phillips Exeter Academy", city: "Exeter, NH", country: "United States", type: "Independent" },
  { name: "Phillips Academy Andover", city: "Andover, MA", country: "United States", type: "Independent" },
  { name: "Choate Rosemary Hall", city: "Wallingford, CT", country: "United States", type: "Independent" },
  { name: "Deerfield Academy", city: "Deerfield, MA", country: "United States", type: "Independent" },
  { name: "The Lawrenceville School", city: "Lawrenceville, NJ", country: "United States", type: "Independent" },
  { name: "Hotchkiss School", city: "Lakeville, CT", country: "United States", type: "Independent" },
  { name: "St. Paul's School", city: "Concord, NH", country: "United States", type: "Independent" },
  { name: "Groton School", city: "Groton, MA", country: "United States", type: "Independent" },
  { name: "Milton Academy", city: "Milton, MA", country: "United States", type: "Independent" },
  { name: "Cate School", city: "Carpinteria, CA", country: "United States", type: "Independent" },
  { name: "The Harker School", city: "San Jose, CA", country: "United States", type: "Independent" },
  { name: "Harvard-Westlake School", city: "Los Angeles, CA", country: "United States", type: "Independent" },
  { name: "The Dalton School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "Trinity School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "Horace Mann School", city: "Bronx, NY", country: "United States", type: "Independent" },
  { name: "Collegiate School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "Sidwell Friends School", city: "Washington, DC", country: "United States", type: "Independent" },
  { name: "The Nueva School", city: "Hillsborough, CA", country: "United States", type: "Independent" },
  { name: "Hunter College High School", city: "New York, NY", country: "United States", type: "Public" },
  { name: "Brooklyn Technical High School", city: "Brooklyn, NY", country: "United States", type: "Public" },
  { name: "Staten Island Technical High School", city: "Staten Island, NY", country: "United States", type: "Public" },
  { name: "Queens High School for the Sciences at York College", city: "Jamaica, NY", country: "United States", type: "Public" },
  { name: "High School for Mathematics, Science and Engineering", city: "New York, NY", country: "United States", type: "Public" },
  { name: "Townsend Harris High School", city: "Flushing, NY", country: "United States", type: "Public" },
  { name: "Bard High School Early College Manhattan", city: "New York, NY", country: "United States", type: "Public" },
  { name: "Walter Payton College Prep", city: "Chicago, IL", country: "United States", type: "Public" },
  { name: "Northside College Preparatory High School", city: "Chicago, IL", country: "United States", type: "Public" },
  { name: "Lane Technical College Prep High School", city: "Chicago, IL", country: "United States", type: "Public" },
  { name: "Henry M. Gunn High School", city: "Palo Alto, CA", country: "United States", type: "Public" },
  { name: "Palo Alto High School", city: "Palo Alto, CA", country: "United States", type: "Public" },
  { name: "Lynbrook High School", city: "San Jose, CA", country: "United States", type: "Public" },
  { name: "Saratoga High School", city: "Saratoga, CA", country: "United States", type: "Public" },
  { name: "Cupertino High School", city: "Cupertino, CA", country: "United States", type: "Public" },
  { name: "Liberal Arts and Science Academy", city: "Austin, TX", country: "United States", type: "Public" },
  { name: "School for the Talented and Gifted", city: "Dallas, TX", country: "United States", type: "Public" },

  // United Kingdom — additional independent and grammar schools
  { name: "Westminster School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "St Paul's School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "City of London School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "King's College School Wimbledon", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "University College School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "North London Collegiate School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "St Paul's Girls' School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "Henrietta Barnett School", city: "London", country: "United Kingdom", type: "Grammar" },
  { name: "Queen Elizabeth's School Barnet", city: "London", country: "United Kingdom", type: "Grammar" },
  { name: "The Tiffin Girls' School", city: "Kingston upon Thames", country: "United Kingdom", type: "Grammar" },
  { name: "Sevenoaks School", city: "Sevenoaks", country: "United Kingdom", type: "Independent" },
  { name: "Brighton College", city: "Brighton", country: "United Kingdom", type: "Independent" },
  { name: "Wycombe Abbey", city: "High Wycombe", country: "United Kingdom", type: "Independent" },
  { name: "Cheltenham Ladies' College", city: "Cheltenham", country: "United Kingdom", type: "Independent" },
  { name: "Marlborough College", city: "Marlborough", country: "United Kingdom", type: "Independent" },
  { name: "Charterhouse School", city: "Godalming", country: "United Kingdom", type: "Independent" },
  { name: "Tonbridge School", city: "Tonbridge", country: "United Kingdom", type: "Independent" },

  // Canada
  { name: "Upper Canada College", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "Branksome Hall", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "Havergal College", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "St. George's School", city: "Vancouver, BC", country: "Canada", type: "Independent" },
  { name: "York House School", city: "Vancouver, BC", country: "Canada", type: "Independent" },
  { name: "Lower Canada College", city: "Montreal, QC", country: "Canada", type: "Independent" },
  { name: "Selwyn House School", city: "Montreal, QC", country: "Canada", type: "Independent" },
  { name: "University of Toronto Schools", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "Ridley College", city: "St. Catharines, ON", country: "Canada", type: "Independent" },
  { name: "Appleby College", city: "Oakville, ON", country: "Canada", type: "Independent" },

  // Australia
  { name: "Sydney Grammar School", city: "Sydney, NSW", country: "Australia", type: "Independent" },
  { name: "Scotch College Melbourne", city: "Melbourne, VIC", country: "Australia", type: "Independent" },
  { name: "Melbourne Grammar School", city: "Melbourne, VIC", country: "Australia", type: "Independent" },
  { name: "Sydney Boys High School", city: "Sydney, NSW", country: "Australia", type: "Selective" },
  { name: "James Ruse Agricultural High School", city: "Sydney, NSW", country: "Australia", type: "Selective" },
  { name: "North Sydney Boys High School", city: "Sydney, NSW", country: "Australia", type: "Selective" },
  { name: "Melbourne High School", city: "Melbourne, VIC", country: "Australia", type: "Selective" },
  { name: "Mac.Robertson Girls' High School", city: "Melbourne, VIC", country: "Australia", type: "Selective" },
  { name: "The King's School", city: "Parramatta, NSW", country: "Australia", type: "Independent" },
  { name: "Geelong Grammar School", city: "Corio, VIC", country: "Australia", type: "Independent" },

  // India — additional well-known schools
  { name: "Cathedral and John Connon School", city: "Mumbai", country: "India", type: "Independent" },
  { name: "Bombay Scottish School", city: "Mumbai", country: "India", type: "Independent" },
  { name: "Jamnabai Narsee School", city: "Mumbai", country: "India", type: "Independent" },
  { name: "Vasant Valley School", city: "New Delhi", country: "India", type: "Independent" },
  { name: "Sanskriti School", city: "New Delhi", country: "India", type: "Independent" },
  { name: "Shri Ram School", city: "New Delhi", country: "India", type: "Independent" },
  { name: "Step by Step School", city: "Noida", country: "India", type: "Independent" },
  { name: "Heritage Xperiential Learning School", city: "Gurugram", country: "India", type: "Independent" },
  { name: "Pathways World School", city: "Gurugram", country: "India", type: "International" },
  { name: "Oakridge International School", city: "Bangalore", country: "India", type: "International" },
  { name: "Greenwood High International School", city: "Bangalore", country: "India", type: "International" },
  { name: "Inventure Academy", city: "Bangalore", country: "India", type: "Independent" },
  { name: "Mallya Aditi International School", city: "Bangalore", country: "India", type: "Independent" },
  { name: "Sishya School", city: "Chennai", country: "India", type: "Independent" },
  { name: "American International School Chennai", city: "Chennai", country: "India", type: "International" },
  { name: "La Martiniere for Boys", city: "Kolkata", country: "India", type: "Independent" },
  { name: "Modern High School for Girls", city: "Kolkata", country: "India", type: "Independent" },
  { name: "Hyderabad Public School", city: "Hyderabad", country: "India", type: "Independent" },
  { name: "Indus International School", city: "Hyderabad", country: "India", type: "International" },
  { name: "Mayo College", city: "Ajmer", country: "India", type: "Boarding" },
  { name: "Welham Boys' School", city: "Dehradun", country: "India", type: "Boarding" },

  // Singapore (additional)
  { name: "United World College of South East Asia", city: "Singapore", country: "Singapore", type: "International" },
  { name: "Singapore American School", city: "Singapore", country: "Singapore", type: "International" },
  { name: "Tanglin Trust School", city: "Singapore", country: "Singapore", type: "International" },
  { name: "ACS (Independent)", city: "Singapore", country: "Singapore", type: "Independent" },

  // Hong Kong
  { name: "Diocesan Boys' School", city: "Hong Kong", country: "Hong Kong", type: "Direct Subsidy" },
  { name: "La Salle College", city: "Hong Kong", country: "Hong Kong", type: "Aided" },
  { name: "Chinese International School", city: "Hong Kong", country: "Hong Kong", type: "International" },
  { name: "Hong Kong International School", city: "Hong Kong", country: "Hong Kong", type: "International" },
  { name: "German Swiss International School", city: "Hong Kong", country: "Hong Kong", type: "International" },

  // UAE
  { name: "GEMS Wellington International School", city: "Dubai", country: "UAE", type: "International" },
  { name: "Dubai College", city: "Dubai", country: "UAE", type: "International" },
  { name: "Jumeirah College", city: "Dubai", country: "UAE", type: "International" },
  { name: "Repton School Dubai", city: "Dubai", country: "UAE", type: "International" },
  { name: "Cranleigh Abu Dhabi", city: "Abu Dhabi", country: "UAE", type: "International" },
];

// Function to search schools with autocomplete
export function searchSchools(query: string, limit: number = 10): School[] {
  if (!query || query.length < 2) return [];
  
  const lowerQuery = query.toLowerCase();
  
  return globalSchools
    .filter(school => 
      school.name.toLowerCase().includes(lowerQuery) ||
      school.city.toLowerCase().includes(lowerQuery) ||
      school.country.toLowerCase().includes(lowerQuery)
    )
    .slice(0, limit);
}

  const expandedSchools: School[] = [
  { name: "United World College of South East Asia (Dover)", city: "Singapore", country: "Singapore", type: "International (IB)" },
  { name: "United World College of South East Asia (East)", city: "Singapore", country: "Singapore", type: "International (IB)" },
  { name: "Singapore American School", city: "Singapore", country: "Singapore", type: "International" },
  { name: "Tanglin Trust School", city: "Singapore", country: "Singapore", type: "International (British)" },
  { name: "UWC Atlantic College", city: "St Donat's", country: "United Kingdom", type: "International (IB)" },
  { name: "Sevenoaks School", city: "Sevenoaks", country: "United Kingdom", type: "Independent (IB)" },
  { name: "King's College School Wimbledon", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "Westminster School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "St Paul's School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "Winchester College", city: "Winchester", country: "United Kingdom", type: "Independent" },
  { name: "Eton College", city: "Windsor", country: "United Kingdom", type: "Independent" },
  { name: "Harrow School", city: "London", country: "United Kingdom", type: "Independent" },
  { name: "International School of Geneva (Ecolint)", city: "Geneva", country: "Switzerland", type: "International (IB)" },
  { name: "Institut Le Rosey", city: "Rolle", country: "Switzerland", type: "International (Boarding)" },
  { name: "Lycée Louis-le-Grand", city: "Paris", country: "France", type: "Public Selective" },
  { name: "Lycée Henri-IV", city: "Paris", country: "France", type: "Public Selective" },
  { name: "École Internationale de Genève", city: "Geneva", country: "Switzerland", type: "International (IB)" },
  { name: "International School of Brussels", city: "Brussels", country: "Belgium", type: "International (IB)" },
  { name: "American School of The Hague", city: "Wassenaar", country: "Netherlands", type: "International" },
  { name: "International School of Amsterdam", city: "Amstelveen", country: "Netherlands", type: "International (IB)" },
  { name: "Berlin Brandenburg International School", city: "Kleinmachnow", country: "Germany", type: "International (IB)" },
  { name: "Frankfurt International School", city: "Oberursel", country: "Germany", type: "International (IB)" },
  { name: "Munich International School", city: "Starnberg", country: "Germany", type: "International (IB)" },
  { name: "Saint Stephen's School Rome", city: "Rome", country: "Italy", type: "International (IB)" },
  { name: "International School of Helsinki", city: "Helsinki", country: "Finland", type: "International (IB)" },
  { name: "International School of Stockholm", city: "Stockholm", country: "Sweden", type: "International (IB)" },
  { name: "Copenhagen International School", city: "Copenhagen", country: "Denmark", type: "International (IB)" },

  // ===== EXPANDED — INDIA =====
  { name: "Doon School", city: "Dehradun", country: "India", type: "Boarding" },
  { name: "Mayo College", city: "Ajmer", country: "India", type: "Boarding" },
  { name: "Modern School Barakhamba Road", city: "New Delhi", country: "India", type: "Private" },
  { name: "Sanskriti School", city: "New Delhi", country: "India", type: "Private" },
  { name: "Vasant Valley School", city: "New Delhi", country: "India", type: "Private" },
  { name: "Step by Step School", city: "Noida", country: "India", type: "Private (IB/CBSE)" },
  { name: "Pathways World School", city: "Aravali", country: "India", type: "Boarding (IB)" },
  { name: "Cathedral and John Connon School", city: "Mumbai", country: "India", type: "Private (ICSE)" },
  { name: "Dhirubhai Ambani International School", city: "Mumbai", country: "India", type: "Private (IB/IGCSE)" },
  { name: "Bombay Scottish School", city: "Mumbai", country: "India", type: "Private (ICSE)" },
  { name: "Jamnabai Narsee School", city: "Mumbai", country: "India", type: "Private (CBSE/IGCSE)" },
  { name: "Bishop Cotton Boys' School", city: "Bengaluru", country: "India", type: "Private (ICSE)" },
  { name: "Inventure Academy", city: "Bengaluru", country: "India", type: "Private (IGCSE)" },
  { name: "Greenwood High International School", city: "Bengaluru", country: "India", type: "Private (IB)" },
  { name: "The International School Bangalore (TISB)", city: "Bengaluru", country: "India", type: "International (IB)" },
  { name: "Indus International School", city: "Bengaluru", country: "India", type: "International (IB)" },
  { name: "Loyola School", city: "Chennai", country: "India", type: "Private" },
  { name: "Kodaikanal International School", city: "Kodaikanal", country: "India", type: "International (IB)" },
  { name: "Woodstock School", city: "Mussoorie", country: "India", type: "International (IB)" },
  { name: "Welham Boys' School", city: "Dehradun", country: "India", type: "Boarding" },
  { name: "Welham Girls' School", city: "Dehradun", country: "India", type: "Boarding" },
  { name: "La Martinière for Boys", city: "Kolkata", country: "India", type: "Private (ICSE)" },
  { name: "South Point High School", city: "Kolkata", country: "India", type: "Private" },
  { name: "Hyderabad Public School", city: "Hyderabad", country: "India", type: "Private" },

  // ===== EXPANDED — MIDDLE EAST =====
  { name: "American School of Dubai", city: "Dubai", country: "United Arab Emirates", type: "International" },
  { name: "Dubai American Academy", city: "Dubai", country: "United Arab Emirates", type: "International" },
  { name: "GEMS Wellington International School", city: "Dubai", country: "United Arab Emirates", type: "International (IB)" },
  { name: "Jumeirah College", city: "Dubai", country: "United Arab Emirates", type: "International (British)" },
  { name: "Repton School Dubai", city: "Dubai", country: "United Arab Emirates", type: "International (British)" },
  { name: "American Community School Abu Dhabi", city: "Abu Dhabi", country: "United Arab Emirates", type: "International" },
  { name: "American School of Doha", city: "Doha", country: "Qatar", type: "International" },
  { name: "Doha College", city: "Doha", country: "Qatar", type: "International (British)" },
  { name: "American School of Kuwait", city: "Salmiya", country: "Kuwait", type: "International" },

  // ===== EXPANDED — EAST ASIA =====
  { name: "Beijing No. 4 High School", city: "Beijing", country: "China", type: "Public" },
  { name: "Renmin University Affiliated High School", city: "Beijing", country: "China", type: "Public" },
  { name: "High School Affiliated to Fudan University", city: "Shanghai", country: "China", type: "Public" },
  { name: "Shanghai American School", city: "Shanghai", country: "China", type: "International" },
  { name: "International School of Beijing", city: "Beijing", country: "China", type: "International" },
  { name: "Western Academy of Beijing", city: "Beijing", country: "China", type: "International (IB)" },
  { name: "Hong Kong International School", city: "Hong Kong", country: "Hong Kong", type: "International" },
  { name: "Chinese International School", city: "Hong Kong", country: "Hong Kong", type: "International (IB)" },
  { name: "German Swiss International School", city: "Hong Kong", country: "Hong Kong", type: "International (IB)" },
  { name: "Diocesan Boys' School", city: "Hong Kong", country: "Hong Kong", type: "Private" },
  { name: "Seoul International School", city: "Seoul", country: "South Korea", type: "International" },
  { name: "Korea International School", city: "Seongnam", country: "South Korea", type: "International" },
  { name: "Daewon Foreign Language High School", city: "Seoul", country: "South Korea", type: "Public Selective" },
  { name: "American School in Japan", city: "Tokyo", country: "Japan", type: "International" },
  { name: "Tokyo International School", city: "Tokyo", country: "Japan", type: "International (IB)" },
  { name: "Saint Maur International School", city: "Yokohama", country: "Japan", type: "International (IB)" },

  // ===== EXPANDED — AUSTRALIA / NZ / OCEANIA =====
  { name: "Sydney Grammar School", city: "Sydney", country: "Australia", type: "Independent" },
  { name: "James Ruse Agricultural High School", city: "Sydney", country: "Australia", type: "Public Selective" },
  { name: "North Sydney Boys High School", city: "Sydney", country: "Australia", type: "Public Selective" },
  { name: "Melbourne High School", city: "Melbourne", country: "Australia", type: "Public Selective" },
  { name: "Mac.Robertson Girls' High School", city: "Melbourne", country: "Australia", type: "Public Selective" },
  { name: "Scotch College Melbourne", city: "Melbourne", country: "Australia", type: "Independent" },
  { name: "Brisbane Grammar School", city: "Brisbane", country: "Australia", type: "Independent" },
  { name: "Auckland Grammar School", city: "Auckland", country: "New Zealand", type: "Public" },
  { name: "King's College Auckland", city: "Auckland", country: "New Zealand", type: "Independent" },

  // ===== EXPANDED — LATIN AMERICA & AFRICA =====
  { name: "Colegio Anglo Mexicano de Coyoacán", city: "Mexico City", country: "Mexico", type: "Private (IB)" },
  { name: "American School Foundation of Mexico City", city: "Mexico City", country: "Mexico", type: "International" },
  { name: "Colegio Nogales", city: "Santiago", country: "Chile", type: "Private (IB)" },
  { name: "The Grange School", city: "Santiago", country: "Chile", type: "International (British)" },
  { name: "Colegio San George", city: "Buenos Aires", country: "Argentina", type: "Private" },
  { name: "Saint George's College North", city: "Buenos Aires", country: "Argentina", type: "Private (IB)" },
  { name: "Graded - The American School of São Paulo", city: "São Paulo", country: "Brazil", type: "International" },
  { name: "St. Paul's School São Paulo", city: "São Paulo", country: "Brazil", type: "International (British)" },
  { name: "American School of Rio de Janeiro", city: "Rio de Janeiro", country: "Brazil", type: "International" },
  { name: "African Leadership Academy", city: "Johannesburg", country: "South Africa", type: "International (IB)" },
  { name: "St John's College Johannesburg", city: "Johannesburg", country: "South Africa", type: "Private" },
  { name: "Hilton College", city: "Hilton", country: "South Africa", type: "Private (Boarding)" },
  { name: "Bishops Diocesan College", city: "Cape Town", country: "South Africa", type: "Private" },
  { name: "Aga Khan Academy Mombasa", city: "Mombasa", country: "Kenya", type: "International (IB)" },
  { name: "International School of Kenya", city: "Nairobi", country: "Kenya", type: "International (IB)" },
  { name: "American International School of Lagos", city: "Lagos", country: "Nigeria", type: "International" },

  // ===== EXPANDED — UNITED STATES (additional magnets & top privates) =====
  { name: "Hunter College High School", city: "New York, NY", country: "United States", type: "Public Selective" },
  { name: "Brooklyn Technical High School", city: "Brooklyn, NY", country: "United States", type: "Public Selective" },
  { name: "Staten Island Technical High School", city: "Staten Island, NY", country: "United States", type: "Public Selective" },
  { name: "Townsend Harris High School", city: "Queens, NY", country: "United States", type: "Public Selective" },
  { name: "Phillips Exeter Academy", city: "Exeter, NH", country: "United States", type: "Boarding" },
  { name: "Phillips Academy Andover", city: "Andover, MA", country: "United States", type: "Boarding" },
  { name: "Choate Rosemary Hall", city: "Wallingford, CT", country: "United States", type: "Boarding" },
  { name: "Deerfield Academy", city: "Deerfield, MA", country: "United States", type: "Boarding" },
  { name: "The Lawrenceville School", city: "Lawrenceville, NJ", country: "United States", type: "Boarding" },
  { name: "Hotchkiss School", city: "Lakeville, CT", country: "United States", type: "Boarding" },
  { name: "Groton School", city: "Groton, MA", country: "United States", type: "Boarding" },
  { name: "Milton Academy", city: "Milton, MA", country: "United States", type: "Boarding" },
  { name: "St. Paul's School", city: "Concord, NH", country: "United States", type: "Boarding" },
  { name: "Trinity School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "Horace Mann School", city: "Bronx, NY", country: "United States", type: "Independent" },
  { name: "Dalton School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "Collegiate School", city: "New York, NY", country: "United States", type: "Independent" },
  { name: "The Harker School", city: "San Jose, CA", country: "United States", type: "Independent" },
  { name: "Harvard-Westlake School", city: "Los Angeles, CA", country: "United States", type: "Independent" },
  { name: "Sidwell Friends School", city: "Washington, DC", country: "United States", type: "Independent" },

  // ===== EXPANDED — CANADA =====
  { name: "Upper Canada College", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "University of Toronto Schools", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "Branksome Hall", city: "Toronto, ON", country: "Canada", type: "Independent (IB)" },
  { name: "Havergal College", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "Crescent School", city: "Toronto, ON", country: "Canada", type: "Independent" },
  { name: "St. George's School", city: "Vancouver, BC", country: "Canada", type: "Independent" },
  { name: "York House School", city: "Vancouver, BC", country: "Canada", type: "Independent" },
  { name: "Lower Canada College", city: "Montreal, QC", country: "Canada", type: "Independent" },
];

// Merge base + expanded sets, deduped by name+country
export const globalSchools: School[] = (() => {
  const seen = new Set<string>();
  const out: School[] = [];
  for (const s of [...baseSchools, ...expandedSchools]) {
    const key = `${s.name}|${s.country}`.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(s);
  }
  return out;
})();

// (helpers below) ////////////////////////////////////////////////////////

export function getCountries(): string[] {
  const countries = new Set(globalSchools.map(s => s.country));
  return Array.from(countries).sort();
}

// Format school display name
export function formatSchoolDisplay(school: School): string {
  return `${school.name} - ${school.city}, ${school.country}`;
}
