/**
 * Additional practice-bank questions, written in the digital SAT's style.
 *
 * These sit alongside the original bank in `questions.ts` and are served by
 * the Question Bank, practice sets and the randomly assembled exams. They are
 * weighted toward what the original bank lacked: questions built on tables,
 * graphs and diagrams, and harder items at the top of each skill.
 */

import { STEM, goal, notes, q, texts, type QSpec } from "./author";

const build = (specs: QSpec[]) => specs.map((s) => q(s));

/* ------------------------------------------------------------------ */
/* Math                                                                */
/* ------------------------------------------------------------------ */

const MATH: QSpec[] = [
  {
    id: "b-m-01",
    skill: "linear-eq-1var",
    d: "medium",
    p: "If (3/4)x - 2 = (1/2)x + 5, what is the value of x?",
    a: "28",
    e: "Subtract (1/2)x from both sides and add 2: (1/4)x = 7, so x = 28.",
  },
  {
    id: "b-m-02",
    skill: "linear-eq-1var",
    d: "hard",
    p: "In the equation k(x + 3) = 4x + 12 - 2x, k is a constant. For what value of k does the equation have no solution?",
    c: ["2", "4", "6", "-2"],
    a: "A",
    e: "The right side is 2x + 12. With k = 2 the left side is 2x + 6, and 2x + 6 = 2x + 12 is never true. For any other k there is exactly one solution.",
  },
  {
    id: "b-m-03",
    skill: "linear-eq-2var",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Rice (kilograms)",
      yLabel: "Beans (kilograms)",
      x: [0, 9, 1],
      y: [0, 7, 1],
      series: [{ type: "fn", f: (x) => 6 - 0.75 * x, domain: [0, 8] }],
      alt: "A line from (0, 6) down to (8, 0).",
    },
    p: "The graph shows the possible combinations of rice, x, and beans, y, in kilograms, that a shopper can buy for exactly $24. If the shopper buys 4 kilograms of rice, how many kilograms of beans can the shopper buy?",
    c: ["3", "4", "2", "6"],
    a: "B",
    e: "Reading the line at x = 4 gives y = 3. (The line is 3x + 4y = 24: 12 + 4y = 24, so y = 3.)",
  },
  {
    id: "b-m-04",
    skill: "linear-eq-2var",
    d: "hard",
    p: "Apples cost $1.50 per pound and pears cost $2.25 per pound. A shopper spends exactly $18.00 and buys 2 more pounds of pears than of apples. How many pounds of apples does the shopper buy?",
    a: "3.6",
    alt: ["18/5"],
    e: "With x pounds of apples, 1.50x + 2.25(x + 2) = 18. So 3.75x + 4.50 = 18, 3.75x = 13.50, and x = 3.6.",
  },
  {
    id: "b-m-05",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "table",
      head: ["x", "-2", "1", "4"],
      rows: [["f(x)", "11", "5", "-1"]],
      rowHeaders: true,
    },
    p: "The table shows three values of x and their corresponding values of f(x), where f is a linear function. Which equation defines f?",
    c: ["f(x) = -2x + 7", "f(x) = 2x + 7", "f(x) = -2x + 5", "f(x) = -6x + 11"],
    a: "C",
    e: "The slope is (5 - 11)/(1 - (-2)) = -2. Using f(1) = 5: 5 = -2 + b, so b = 7 and f(x) = -2x + 7.",
  },
  {
    id: "b-m-06",
    skill: "linear-functions",
    d: "hard",
    p: "The linear function f satisfies f(2) = 11 and f(-1) = 2. What is the value of f(5)?",
    a: "20",
    e: "The slope is (11 - 2)/(2 - (-1)) = 3, so f(x) = 3x + b and 11 = 6 + b gives b = 5. Then f(5) = 20.",
  },
  {
    id: "b-m-07",
    skill: "systems-linear",
    d: "medium",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-5, 4, 1],
      y: [-3, 6, 1],
      series: [{ type: "fn", f: (x) => 2 * x + 4 }, { type: "fn", f: (x) => -x + 1, dashed: true }],
      alt: "Two lines crossing at (negative 1, 2).",
    },
    p: "The graphs of y = 2x + 4 and y = -x + 1 are shown in the xy-plane. What is the solution (x, y) to the system of the two equations?",
    c: ["(-1, 2)", "(2, -1)", "(0, 4)", "(1, 0)"],
    a: "D",
    e: "The lines cross at (-1, 2). Check: 2(-1) + 4 = 2 and -(-1) + 1 = 2.",
  },
  {
    id: "b-m-08",
    skill: "systems-linear",
    d: "hard",
    p: "A school sold 150 tickets to a play. Adult tickets cost $12 and student tickets cost $7, and ticket sales totaled $1,450. How many student tickets were sold?",
    a: "70",
    e: "With a adult tickets, 12a + 7(150 - a) = 1,450, so 5a = 400 and a = 80. Student tickets: 150 - 80 = 70.",
  },
  {
    id: "b-m-09",
    skill: "linear-inequalities",
    d: "hard",
    s: "y < -2x + 5\ny > x - 4",
    p: "Which point (x, y) is a solution to the given system of inequalities?",
    c: ["(1, 1)", "(3, 0)", "(0, 6)", "(4, -1)"],
    a: "B",
    e: "For (1, 1): 1 < 3 and 1 > -3, both true. (3, 0) fails 0 < -1, (0, 6) fails 6 < 5, and (4, -1) fails -1 < -3.",
  },
  {
    id: "b-m-10",
    skill: "linear-inequalities",
    d: "medium",
    p: "A student wants an average of at least 90 on four tests. The student's scores on the first three tests are 86, 91, and 88. What is the minimum score the student needs on the fourth test?",
    a: "95",
    e: "The four scores must total at least 4 {times} 90 = 360. The first three total 265, so the fourth must be at least 95.",
  },
  {
    id: "b-m-11",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Time (hours)",
      yLabel: "Distance from campsite (km)",
      x: [0, 7, 1],
      y: [0, 14, 2],
      series: [{ type: "fn", f: (x) => 12 - 2 * x, domain: [0, 6] }],
      alt: "A line falling from (0, 12) to (6, 0).",
    },
    p: "The graph shows a hiker's distance from a campsite t hours after the hiker starts walking toward it. What is the best interpretation of the point where the graph meets the horizontal axis?",
    c: [
      "The hiker reaches the campsite 6 hours after starting.",
      "The hiker starts 6 kilometers from the campsite.",
      "The hiker walks 6 kilometers per hour.",
      "The hiker rests for 6 hours.",
    ],
    a: "A",
    e: "At that point the distance is 0 and the time is 6: the hiker arrives at the campsite after 6 hours. The hiker starts 12 kilometers away and walks 2 kilometers per hour.",
  },
  {
    id: "b-m-12",
    skill: "quadratics",
    d: "hard",
    p: "The equation x^2 - 10x + c = 0, where c is a constant, has two distinct real solutions. Which of the following could be the value of c?",
    c: ["24", "25", "26", "30"],
    a: "C",
    e: "Two distinct real solutions need a positive discriminant: 100 - 4c > 0, so c < 25. Only 24 qualifies. (c = 25 gives exactly one solution.)",
  },
  {
    id: "b-m-13",
    skill: "quadratics",
    d: "medium",
    p: "What is the positive solution to the equation (x + 2)^2 = 3x + 10?",
    a: "2",
    e: "Expand: x^2 + 4x + 4 = 3x + 10, so x^2 + x - 6 = 0 and (x + 3)(x - 2) = 0. The positive solution is 2.",
  },
  {
    id: "b-m-14",
    skill: "nonlinear-functions",
    d: "hard",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-3, 5, 1],
      y: [-5, 5, 1],
      series: [{ type: "fn", f: (x) => (x - 1) ** 2 - 4 }],
      alt: "An upward-opening parabola with vertex at (1, negative 4) crossing the x-axis at negative 1 and 3.",
    },
    p: "The graph of y = f(x) is shown. For how many values of x does f(x) = -3?",
    c: ["2", "0", "1", "3"],
    a: "A",
    e: "The horizontal line y = -3 lies just above the vertex at y = -4, so it crosses the parabola twice. (Algebraically, (x - 1)^2 = 1 gives x = 0 or x = 2.)",
  },
  {
    id: "b-m-15",
    skill: "nonlinear-functions",
    d: "hard",
    p: "The function f is defined by f(x) = (x - 3)(x + 1). The function g is defined by g(x) = f(x) + k, where k is a constant. If the graph of y = g(x) has exactly one x-intercept, what is the value of k?",
    a: "4",
    e: "f has its minimum midway between its zeros, at x = 1, where f(1) = (-2)(2) = -4. Shifting up by 4 lifts the vertex to the x-axis, giving exactly one x-intercept.",
  },
  {
    id: "b-m-16",
    skill: "exponential",
    d: "medium",
    fig: {
      kind: "table",
      head: ["x", "1", "2", "3"],
      rows: [["g(x)", "12", "36", "108"]],
      rowHeaders: true,
    },
    p: "The table shows three values of the exponential function g. Which equation could define g?",
    c: ["g(x) = 4(3)^{x}", "g(x) = 12(3)^{x}", "g(x) = 3(4)^{x}", "g(x) = 12x^3"],
    a: "D",
    e: "Each value is 3 times the previous one, so g(x) = a(3)^{x}. From g(1) = 12, 3a = 12 and a = 4. (12(3)^{x} would give g(1) = 36.)",
  },
  {
    id: "b-m-17",
    skill: "exponential",
    d: "hard",
    p: "A town's population of 3,000 increases by 50% every 8 years. Which function gives the population P(t) after t years?",
    c: ["P(t) = 3,000(1.5)^{t/8}", "P(t) = 3,000(1.5)^{8t}", "P(t) = 3,000(0.5)^{t/8}", "P(t) = 3,000(1.05)^{t}"],
    a: "A",
    e: "The population is multiplied by 1.5 once for every 8 years, which is t/8 times in t years.",
  },
  {
    id: "b-m-18",
    skill: "exponential",
    d: "hard",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [0, 5, 1],
      y: [0, 70, 10],
      series: [{ type: "fn", f: (x) => 64 * 0.5 ** x }],
      alt: "A decreasing curve passing through (0, 64), (1, 32), (2, 16), and (3, 8).",
    },
    p: "The graph of y = a(b)^{x} is shown, where a and b are positive constants. The graph passes through (0, 64) and (2, 16). What is the value of b?",
    c: ["1/2", "1/4", "2", "16"],
    a: "B",
    e: "At x = 0, a = 64. Then 64b^2 = 16, so b^2 = 1/4 and b = 1/2 (b is positive).",
  },
  {
    id: "b-m-19",
    skill: "equivalent-expressions",
    d: "hard",
    p: "The expression 2x^2 + 7x - 15 is equivalent to (2x + a)(x + b), where a and b are constants. What is the value of a + b?",
    a: "2",
    e: "2x^2 + 7x - 15 = (2x - 3)(x + 5), so a = -3 and b = 5, and a + b = 2.",
  },
  {
    id: "b-m-20",
    skill: "equivalent-expressions",
    d: "medium",
    p: "Which expression is equivalent to 1/(x + 2) + 3/(x - 1), where x > 1?",
    c: ["(4x + 5)/((x + 2)(x - 1))", "4/((x + 2)(x - 1))", "4/(2x + 1)", "(4x + 7)/((x + 2)(x - 1))"],
    a: "C",
    e: "Over the common denominator (x + 2)(x - 1), the numerator is (x - 1) + 3(x + 2) = 4x + 5.",
  },
  {
    id: "b-m-21",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The function h is defined by h(x) = x^2 - 8x + 20. Which statement about h is true?",
    c: [
      "The minimum value of h(x) is 4, which occurs at x = 4.",
      "The minimum value of h(x) is 20, which occurs at x = 0.",
      "The minimum value of h(x) is 4, which occurs at x = -4.",
      "The minimum value of h(x) is -4, which occurs at x = 4.",
    ],
    a: "D",
    e: "Completing the square gives h(x) = (x - 4)^2 + 4, so the minimum value is 4, at x = 4.",
  },
  {
    id: "b-m-22",
    skill: "quadratics",
    d: "hard",
    p: "In the xy-plane, the graphs of y = x^2 and y = 2x + 8 intersect at the points (a, b) and (c, d). What is the value of b + d?",
    a: "20",
    e: "Set x^2 = 2x + 8: x^2 - 2x - 8 = 0, so x = 4 or x = -2. The y-values are 16 and 4, and their sum is 20.",
  },
  {
    id: "b-m-23",
    skill: "exponential",
    d: "medium",
    p: "The balance of an account doubles every 9 years. The balance is $5,000 now. How many years from now will the balance be $40,000?",
    c: ["27", "36", "24", "72"],
    a: "B",
    e: "$40,000 is 8 times $5,000, which is three doublings (2 {times} 2 {times} 2). Three doublings take 3 {times} 9 = 27 years.",
  },
  {
    id: "b-m-24",
    skill: "ratios-rates",
    d: "medium",
    p: "A car uses 0.08 liter of fuel per kilometer, and fuel costs $1.60 per liter. What is the cost of the fuel the car uses to travel 350 kilometers?",
    c: ["$44.80", "$28.00", "$560.00", "$4.48"],
    a: "A",
    e: "The car uses 0.08 {times} 350 = 28 liters, which cost 28 {times} $1.60 = $44.80.",
  },
  {
    id: "b-m-25",
    skill: "ratios-rates",
    d: "hard",
    p: "A metal block in the shape of a rectangular prism measures 5 centimeters by 4 centimeters by 3 centimeters and has a mass of 810 grams. What is the density of the metal, in grams per cubic centimeter?",
    a: "13.5",
    alt: ["27/2"],
    e: "The volume is 5 {times} 4 {times} 3 = 60 cubic centimeters, so the density is 810/60 = 13.5 grams per cubic centimeter.",
  },
  {
    id: "b-m-26",
    skill: "percentages",
    d: "hard",
    p: "The price of a stock rose by 40% in one year and then fell by 30% the next year. How did the price at the end of the two years compare with the price at the start?",
    c: [
      "It had decreased by 2%.",
      "It had increased by 10%.",
      "It was unchanged.",
      "It had decreased by 10%.",
    ],
    a: "A",
    e: "Multiply the factors: 1.40 {times} 0.70 = 0.98, so the final price is 98% of the original, a 2% decrease. Adding the percents (+40 - 30 = +10) is the trap.",
  },
  {
    id: "b-m-27",
    skill: "percentages",
    d: "easy",
    p: "If p% of 80 is 28, what is the value of p?",
    a: "35",
    e: "(p/100)(80) = 28, so p = 2,800/80 = 35.",
  },
  {
    id: "b-m-28",
    skill: "data-distributions",
    d: "hard",
    fig: {
      kind: "bar",
      title: "Number of Siblings of Students in a Club",
      xLabel: "Number of siblings",
      yLabel: "Number of students",
      categories: ["0", "1", "2", "3", "4", "5"],
      series: [{ name: "Students", values: [3, 8, 5, 2, 1, 1] }],
      y: [0, 10, 2],
    },
    p: "The bar graph shows the number of siblings of each of the 20 students in a club. Which statement about the data is true?",
    c: [
      "The mean is greater than the median.",
      "The median is greater than the mean.",
      "The mean and the median are equal.",
      "The mode is greater than the median.",
    ],
    a: "C",
    e: "The 10th and 11th values are both 1, so the median is 1. The mean is (0 + 8 + 10 + 6 + 4 + 5)/20 = 33/20 = 1.65, which is greater. The long right tail pulls the mean up.",
  },
  {
    id: "b-m-29",
    skill: "data-distributions",
    d: "medium",
    p: "The six values 4, 8, 8, x, 15, and 20 are listed in increasing order. If the median of the values is 10, what is the value of x?",
    a: "12",
    e: "With six values, the median is the mean of the 3rd and 4th: (8 + x)/2 = 10, so x = 12.",
  },
  {
    id: "b-m-30",
    skill: "probability",
    d: "medium",
    fig: {
      kind: "table",
      head: ["", "In a club", "Not in a club", "Total"],
      rows: [
        ["Grade 11", "24", "36", "60"],
        ["Grade 12", "30", "20", "50"],
        ["Total", "54", "56", "110"],
      ],
      rowHeaders: true,
    },
    p: "The table shows how many students in grades 11 and 12 at a school belong to at least one club. If a student who is in a club is selected at random, what is the probability that the student is in grade 12?",
    c: ["5/9", "3/5", "3/11", "27/55"],
    a: "B",
    e: "Of the 54 students in a club, 30 are in grade 12, so the probability is 30/54 = 5/9. (3/5 is the share of grade 12 students who are in a club.)",
  },
  {
    id: "b-m-31",
    skill: "probability",
    d: "hard",
    p: "An integer from 1 to 30, inclusive, is chosen at random. What is the probability that it is a multiple of 3 or a multiple of 5?",
    c: ["7/15", "8/15", "1/2", "2/5"],
    a: "A",
    e: "There are 10 multiples of 3 and 6 multiples of 5, but 15 and 30 are counted twice, leaving 10 + 6 - 2 = 14. The probability is 14/30 = 7/15.",
  },
  {
    id: "b-m-32",
    skill: "inference",
    d: "medium",
    p: "A researcher randomly selected 80 members of a high school's chess club and asked how many hours they practice each week. To which population can the results of the survey most appropriately be generalized?",
    c: [
      "All members of that high school's chess club",
      "All students at that high school",
      "All high school students in the country",
      "All chess players",
    ],
    a: "C",
    e: "A random sample represents the group it was drawn from, which is the club's members. It says nothing reliable about students outside the club.",
  },
  {
    id: "b-m-33",
    skill: "inference",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Years of experience",
      yLabel: "Hourly wage (dollars)",
      x: [0, 12, 1],
      y: [0, 60, 10],
      labelEvery: 2,
      series: [
        { type: "points", pts: [[1, 19], [2, 20.5], [3, 25.4], [4, 27], [5, 30.8], [6, 33], [7, 37.1], [8, 40], [9, 43.5], [10, 46.2], [11, 49]] },
        { type: "fn", f: (x) => 3.2 * x + 15, domain: [0, 12] },
      ],
      alt: "A scatterplot of hourly wage rising with years of experience, with a line of best fit.",
    },
    p: "The scatterplot shows years of experience, x, and hourly wage, y, for 11 employees at a company, along with the line of best fit y = 3.2x + 15. What is the best interpretation of 15 in this context?",
    c: [
      "The predicted hourly wage of an employee with no experience is $15.",
      "Each additional year of experience increases the predicted hourly wage by $15.",
      "The highest hourly wage at the company is $15.",
      "Employees gain 15 years of experience for every $3.20 increase in wage.",
    ],
    a: "A",
    e: "15 is the y-intercept: the predicted wage when x = 0. The per-year increase is the slope, 3.2.",
  },
  {
    id: "b-m-34",
    skill: "ratios-rates",
    d: "hard",
    p: "A cheetah can run at a speed of 112 kilometers per hour. Which of the following is closest to this speed in meters per second?",
    c: ["31", "112", "1,867", "3.1"],
    a: "A",
    e: "112 kilometers is 112,000 meters, and an hour is 3,600 seconds: 112,000/3,600 is about 31 meters per second.",
  },
  {
    id: "b-m-35",
    skill: "area-volume",
    d: "hard",
    p: "A right circular cylinder has a volume of 72{pi}. A second cylinder has the same height and twice the radius. What is the volume of the second cylinder?",
    c: ["288{pi}", "144{pi}", "216{pi}", "576{pi}"],
    a: "C",
    e: "Volume is {pi}r^2h, so doubling the radius multiplies the volume by 2^2 = 4: 4 {times} 72{pi} = 288{pi}.",
  },
  {
    id: "b-m-36",
    skill: "area-volume",
    d: "hard",
    p: "A sphere has a volume of 36{pi} cubic inches. What is the radius of the sphere, in inches?",
    a: "3",
    e: "(4/3){pi}r^3 = 36{pi}, so r^3 = 27 and r = 3.",
  },
  {
    id: "b-m-37",
    skill: "lines-angles-triangles",
    d: "hard",
    fig: {
      kind: "diagram",
      w: 270,
      h: 160,
      items: [
        { t: "poly", pts: [[40, 150], [220, 150], [110, 30]] },
        { t: "line", a: [220, 150], b: [270, 150] },
        { t: "text", at: [244, 136], s: "130{deg}" },
        { t: "text", at: [88, 138], s: "(2x + 10){deg}" },
        { t: "text", at: [112, 62], s: "3x{deg}" },
      ],
      note: "Note: Figure not drawn to scale.",
      alt: "A triangle with one side extended. The exterior angle is 130 degrees; the two interior angles not next to it are (2x + 10) degrees and 3x degrees.",
    },
    p: "In the figure, one side of a triangle is extended, forming an exterior angle of 130{deg}. What is the value of x?",
    a: "24",
    e: "An exterior angle equals the sum of the two interior angles not adjacent to it: (2x + 10) + 3x = 130, so 5x = 120 and x = 24.",
  },
  {
    id: "b-m-38",
    skill: "lines-angles-triangles",
    d: "medium",
    p: "At a certain time of day, a person who is 6 feet tall casts a shadow 4 feet long, and a nearby tree casts a shadow 30 feet long. How tall is the tree, in feet?",
    c: ["45", "20", "36", "180"],
    a: "A",
    e: "The sun's rays make similar triangles, so height/shadow is the same for both: 6/4 = h/30, and h = 45.",
  },
  {
    id: "b-m-39",
    skill: "right-triangles-trig",
    d: "hard",
    p: "In triangle PQR, angle Q is a right angle, angle P measures 30{deg}, and PR = 20. What is the length of side QR?",
    c: ["10", "10{sqrt}3", "20{sqrt}3", "5"],
    a: "A",
    e: "In a 30-60-90 triangle, the side opposite the 30-degree angle is half the hypotenuse. QR is opposite angle P, so QR = 20/2 = 10.",
  },
  {
    id: "b-m-40",
    skill: "right-triangles-trig",
    d: "hard",
    p: "In a right triangle, one acute angle measures x{deg}, and cos(x{deg}) = 8/17. What is the value of tan(x{deg})?",
    a: "15/8",
    alt: ["1.875"],
    e: "Take the adjacent side as 8 and the hypotenuse as 17. The opposite side is {sqrt}(17^2 - 8^2) = 15, so tan x = 15/8.",
  },
  {
    id: "b-m-41",
    skill: "circles",
    d: "hard",
    fig: {
      kind: "diagram",
      w: 200,
      h: 200,
      items: [
        { t: "circle", c: [100, 100], r: 80 },
        { t: "line", a: [52, 164], b: [148, 164] },
        { t: "line", a: [100, 100], b: [100, 164], dashed: true },
        { t: "right", at: [100, 164], a: [100, 100], b: [148, 164] },
        { t: "dot", at: [100, 100] },
        { t: "text", at: [90, 94], s: "O" },
        { t: "text", at: [42, 172], s: "A" },
        { t: "text", at: [158, 172], s: "B" },
      ],
      alt: "A circle with center O and a chord AB, with a dashed segment from O perpendicular to AB.",
    },
    p: "In the circle shown, the center is O, the radius is 10, and chord AB has length 12. What is the distance from O to chord AB?",
    a: "8",
    e: "The perpendicular from the center bisects the chord, making a right triangle with hypotenuse 10 (a radius) and one leg 6 (half the chord). The other leg is {sqrt}(100 - 36) = 8.",
  },
  {
    id: "b-m-42",
    skill: "circles",
    d: "medium",
    p: "A circle in the xy-plane has the equation (x - 2)^2 + (y + 1)^2 = 25. Which of the following points lies on the circle?",
    c: ["(5, 3)", "(2, 5)", "(5, -4)", "(6, 1)"],
    a: "C",
    e: "For (5, 3): (5 - 2)^2 + (3 + 1)^2 = 9 + 16 = 25. The other points give 36, 18, and 20.",
  },
  {
    id: "b-m-43",
    skill: "area-volume",
    d: "medium",
    p: "A box with a square base has a height of 10 inches and a volume of 360 cubic inches. What is the length, in inches, of one side of the base?",
    c: ["6", "36", "3.6", "18"],
    a: "D",
    e: "s^2 {times} 10 = 360, so s^2 = 36 and s = 6.",
  },
  {
    id: "b-m-44",
    skill: "circles",
    d: "medium",
    p: "An angle measures 7{pi}/6 radians. What is the measure of the angle in degrees?",
    c: ["210", "105", "150", "240"],
    a: "B",
    e: "{pi} radians is 180 degrees, so 7{pi}/6 radians is 7 {times} 180/6 = 210 degrees.",
  },
];

/* ------------------------------------------------------------------ */
/* Reading and Writing                                                 */
/* ------------------------------------------------------------------ */

const RW: QSpec[] = [
  {
    id: "b-r-01",
    skill: "words-in-context",
    d: "hard",
    s: "The committee's praise for the proposal was ______: members commended its goals but warned that its budget was unrealistic and its timeline too short.",
    p: STEM.wic,
    c: ["qualified", "unreserved", "perfunctory", "sarcastic"],
    a: "C",
    e: "Praise combined with warnings is limited, or qualified. 'Unreserved' would mean the praise had no reservations, which the warnings contradict.",
  },
  {
    id: "b-r-02",
    skill: "words-in-context",
    d: "hard",
    s: "Because the medieval poem survives only in a few damaged copies, scholars' reconstruction of its original text is necessarily ______.",
    p: STEM.wic,
    c: ["tentative", "definitive", "redundant", "lavish"],
    a: "A",
    e: "Working from few, damaged copies means any reconstruction is uncertain and open to revision: tentative. 'Definitive' is the opposite.",
  },
  {
    id: "b-r-03",
    skill: "words-in-context",
    d: "medium",
    s: "The ______ of rainfall in the region--some years bring floods while others bring drought--makes long-term planning difficult for farmers.",
    p: STEM.wic,
    c: ["variability", "abundance", "scarcity", "regularity"],
    a: "B",
    e: "Floods some years and drought in others describe unpredictable change: variability. 'Regularity' is the opposite, and 'abundance' and 'scarcity' each describe only one extreme.",
  },
  {
    id: "b-r-04",
    skill: "words-in-context",
    d: "hard",
    s: "Although the two species of frog are nearly ______ in appearance, their calls differ so markedly that females of one species never respond to males of the other.",
    p: STEM.wic,
    c: ["indistinguishable", "incompatible", "unremarkable", "ephemeral"],
    a: "D",
    e: "'Although' sets their appearance against their very different calls, so the frogs must look almost the same: indistinguishable.",
  },
  {
    id: "b-r-05",
    skill: "words-in-context",
    d: "medium",
    s: "The novelist's portrayal of the town is ______: she depicts its residents' generosity and warmth alongside their pettiness and suspicion of outsiders.",
    p: STEM.wic,
    c: ["nuanced", "idealized", "hostile", "superficial"],
    a: "A",
    e: "Showing virtues and flaws together is a portrayal with subtle shades: nuanced. 'Idealized' would show only the good, 'hostile' only the bad.",
  },
  {
    id: "b-r-06",
    skill: "words-in-context",
    d: "hard",
    s: "Critics who dismiss the film as merely ______ overlook its serious engagement with questions of memory and loss, which lie beneath its comic surface.",
    p: STEM.wic,
    c: ["frivolous", "somber", "derivative", "lengthy"],
    a: "C",
    e: "The critics' view is contrasted with the film's seriousness beneath a comic surface, so they must see it as lacking seriousness: frivolous. 'Somber' contradicts 'comic.'",
  },
  {
    id: "b-r-07",
    skill: "text-structure",
    d: "hard",
    s: "The following text is from a novel.\n\nThe Ashford house stood at the end of a long gravel drive, its three stories of red brick visible from the road. [u]It had been built to impress, and it still did, though no longer in the way its builders had intended.[/u] Ivy had swallowed the east wing, half the windows were boarded, and the fountain in the forecourt held nothing but dead leaves.",
    p: STEM.underlined,
    c: [
      "It suggests that the house's power to impress has changed in character, preparing for the description of its decay that follows.",
      "It explains why the house was originally built.",
      "It describes the people who currently live in the house.",
      "It contradicts the description of the house's size in the first sentence.",
    ],
    a: "B",
    e: "Saying the house still impresses, but not as intended, hints at something other than grandeur, and the next sentence reveals it: ruin. The sentence gives no builders' motives in detail and mentions no residents.",
  },
  {
    id: "b-r-08",
    skill: "text-structure",
    d: "medium",
    s: "Many people assume that the Sahara has always been a desert. Yet rock paintings found deep in the Sahara depict giraffes, hippopotamuses, and herds of cattle, and sediment cores show that between about 11,000 and 5,000 years ago much of the region was covered by grassland and lakes. This 'Green Sahara' period ended as gradual shifts in Earth's orbit weakened the monsoon rains.",
    p: STEM.purpose,
    c: [
      "To challenge a common assumption about the Sahara by describing evidence of an earlier, wetter period and how it ended",
      "To argue that the Sahara will soon return to being grassland",
      "To explain how rock paintings were made in ancient North Africa",
      "To describe the animals that live in the Sahara today",
    ],
    a: "D",
    e: "The text opens with an assumption, presents paintings and sediment evidence against it, and explains the period's end. It makes no prediction and describes past, not present, wildlife.",
  },
  {
    id: "b-r-09",
    skill: "text-structure",
    d: "hard",
    s: "Some historians portray medieval craft guilds as monopolies that kept prices high by limiting who could practice a trade. Others emphasize the guilds' role in training apprentices and enforcing standards of quality. Historian Lena Vogt argues that both accounts are accurate but describe different stages: guilds tended to promote quality when they were young and to restrict competition as they aged.",
    p: STEM.structure,
    c: [
      "It presents two contrasting views of a subject and then describes a scholar's argument that each view captures part of the truth.",
      "It describes a historical institution and then explains why it disappeared.",
      "It presents a widely accepted view and then offers evidence that it is false.",
      "It compares medieval guilds with modern labor unions.",
    ],
    a: "A",
    e: "Two opposing portrayals are followed by Vogt's claim that each is right about a different stage. Neither view is declared false, and no modern comparison appears.",
  },
  {
    id: "b-r-10",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Some researchers argue that dogs understand human pointing gestures because thousands of years of domestication selected for that skill.",
      "Researcher Ana Lindgren found that wolves raised by people from birth could follow pointing gestures nearly as well as pet dogs, while dogs raised with little human contact struggled to do so.",
    ),
    p: "Based on the texts, how would Lindgren (Text 2) most likely respond to the researchers' argument in Text 1?",
    c: [
      "By suggesting that the ability may depend more on an animal's experience with people than on domestication",
      "By agreeing that domestication fully explains dogs' ability to follow pointing",
      "By arguing that wolves are generally more intelligent than dogs",
      "By claiming that no animals other than dogs can follow pointing gestures",
    ],
    a: "C",
    e: "Wolves with human upbringing succeed and dogs without it struggle, which points to experience rather than domestication. Wolves' success contradicts the last choice.",
  },
  {
    id: "b-r-11",
    skill: "cross-text",
    d: "medium",
    s: texts(
      "Architect Nils Brandt argues that cities should replace surface parking lots with housing, since parking consumes valuable land near transit stations.",
      "Urban economist Priya Das agrees that surface lots are often an inefficient use of land. But she cautions that removing them all at once could hurt small businesses that depend on customers who drive, and she recommends a gradual transition.",
    ),
    p: "Based on the texts, how would Das (Text 2) most likely respond to Brandt's argument in Text 1?",
    c: [
      "By accepting its reasoning about land use but urging that the change be made gradually",
      "By rejecting the idea that parking lots use land inefficiently",
      "By arguing that small businesses should be moved away from transit stations",
      "By claiming that housing near transit is rarely in demand",
    ],
    a: "B",
    e: "Das agrees lots are inefficient but warns about the pace of change. She does not dispute the land-use point or propose moving businesses.",
  },
  {
    id: "b-r-12",
    skill: "central-ideas",
    d: "hard",
    s: "The following text is from a novel. Clara has returned to the concert hall where she performed as a child.\n\nThe hall was smaller than it had been in her memory, as such places always are, and the velvet seats had faded to the color of weak tea. Yet when Clara stood at the edge of the stage and looked out at the empty rows, her hands began, very slightly, to tremble--exactly as they had thirty years before.",
    p: STEM.mainIdea,
    c: [
      "Although the hall seems diminished, returning to it revives in Clara the nervousness she felt as a child performer.",
      "Clara is disappointed that the hall has been poorly maintained.",
      "Clara decides to perform in the hall again.",
      "Clara no longer remembers what performing as a child felt like.",
    ],
    a: "D",
    e: "'Yet' turns from the shrunken, faded hall to the trembling that returns 'exactly as' before. Her body clearly remembers, and she makes no decision to perform.",
  },
  {
    id: "b-r-13",
    skill: "central-ideas",
    d: "medium",
    s: "Most bird species that migrate long distances fly at night. One explanation is that cooler night air reduces the risk of overheating and dehydration during sustained flight. Another is that flying at night frees the daylight hours for feeding, allowing birds to refuel between flights. Researchers note that the two explanations are not mutually exclusive.",
    p: STEM.mainIdea,
    c: [
      "Researchers have proposed two compatible explanations for why many long-distance migratory birds fly at night.",
      "Birds that migrate at night are more likely to become dehydrated than birds that migrate by day.",
      "Researchers have determined that feeding is the only reason birds migrate at night.",
      "Most migratory birds prefer to feed at night.",
    ],
    a: "A",
    e: "The text offers two explanations and notes that both can be true. It says night flight reduces dehydration and that birds feed by day.",
  },
  {
    id: "b-r-14",
    skill: "central-ideas",
    d: "hard",
    s: "When the poet published her first collection, reviewers praised its technical polish but called its subjects--kitchens, laundry, the care of aging parents--too domestic for serious poetry. Four decades later, critics cite exactly those subjects as the source of the collection's power, arguing that the poet found in ordinary household work a language for grief and devotion that more 'serious' poetry lacked.",
    p: STEM.mainIdea,
    c: [
      "Features of the poet's first collection that early reviewers criticized are now seen by critics as its greatest strength.",
      "Early reviewers criticized the poet's technical skill.",
      "The poet stopped writing about domestic subjects after her first collection.",
      "Critics today consider the collection's technical polish its only strength.",
    ],
    a: "C",
    e: "The domestic subjects once faulted are now credited with the book's power. Reviewers praised her technique, and nothing is said about her later work.",
  },
  {
    id: "b-r-15",
    skill: "command-evidence",
    d: "hard",
    s: "Marine ecologist Tomasz Wolski hypothesizes that sea otters indirectly protect seagrass meadows. By eating crabs, he argues, otters allow populations of small grazing animals--which clean algae off seagrass--to increase, and cleaner seagrass grows better.",
    p: "Which finding, if true, would most directly support Wolski's hypothesis?",
    c: [
      "In estuaries where otters had recently returned, crab numbers fell, grazer numbers rose, and seagrass cover expanded, compared with similar estuaries without otters.",
      "Sea otters eat large quantities of sea urchins as well as crabs.",
      "Seagrass meadows grow best in shallow, sunlit water.",
      "Crabs are more common in estuaries than on the open coast.",
    ],
    a: "B",
    e: "The hypothesis predicts a chain: otters, fewer crabs, more grazers, better seagrass. The first finding shows every link, compared with a control. The others do not connect otters to seagrass.",
  },
  {
    id: "b-r-16",
    skill: "command-evidence",
    d: "medium",
    s: "In the play *The Lantern Keepers*, the character Odile is portrayed as someone who distrusts change.",
    p: "Which quotation from *The Lantern Keepers* most effectively illustrates this claim?",
    c: [
      "ODILE: My mother lit this lamp the same way for forty years. I see no reason to learn another.",
      "ODILE: The wind has shifted to the north tonight.",
      "ODILE: Bring the oil from the storeroom, please.",
      "ODILE: The supply ship is two days late again.",
    ],
    a: "D",
    e: "Refusing to learn a new way because the old one served for forty years shows distrust of change. The other lines are practical remarks.",
  },
  {
    id: "b-r-17",
    skill: "command-evidence",
    d: "hard",
    s: "Anthropologist Kwame Asante argues that the large stone circles at a site in West Africa were built as astronomical calendars, with their stones aligned to mark sunrise and sunset on the solstices.",
    p: "Which finding, if true, would most directly weaken Asante's argument?",
    c: [
      "Surveys show that the stones point in many different directions, with no more of them aligned to solstice sunrise or sunset than would be expected by chance.",
      "The stones were quarried several kilometers from the site.",
      "Similar stone circles have been found at other sites in the region.",
      "Some of the circles appear to have been built over several centuries.",
    ],
    a: "A",
    e: "The argument depends on deliberate solstice alignments. Evidence that alignments occur no more often than chance undercuts it directly. The other findings say nothing about alignment.",
  },
  {
    id: "b-r-18",
    skill: "quantitative-evidence",
    d: "medium",
    s: "A researcher claims that in every age group studied, average screen time was higher on weekends than on weekdays, although the size of the difference varied.",
    fig: {
      kind: "bar",
      title: "Average Daily Screen Time (hours)",
      yLabel: "Hours per day",
      categories: ["Ages 13-15", "Ages 16-18", "Ages 19-21"],
      series: [
        { name: "Weekday", values: [5.1, 6.2, 7.0] },
        { name: "Weekend", values: [7.4, 8.9, 8.1] },
      ],
      y: [0, 10, 2],
    },
    p: "Which choice best describes data from the graph that support the researcher's claim?",
    c: [
      "In each age group, weekend screen time was higher than weekday screen time, by about 2.3 hours for ages 13-15, 2.7 hours for ages 16-18, and 1.1 hours for ages 19-21.",
      "People aged 19-21 had the most weekday screen time of any group.",
      "People aged 16-18 averaged about 8.9 hours of screen time on weekends.",
      "Weekday screen time increased with age.",
    ],
    a: "C",
    e: "The claim has two parts: weekends higher in every group, and different gaps. Only the first choice shows both. The others are accurate but address one group or weekdays only.",
  },
  {
    id: "b-r-19",
    skill: "quantitative-evidence",
    d: "hard",
    s: "Marine biologist Aroha Ngata hypothesized that coral fragments transplanted to damaged reefs would survive better when placed near established coral colonies than when attached to artificial structures.",
    fig: {
      kind: "table",
      title: "Survival of Transplanted Coral Fragments After One Year",
      head: ["Method", "Fragments planted", "Fragments surviving"],
      rows: [
        ["Cemented to bare rock", "400", "188"],
        ["Tied to metal frames", "400", "292"],
        ["Placed near existing coral", "400", "316"],
      ],
      rowHeaders: true,
    },
    p: "Which choice most effectively uses data from the table to support Ngata's hypothesis?",
    c: [
      "Of the fragments placed near existing coral, 316 of 400 survived, compared with 292 of 400 fragments tied to metal frames.",
      "Of the fragments cemented to bare rock, only 188 of 400 survived.",
      "Fragments tied to metal frames survived at a higher rate than fragments cemented to bare rock.",
      "The same number of fragments, 400, was planted using each method.",
    ],
    a: "D",
    e: "The hypothesis compares placement near colonies with artificial structures, so the relevant comparison is the metal frames. The bare-rock figures do not involve a structure-versus-colony comparison.",
  },
  {
    id: "b-r-20",
    skill: "quantitative-evidence",
    d: "hard",
    s: "Climate scientist Ruth Okonjo notes that ice cover on Lake Tern has not only shortened over the past seventy years but that the decline has sped up. For example, ______",
    fig: {
      kind: "plot",
      title: "Days of Ice Cover on Lake Tern",
      xLabel: "Year",
      yLabel: "Days of ice cover",
      x: [1950, 2020, 10],
      y: [70, 130, 10],
      series: [
        { type: "polyline", pts: [[1950, 118], [1970, 112], [1990, 101], [2010, 90], [2020, 84]] },
        { type: "points", pts: [[1950, 118], [1970, 112], [1990, 101], [2010, 90], [2020, 84]] },
      ],
    },
    p: STEM.graphComplete,
    c: [
      "ice cover shrank by an average of about 3 days per decade from 1950 to 1970 but by about 6 days in the single decade from 2010 to 2020.",
      "ice cover lasted about 118 days in 1950.",
      "ice cover lasted fewer than 100 days in both 2010 and 2020.",
      "ice cover was shorter in 2020 than in any other year shown.",
    ],
    a: "B",
    e: "Showing that a decline sped up requires comparing its rate in two periods: 6 days over two decades early on, then 6 days in one recent decade. The others give single values.",
  },
  {
    id: "b-r-21",
    skill: "quantitative-evidence",
    d: "medium",
    s: "In 2022, more books were translated into English from French than from any other language, while translations from German and Spanish were close to each other in number: ______",
    fig: {
      kind: "table",
      title: "Books Translated into English in 2022, by Original Language",
      head: ["Language", "Titles"],
      rows: [["French", "312"], ["German", "245"], ["Spanish", "238"], ["Japanese", "190"], ["Italian", "121"]],
      rowHeaders: true,
    },
    p: STEM.tableExample,
    c: [
      "245 titles were translated from German and 238 from Spanish.",
      "312 titles were translated from French.",
      "more titles were translated from Japanese than from Italian.",
      "121 titles were translated from Italian.",
    ],
    a: "A",
    e: "The blank follows the claim about German and Spanish being close, so it must give those two figures.",
  },
  {
    id: "b-r-22",
    skill: "quantitative-evidence",
    d: "hard",
    s: "A school district reported that a new tutoring program improved average test scores at every school that participated.",
    fig: {
      kind: "bar",
      title: "Average Test Scores at Participating Schools",
      yLabel: "Average score",
      categories: ["School A", "School B", "School C"],
      series: [
        { name: "Before program", values: [62, 70, 55] },
        { name: "After program", values: [68, 69, 63] },
      ],
      y: [0, 80, 20],
    },
    p: "Which choice best describes data from the graph that weaken the district's claim?",
    c: [
      "At School B, the average score fell slightly, from 70 to 69.",
      "At School C, the average score rose from 55 to 63.",
      "School B had the highest average score before the program.",
      "At School A, the average score rose by 6 points.",
    ],
    a: "C",
    e: "The claim is that scores rose at every school. A school where scores fell is a direct counterexample. The rises at A and C support the claim.",
  },
  {
    id: "b-r-23",
    skill: "quantitative-evidence",
    d: "medium",
    s: "A dietitian noted that legumes such as lentils and chickpeas tend to contain more of both protein and fiber than grains such as quinoa and brown rice. For example, ______",
    fig: {
      kind: "table",
      title: "Nutrient Content per 100 Grams (cooked)",
      head: ["Food", "Protein (g)", "Fiber (g)"],
      rows: [
        ["Lentils", "9.0", "7.9"],
        ["Quinoa", "4.4", "2.8"],
        ["Brown rice", "2.6", "1.8"],
        ["Chickpeas", "8.9", "7.6"],
      ],
      rowHeaders: true,
    },
    p: STEM.tableExample,
    c: [
      "lentils contain 9.0 grams of protein and 7.9 grams of fiber per 100 grams, while quinoa contains 4.4 grams of protein and 2.8 grams of fiber.",
      "chickpeas contain 8.9 grams of protein per 100 grams.",
      "brown rice contains less fiber than quinoa.",
      "lentils contain slightly more protein than chickpeas.",
    ],
    a: "D",
    e: "The example must compare a legume with a grain on both nutrients. Only the lentil-quinoa comparison does that.",
  },
  {
    id: "b-r-24",
    skill: "inferences",
    d: "hard",
    s: "In the 1800s, many European cities grew so quickly that their water systems could not keep up, and outbreaks of waterborne disease were common. Records from one city show that after a new sewer system opened in 1868, deaths from cholera and typhoid fell sharply in the neighborhoods it served but remained high in neighborhoods it had not yet reached. This pattern suggests that ______",
    p: STEM.complete,
    c: [
      "the new sewer system, rather than some citywide change happening at the same time, was largely responsible for the decline in deaths.",
      "cholera and typhoid were no longer a threat anywhere in the city after 1868.",
      "the city's population declined sharply after the sewer system opened.",
      "neighborhoods without the sewer system had cleaner water than those with it.",
    ],
    a: "B",
    e: "A citywide cause would have lowered deaths everywhere. Because deaths fell only where the sewers reached, the sewers are the likely cause.",
  },
  {
    id: "b-r-25",
    skill: "inferences",
    d: "medium",
    s: "The nectar of many plants contains small amounts of caffeine. Researchers found that bees that fed on caffeinated nectar were more likely to remember a flower's scent and return to it than bees that fed on nectar without caffeine. This suggests that caffeine in nectar may ______",
    p: STEM.complete,
    c: [
      "benefit plants by encouraging bees to return to their flowers.",
      "harm bees by making it harder for them to remember scents.",
      "discourage bees from visiting flowers.",
      "make nectar less nutritious for bees.",
    ],
    a: "D",
    e: "Bees that remember and revisit flowers pollinate them more, which benefits the plant. The finding shows better, not worse, memory.",
  },
  {
    id: "b-r-26",
    skill: "inferences",
    d: "hard",
    s: "Glaciers carry rocks far from where they formed and leave them behind when the ice melts. In 1840, naturalist Louis Agassiz pointed to large boulders scattered across the plains of northern Europe--made of rock unlike any bedrock nearby--as evidence that ______",
    p: STEM.complete,
    c: [
      "the region had once been covered by glaciers.",
      "the boulders had formed where they were found.",
      "rivers had carried the boulders from the nearby hills.",
      "northern Europe had never experienced a colder climate.",
    ],
    a: "A",
    e: "Boulders unlike the local bedrock were carried from elsewhere, and the text names glaciers as a carrier of such rocks. So the boulders point to past glaciers.",
  },
  {
    id: "b-r-27",
    skill: "boundaries",
    d: "hard",
    s: "The tallest known living tree, a coast redwood named ______ stands about 116 meters high in a remote part of California's Redwood National Park.",
    p: STEM.sec,
    c: ["Hyperion,", "Hyperion", "Hyperion;", "Hyperion:"],
    a: "B",
    e: "'A coast redwood named Hyperion' is a nonessential appositive opened with a comma after 'tree,' so it must close with a comma before the verb 'stands.'",
  },
  {
    id: "b-r-28",
    skill: "boundaries",
    d: "medium",
    s: "Researchers studying the eruption collected samples of ash, pumice, and volcanic ______ each type of material provides different clues about the force of the eruption.",
    p: STEM.sec,
    c: ["glass;", "glass,", "glass", "glass and,"],
    a: "C",
    e: "Two independent clauses meet at the blank, so a semicolon separates them. A comma alone would be a comma splice.",
  },
  {
    id: "b-r-29",
    skill: "boundaries",
    d: "hard",
    s: "Maria Tallchief, who in 1947 became the first Native American to hold the title of prima ballerina at a major American ballet ______ was celebrated for her speed, precision, and dramatic intensity.",
    p: STEM.sec,
    c: ["company,", "company", "company;", "company--"],
    a: "D",
    e: "The nonessential clause opens with a comma after 'Tallchief,' so it closes with a comma before the verb 'was.'",
  },
  {
    id: "b-r-30",
    skill: "boundaries",
    d: "hard",
    s: "The investigators' findings pointed to a single ______ contaminated irrigation water from a nearby canal.",
    p: STEM.sec,
    c: ["source:", "source;", "source", "source, it was"],
    a: "A",
    e: "A colon after a complete clause introduces what the clause points to. A semicolon would leave a fragment, and 'source, it was' creates a comma splice.",
  },
  {
    id: "b-r-31",
    skill: "subject-verb",
    d: "medium",
    s: "The results of the survey, which was conducted in twelve countries, ______ that most respondents trust local news more than national news.",
    p: STEM.sec,
    c: ["indicate", "indicates", "has indicated", "is indicating"],
    a: "B",
    e: "The subject is 'results,' which is plural, so the verb is 'indicate.' 'Survey' and 'countries' sit inside modifying phrases.",
  },
  {
    id: "b-r-32",
    skill: "form-structure-sense",
    d: "medium",
    s: "Octopuses are solitary animals, and most species live only a year or two; nevertheless, ______ problem-solving abilities rival those of some mammals.",
    p: STEM.sec,
    c: ["their", "its", "there", "they're"],
    a: "A",
    e: "The possessive refers to 'octopuses,' which is plural, so 'their' is correct.",
  },
  {
    id: "b-r-33",
    skill: "form-structure-sense",
    d: "hard",
    s: "Scientists predict that by 2050 the glacier ______ more than half of its current mass.",
    p: STEM.sec,
    c: ["will have lost", "has lost", "had lost", "loses"],
    a: "C",
    e: "'By 2050' marks an action completed before a future point, which calls for the future perfect: 'will have lost.'",
  },
  {
    id: "b-r-34",
    skill: "transitions",
    d: "hard",
    s: "Most lizards lay eggs. A number of species, ______ give birth to live young--a trait that seems to have evolved independently dozens of times, often in species living in cold climates.",
    p: STEM.transition,
    c: ["however,", "therefore,", "for example,", "similarly,"],
    a: "D",
    e: "Species that give birth to live young are an exception to egg-laying, so a contrasting transition fits.",
  },
  {
    id: "b-r-35",
    skill: "transitions",
    d: "medium",
    s: "The first commercial jet airliner, the de Havilland Comet, entered service in 1952 to great acclaim. ______ a series of fatal crashes caused by metal fatigue grounded the entire fleet within two years.",
    p: STEM.transition,
    c: ["However,", "For example,", "As a result,", "Similarly,"],
    a: "A",
    e: "The crashes and grounding reverse the acclaimed launch, so a contrasting transition fits.",
  },
  {
    id: "b-r-36",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "The Voyager 1 space probe was launched in 1977.",
      "In 2012, it became the first human-made object to enter interstellar space.",
      "It carries a gold-plated record with sounds and images from Earth.",
      "Its instruments are powered by a generator that converts heat from decaying plutonium into electricity.",
    ),
    p: goal("emphasize a historic milestone reached by Voyager 1."),
    c: [
      "In 2012, Voyager 1, launched in 1977, became the first human-made object to enter interstellar space.",
      "Voyager 1 carries a gold-plated record with sounds and images from Earth.",
      "Voyager 1's instruments are powered by heat from decaying plutonium.",
      "The Voyager 1 space probe was launched in 1977.",
    ],
    a: "B",
    e: "Being the first human-made object in interstellar space is the milestone. The others describe its equipment or launch.",
  },
];

export const BANK_PLUS = build([...MATH, ...RW]);
