/**
 * The PSAT/NMSQT practice bank.
 *
 * The PSAT shares the digital SAT's domains and skills, so these questions are
 * written in the same shorthand as the SAT's (`author.ts`) and tagged
 * `testId: "psat"`. They are pitched at the PSAT's range: more easy and medium
 * items, and "hard" here means the top of the PSAT, which stops short of the
 * SAT's hardest questions.
 *
 * Every item was written for Pathforge. None of it is College Board material,
 * and passages are about invented people, places and studies.
 */

import { STEM, goal, notes, q, texts, type QSpec } from "./author";

/* ------------------------------------------------------------------ */
/* Math                                                                */
/* ------------------------------------------------------------------ */

const MATH: QSpec[] = [
  {
    id: "ps-m-01",
    skill: "linear-eq-1var",
    d: "easy",
    p: "If 5x + 3 = 38, what is the value of x?",
    c: ["7", "6", "8", "41/5"],
    a: "B",
    e: "Subtract 3 from both sides: 5x = 35. Divide by 5: x = 7.",
  },
  {
    id: "ps-m-02",
    skill: "linear-eq-1var",
    d: "medium",
    p: "If 2(x - 3) + 4 = 3x - 9, what is the value of x?",
    a: "7",
    e: "Distribute and combine: 2x - 6 + 4 = 2x - 2. Then 2x - 2 = 3x - 9, so x = 7.",
  },
  {
    id: "ps-m-03",
    skill: "linear-eq-1var",
    d: "hard",
    p: "In the equation 4(ax - 1) = 12x + b, a and b are constants. If the equation has infinitely many solutions, what is the value of a + b?",
    c: ["-1", "7", "-7", "3"],
    a: "C",
    e: "The left side is 4ax - 4. For infinitely many solutions both sides must be identical, so 4a = 12 and b = -4. Then a = 3 and a + b = -1.",
  },
  {
    id: "ps-m-04",
    skill: "linear-eq-2var",
    d: "easy",
    p: "A store sells notebooks for $3 each and pens for $1 each. Maya spends exactly $20 on n notebooks and p pens. Which equation represents this situation?",
    c: ["3n + p = 20", "n + 3p = 20", "3np = 20", "4(n + p) = 20"],
    a: "A",
    e: "The notebooks cost 3n dollars and the pens cost p dollars, and together they cost 20 dollars: 3n + p = 20.",
  },
  {
    id: "ps-m-05",
    skill: "linear-eq-2var",
    d: "medium",
    p: "The graph of 2x + 5y = 30 in the xy-plane crosses the y-axis at the point (0, k). What is the value of k?",
    a: "6",
    e: "On the y-axis x = 0, so 5y = 30 and y = 6.",
  },
  {
    id: "ps-m-06",
    skill: "linear-functions",
    d: "easy",
    p: "A plumber charges a $60 visit fee plus $45 for each hour of work. Which function gives the total charge C(h), in dollars, for a job that takes h hours?",
    c: ["C(h) = 45h + 60", "C(h) = 60h + 45", "C(h) = 105h", "C(h) = 45(h + 60)"],
    a: "D",
    e: "The fee of 60 is charged once, and 45 is charged for each of the h hours, so C(h) = 45h + 60.",
  },
  {
    id: "ps-m-07",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "table",
      head: ["x", "0", "2", "5"],
      rows: [["f(x)", "4", "10", "19"]],
      rowHeaders: true,
    },
    p: "The table shows three values of x and their corresponding values of f(x), where f is a linear function. What is the value of f(8)?",
    a: "28",
    e: "The slope is (10 - 4)/(2 - 0) = 3 and f(0) = 4, so f(x) = 3x + 4 and f(8) = 28.",
  },
  {
    id: "ps-m-08",
    skill: "linear-functions",
    d: "hard",
    p: "Line {l} in the xy-plane passes through the point (1, 4) and is perpendicular to the line y = -(1/3)x + 2. What is the y-intercept of line {l}?",
    c: ["1", "4", "-1", "11/3"],
    a: "B",
    e: "A perpendicular slope is the negative reciprocal of -1/3, which is 3. Then y - 4 = 3(x - 1), so y = 3x + 1 and the y-intercept is 1.",
  },
  {
    id: "ps-m-09",
    skill: "systems-linear",
    d: "easy",
    s: "x + y = 10\nx - y = 4",
    p: "What is the value of x in the solution to the given system of equations?",
    c: ["7", "3", "6", "14"],
    a: "A",
    e: "Add the equations: 2x = 14, so x = 7.",
  },
  {
    id: "ps-m-10",
    skill: "systems-linear",
    d: "medium",
    p: "At a fair, 3 hot dogs and 2 drinks cost $13, and 1 hot dog and 2 drinks cost $7. What is the cost, in dollars, of one hot dog?",
    a: "3",
    e: "Subtract the second purchase from the first: 2 hot dogs cost 13 - 7 = 6 dollars, so one costs 3 dollars.",
  },
  {
    id: "ps-m-11",
    skill: "systems-linear",
    d: "hard",
    s: "6x - 4y = 10\nkx - 2y = 3",
    p: "In the given system of equations, k is a constant. If the system has no solution, what is the value of k?",
    a: "3",
    e: "No solution means the lines are parallel and distinct. Halving the first equation gives 3x - 2y = 5, so k = 3 makes the left sides match while the right sides (5 and 3) differ.",
  },
  {
    id: "ps-m-12",
    skill: "linear-inequalities",
    d: "easy",
    p: "Which value of x is a solution to the inequality 3x - 7 > 11?",
    c: ["7", "6", "5", "0"],
    a: "C",
    e: "Add 7 and divide by 3: x > 6. Of the choices, only 7 is greater than 6.",
  },
  {
    id: "ps-m-13",
    skill: "linear-inequalities",
    d: "medium",
    p: "A van can carry at most 1,200 pounds. The driver weighs 180 pounds, and each box weighs 40 pounds. What is the greatest number of boxes the van can carry along with the driver?",
    a: "25",
    e: "180 + 40b <= 1,200 gives 40b <= 1,020, so b <= 25.5. The number of boxes must be a whole number, so the greatest is 25.",
  },
  {
    id: "ps-m-14",
    skill: "quadratics",
    d: "easy",
    p: "What are the solutions to the equation x^2 - 9 = 0?",
    c: ["3 and -3", "9 and -9", "3 only", "0 and 9"],
    a: "B",
    e: "x^2 = 9, so x = 3 or x = -3.",
  },
  {
    id: "ps-m-15",
    skill: "quadratics",
    d: "medium",
    p: "What is the positive solution to the equation x^2 - 5x - 14 = 0?",
    a: "7",
    e: "Factor: (x - 7)(x + 2) = 0, so x = 7 or x = -2. The positive solution is 7.",
  },
  {
    id: "ps-m-16",
    skill: "quadratics",
    d: "hard",
    p: "In the equation x^2 + bx + 25 = 0, b is a positive constant. If the equation has exactly one real solution, what is the value of b?",
    a: "10",
    e: "Exactly one real solution means the discriminant is zero: b^2 - 4(1)(25) = 0, so b^2 = 100 and, since b is positive, b = 10.",
  },
  {
    id: "ps-m-17",
    skill: "nonlinear-functions",
    d: "easy",
    p: "The function f is defined by f(x) = x^2 + 3. What is the value of f(4)?",
    c: ["19", "11", "16", "49"],
    a: "D",
    e: "f(4) = 4^2 + 3 = 16 + 3 = 19.",
  },
  {
    id: "ps-m-18",
    skill: "nonlinear-functions",
    d: "medium",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-2, 6, 1],
      y: [-2, 8, 1],
      series: [{ type: "fn", f: (x) => (x - 2) ** 2 - 1, domain: [-1, 5] }],
      alt: "A parabola opening upward with its vertex at (2, negative 1).",
    },
    p: "The graph of y = f(x) is shown in the xy-plane. What is the minimum value of f(x)?",
    c: ["-1", "2", "0", "3"],
    a: "A",
    e: "The lowest point of the parabola is its vertex, (2, -1). The minimum value of f(x) is the y-coordinate there, -1. (2 is the x-value where the minimum occurs.)",
  },
  {
    id: "ps-m-19",
    skill: "nonlinear-functions",
    d: "hard",
    p: "The function g is defined by g(x) = |x - 3| + 2. For how many values of x does g(x) = 5?",
    c: ["2", "1", "0", "3"],
    a: "B",
    e: "|x - 3| + 2 = 5 means |x - 3| = 3, so x - 3 = 3 or x - 3 = -3. That gives x = 6 or x = 0: two values.",
  },
  {
    id: "ps-m-20",
    skill: "equivalent-expressions",
    d: "easy",
    p: "Which expression is equivalent to 3(2x + 5) - x?",
    c: ["5x + 15", "6x + 15", "5x + 5", "7x + 15"],
    a: "C",
    e: "3(2x + 5) = 6x + 15, and 6x + 15 - x = 5x + 15.",
  },
  {
    id: "ps-m-21",
    skill: "equivalent-expressions",
    d: "medium",
    p: "Which expression is equivalent to (x + 4)^2?",
    c: ["x^2 + 8x + 16", "x^2 + 16", "x^2 + 4x + 16", "2x + 8"],
    a: "A",
    e: "(x + 4)(x + 4) = x^2 + 4x + 4x + 16 = x^2 + 8x + 16. Squaring each term separately misses the middle term.",
  },
  {
    id: "ps-m-22",
    skill: "equivalent-expressions",
    d: "hard",
    p: "Which expression is equivalent to (x^2 - 4)/(x + 2), for x != -2?",
    c: ["x - 2", "x + 2", "x^2 - 2", "x - 4"],
    a: "D",
    e: "x^2 - 4 is a difference of squares, (x - 2)(x + 2). Dividing by x + 2 leaves x - 2.",
  },
  {
    id: "ps-m-23",
    skill: "exponential",
    d: "easy",
    p: "A town has a population of 8,000, and the population grows by 5% each year. Which expression gives the population after t years?",
    c: ["8,000(1.05)^{t}", "8,000(0.05)^{t}", "8,000 + 0.05t", "8,000(1.5)^{t}"],
    a: "B",
    e: "Growing by 5% multiplies the population by 1 + 0.05 = 1.05 each year, so after t years it is 8,000(1.05)^{t}.",
  },
  {
    id: "ps-m-24",
    skill: "exponential",
    d: "medium",
    p: "A car bought for $20,000 loses 15% of its value each year. What is the car's value, in dollars, 2 years after it is bought?",
    a: "14450",
    alt: ["14,450"],
    e: "Each year the value is multiplied by 0.85. After 2 years: 20,000 {times} 0.85^2 = 20,000 {times} 0.7225 = 14,450.",
  },
  {
    id: "ps-m-25",
    skill: "ratios-rates",
    d: "easy",
    p: "A recipe uses 3 cups of flour for every 2 cups of sugar. How many cups of flour are needed for 8 cups of sugar?",
    c: ["12", "11", "16", "6"],
    a: "C",
    e: "8 cups of sugar is 4 times 2 cups, so the flour is 4 times 3 cups: 12 cups.",
  },
  {
    id: "ps-m-26",
    skill: "ratios-rates",
    d: "medium",
    p: "A cyclist rides 18 miles in 1.5 hours. At this rate, how many minutes will it take the cyclist to ride 30 miles?",
    a: "150",
    e: "The rate is 18 / 1.5 = 12 miles per hour. 30 miles takes 30 / 12 = 2.5 hours, which is 150 minutes.",
  },
  {
    id: "ps-m-27",
    skill: "percentages",
    d: "easy",
    p: "What is 30% of 250?",
    c: ["75", "25", "83", "7.5"],
    a: "A",
    e: "0.30 {times} 250 = 75.",
  },
  {
    id: "ps-m-28",
    skill: "percentages",
    d: "medium",
    p: "The price of a jacket was reduced from $80 to $68. By what percent was the price reduced?",
    c: ["15%", "12%", "18%", "85%"],
    a: "B",
    e: "The reduction is 80 - 68 = 12 dollars, and 12 / 80 = 0.15, or 15%. (68 is 85% of the original price.)",
  },
  {
    id: "ps-m-29",
    skill: "data-distributions",
    d: "easy",
    p: "What is the mean of the data set 4, 7, 7, 9, 13?",
    c: ["8", "7", "9", "13"],
    a: "D",
    e: "The sum is 4 + 7 + 7 + 9 + 13 = 40, and 40 / 5 = 8.",
  },
  {
    id: "ps-m-30",
    skill: "data-distributions",
    d: "medium",
    fig: {
      kind: "table",
      title: "Books Read Last Month by Club Members",
      head: ["Number of books", "0", "1", "2", "3"],
      rows: [["Number of members", "2", "5", "4", "1"]],
      rowHeaders: true,
    },
    p: "The table shows how many books each of the 12 members of a reading club read last month. What is the median number of books read?",
    c: ["1", "1.5", "2", "5"],
    a: "A",
    e: "Listed in order, the values are 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3. The median is the mean of the 6th and 7th values, which are both 1.",
  },
  {
    id: "ps-m-31",
    skill: "data-distributions",
    d: "hard",
    p: "Data set A consists of the values 10, 12, 14, 16, and 18. Data set B consists of the same five values and the value 40. Which statement comparing the two data sets is true?",
    c: [
      "The mean of data set B is greater than the mean of data set A by more than the median of B is greater than the median of A.",
      "The median of data set B is greater than the median of data set A by more than the mean of B is greater than the mean of A.",
      "The mean and the median increase by the same amount.",
      "Neither the mean nor the median changes.",
    ],
    a: "C",
    e: "Set A has mean 14 and median 14. Set B has mean 110 / 6, about 18.3, and median (14 + 16) / 2 = 15. The mean rose by about 4.3 and the median by only 1: an outlier pulls the mean far more than the median.",
  },
  {
    id: "ps-m-32",
    skill: "probability",
    d: "easy",
    p: "A bag contains 4 red marbles, 5 blue marbles, and 3 green marbles. If one marble is chosen at random, what is the probability that it is blue?",
    c: ["5/12", "1/3", "5/7", "1/5"],
    a: "B",
    e: "There are 4 + 5 + 3 = 12 marbles, and 5 of them are blue, so the probability is 5/12.",
  },
  {
    id: "ps-m-33",
    skill: "probability",
    d: "medium",
    fig: {
      kind: "table",
      title: "How Surveyed Students Get to School",
      head: ["", "Walk", "Bus", "Total"],
      rows: [
        ["Grade 9", "30", "70", "100"],
        ["Grade 10", "45", "55", "100"],
        ["Total", "75", "125", "200"],
      ],
      rowHeaders: true,
    },
    p: "The table summarizes a survey of 200 students. If one of the students who walk to school is chosen at random, what is the probability that the student is in grade 10?",
    c: ["3/5", "9/20", "2/5", "9/40"],
    a: "C",
    e: "Only the 75 students who walk count. Of those, 45 are in grade 10, so the probability is 45/75 = 3/5.",
  },
  {
    id: "ps-m-34",
    skill: "inference",
    d: "medium",
    p: "A random sample of 150 of a school's 1,200 students found that 42 of the students in the sample bike to school. Based on the sample, which is the best estimate of the number of students at the school who bike to school?",
    c: ["336", "42", "280", "864"],
    a: "D",
    e: "In the sample, 42 / 150 = 0.28 of students bike. Applied to the whole school: 0.28 {times} 1,200 = 336.",
  },
  {
    id: "ps-m-35",
    skill: "area-volume",
    d: "easy",
    p: "A rectangular box is 5 centimeters long, 4 centimeters wide, and 3 centimeters tall. What is the volume of the box, in cubic centimeters?",
    a: "60",
    e: "Volume = length {times} width {times} height = 5 {times} 4 {times} 3 = 60.",
  },
  {
    id: "ps-m-36",
    skill: "area-volume",
    d: "medium",
    p: "A right circular cylinder has a radius of 3 and a height of 10. The volume of the cylinder is k{pi}. What is the value of k?",
    a: "90",
    e: "V = {pi}r^2h = {pi}(3^2)(10) = 90{pi}, so k = 90.",
  },
  {
    id: "ps-m-37",
    skill: "lines-angles-triangles",
    d: "easy",
    p: "Two angles of a triangle measure 48{deg} and 71{deg}. What is the measure of the third angle?",
    c: ["61{deg}", "119{deg}", "71{deg}", "48{deg}"],
    a: "A",
    e: "The angles of a triangle sum to 180{deg}: 180 - 48 - 71 = 61.",
  },
  {
    id: "ps-m-38",
    skill: "lines-angles-triangles",
    d: "medium",
    p: "Two parallel lines are cut by a transversal, and one of the angles formed measures 115{deg}. What is the measure of each acute angle formed?",
    c: ["65{deg}", "75{deg}", "115{deg}", "25{deg}"],
    a: "B",
    e: "Every angle formed is either 115{deg} or its supplement, 180 - 115 = 65{deg}. The acute ones are 65{deg}.",
  },
  {
    id: "ps-m-39",
    skill: "right-triangles-trig",
    d: "medium",
    p: "A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?",
    a: "15",
    e: "9^2 + 12^2 = 81 + 144 = 225, and the square root of 225 is 15.",
  },
  {
    id: "ps-m-40",
    skill: "right-triangles-trig",
    d: "hard",
    p: "In right triangle ABC, angle C is the right angle and sin A = 5/13. What is the value of tan A?",
    c: ["5/12", "12/13", "12/5", "13/5"],
    a: "C",
    e: "sin A = 5/13 means the side opposite A is 5 and the hypotenuse is 13. The adjacent side is the square root of 169 - 25, which is 12, so tan A = 5/12.",
  },
  {
    id: "ps-m-41",
    skill: "circles",
    d: "medium",
    p: "A circle has a circumference of 18{pi}. What is the area of the circle?",
    c: ["81{pi}", "18{pi}", "36{pi}", "324{pi}"],
    a: "D",
    e: "2{pi}r = 18{pi} gives r = 9, so the area is {pi}(9^2) = 81{pi}.",
  },
  {
    id: "ps-m-42",
    skill: "circles",
    d: "hard",
    p: "The equation x^2 + y^2 - 6x + 4y = 12 defines a circle in the xy-plane. What is the radius of the circle?",
    a: "5",
    e: "Complete the square: (x^2 - 6x + 9) + (y^2 + 4y + 4) = 12 + 9 + 4, so (x - 3)^2 + (y + 2)^2 = 25 and the radius is 5.",
  },
];

/* ------------------------------------------------------------------ */
/* Reading and Writing                                                 */
/* ------------------------------------------------------------------ */

const RW: QSpec[] = [
  // Craft and Structure
  {
    id: "ps-r-01",
    skill: "words-in-context",
    d: "easy",
    s: "The new library's reading room is famously ______: visitors speak in whispers, and even the air vents were redesigned to run silently.",
    p: STEM.wic,
    c: ["quiet", "crowded", "colorful", "expensive"],
    a: "B",
    e: "Whispering visitors and silent air vents describe a quiet room. Nothing in the text supports crowded, colorful or expensive.",
  },
  {
    id: "ps-r-02",
    skill: "words-in-context",
    d: "medium",
    s: "Botanist Ines Varga found that the seeds of the dune plant she studied can remain ______ in dry sand for years, sprouting only after an unusually heavy rain.",
    p: STEM.wic,
    c: ["dormant", "visible", "fragile", "abundant"],
    a: "C",
    e: "Seeds that wait for years and sprout only after heavy rain are inactive but alive: dormant. The text says nothing about whether they can be seen, break easily or are numerous.",
  },
  {
    id: "ps-r-03",
    skill: "words-in-context",
    d: "hard",
    s: "Although critics had dismissed the composer's early symphonies as derivative, a 2019 retrospective prompted a ______ assessment: several reviewers now describe the same works as quietly inventive.",
    p: STEM.wic,
    c: ["more favorable", "more hasty", "similarly harsh", "purely technical"],
    a: "A",
    e: "\"Although\" sets the new view against the old dismissal, and \"quietly inventive\" is praise, so the assessment became more favorable.",
  },
  {
    id: "ps-r-04",
    skill: "words-in-context",
    d: "medium",
    s: "The historian's account is notably ______: she presents the evidence for each competing theory in detail and declines to say which one she finds most convincing.",
    p: STEM.wic,
    c: ["even-handed", "persuasive", "brief", "sentimental"],
    a: "C",
    e: "Giving every theory a full hearing and refusing to pick one is being even-handed. She is explicitly not trying to persuade, and detailed evidence is not brief.",
  },
  {
    id: "ps-r-05",
    skill: "text-structure",
    d: "medium",
    s: "Many people assume that city parks mostly benefit the neighborhoods right next to them. A study of one city's park system, however, found that visitors traveled an average of 3 miles to reach their favorite park, and that parks with sports fields drew visitors from across the city. The researchers concluded that a park's benefits often extend well beyond its immediate surroundings.",
    p: STEM.structure,
    c: [
      "It presents a common assumption, then describes a finding that challenges it.",
      "It describes a study, then questions whether the study's methods were sound.",
      "It compares two parks, then recommends one over the other.",
      "It lists the features of several parks, then ranks them.",
    ],
    a: "D",
    e: "The text opens with what many people assume, and \"however\" introduces a study whose findings point the other way.",
  },
  {
    id: "ps-r-06",
    skill: "text-structure",
    d: "easy",
    s: "Before the town of Carrow built its first bridge, residents crossed the river on a ferry that ran only in daylight. Farmers who needed to reach the market before dawn often left the night before and slept on the riverbank. When the bridge opened in 1904, the market's opening hour moved two hours earlier.",
    p: STEM.purpose,
    c: [
      "To show how a new bridge changed daily routines in a town",
      "To argue that ferries are safer than bridges",
      "To explain how the bridge in Carrow was designed",
      "To describe the goods sold at Carrow's market",
    ],
    a: "A",
    e: "The text contrasts life before the bridge (overnight trips to beat the ferry schedule) with a change after it (an earlier market). It says nothing about safety, design or goods.",
  },
  {
    id: "ps-r-07",
    skill: "text-structure",
    d: "hard",
    s: "Most maps of the ocean floor were once drawn from scattered depth measurements taken by ships. In the 1990s, scientists began using satellites to measure tiny bumps in the sea surface, which mirror mountains and trenches far below. The resulting maps covered the entire ocean for the first time, though at lower detail than ship surveys.",
    p: STEM.purpose,
    c: [
      "To explain how satellite measurements made complete maps of the ocean floor possible",
      "To argue that ship surveys should no longer be used",
      "To describe the tallest undersea mountains",
      "To compare two satellites used by ocean scientists",
    ],
    a: "B",
    e: "The text moves from the old method to the satellite method and its result, full coverage. It notes ship surveys are more detailed, so it is not arguing against them.",
  },
  {
    id: "ps-r-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Some historians argue that the spread of printed almanacs in the eighteenth century mainly helped farmers, who used the almanacs' weather predictions to plan their planting.",
      "Historian Tomas Reyes notes that almanac weather predictions were rarely accurate. He argues that the almanacs mattered more for their calendars and tide tables, which readers in many trades relied on every day.",
    ),
    p: "Based on the texts, how would Reyes (Text 2) most likely respond to the historians' claim in Text 1?",
    c: [
      "He would argue that the almanacs' value came mostly from features other than their weather predictions.",
      "He would agree that farmers were the almanacs' most important readers.",
      "He would argue that almanacs were not widely read in the eighteenth century.",
      "He would claim that farmers ignored almanacs entirely.",
    ],
    a: "B",
    e: "Text 1 credits the weather predictions; Reyes says those were rarely accurate and that the calendars and tide tables mattered more. He does not dispute that almanacs were widely read.",
  },

  // Information and Ideas
  {
    id: "ps-r-09",
    skill: "central-ideas",
    d: "easy",
    s: "Beekeeper Aldo Ferri places his hives near fields of wildflowers rather than near a single crop. He has found that bees with access to many kinds of flowers produce more honey and survive the winter in greater numbers than bees kept near one crop.",
    p: STEM.mainIdea,
    c: [
      "Ferri has found that bees near varied wildflowers do better than bees near a single crop.",
      "Ferri prefers wildflowers because they are more attractive than crops.",
      "Ferri's bees produce less honey in winter than in summer.",
      "Ferri believes beekeepers should avoid all farm fields.",
    ],
    a: "A",
    e: "The text's point is the comparison: more honey and better winter survival near varied flowers. The other choices add claims the text never makes.",
  },
  {
    id: "ps-r-10",
    skill: "central-ideas",
    d: "medium",
    s: "Nadia had practiced the piece every evening for a month, yet when she sat at the piano in the recital hall, her hands felt as if they belonged to someone else. She looked out at the audience, found her grandmother's face in the third row, and began to play.",
    p: STEM.mainIdea,
    c: [
      "Nadia feels nervous before her recital but finds steadiness when she sees a familiar face.",
      "Nadia regrets not practicing more before her recital.",
      "Nadia's grandmother taught her to play the piano.",
      "Nadia decides not to perform the piece she practiced.",
    ],
    a: "C",
    e: "Her hands feel like someone else's (nerves), and she begins to play after finding her grandmother (steadiness). She practiced every evening, and she does perform.",
  },
  {
    id: "ps-r-11",
    skill: "central-ideas",
    d: "hard",
    s: "For decades, researchers judged the health of a lake mainly by counting its fish. Ecologist Mira Castell argues that this approach misses early warning signs. Changes among the lake's tiny plankton species, she notes, often appear years before fish populations decline, so monitoring plankton could give managers time to act.",
    p: STEM.mainIdea,
    c: [
      "Castell argues that monitoring plankton could reveal problems in a lake earlier than counting fish does.",
      "Castell argues that fish counts are the most reliable measure of a lake's health.",
      "Castell has found that plankton populations recover faster than fish populations.",
      "Castell believes lake managers should stop counting fish altogether.",
    ],
    a: "D",
    e: "Castell's point is timing: plankton changes come years before fish declines. She says fish counts miss early signs, not that they should be abandoned.",
  },
  {
    id: "ps-r-12",
    skill: "command-evidence",
    d: "medium",
    s: "Marine biologist Sun-Hee Park hypothesizes that a species of reef fish recognizes individual members of its group by the patterns on their faces rather than by the shapes of their bodies.",
    p: "Which finding, if true, would most directly support Park's hypothesis?",
    c: [
      "The fish reacted calmly to images of group members' faces placed on unfamiliar body shapes but reacted aggressively to unfamiliar faces placed on familiar body shapes.",
      "The fish reacted aggressively to all images, regardless of face or body shape.",
      "The fish spent more time near images of larger fish than near images of smaller fish.",
      "The fish could not distinguish between any two images shown to them.",
    ],
    a: "B",
    e: "Swapping faces and bodies separates the two cues. Calm reactions that follow the familiar face, not the familiar body, are exactly what the hypothesis predicts.",
  },
  {
    id: "ps-r-13",
    skill: "command-evidence",
    d: "hard",
    s: "Student Amara Diaz claims that, in the opening chapter of an invented novel, the narrator Jonah feels uneasy about moving to the city.",
    p: "Which quotation from the chapter would most effectively support Diaz's claim?",
    c: [
      "\"Jonah lay awake the night before the move, listing everything that could go wrong.\"",
      "\"The city had more bakeries than Jonah's whole town had houses.\"",
      "\"Jonah's mother wrapped the dishes in newspaper.\"",
      "\"The train left the station at exactly seven o'clock.\"",
    ],
    a: "A",
    e: "Lying awake listing what could go wrong shows unease about the move. The other quotations describe the city, the packing or the schedule, not Jonah's feelings.",
  },
  {
    id: "ps-r-14",
    skill: "quantitative-evidence",
    d: "medium",
    fig: {
      kind: "table",
      title: "Average Daily Visitors at Three Museums in Lorne",
      head: ["Museum", "2021", "2023"],
      rows: [
        ["Harbor Museum", "410", "620"],
        ["Ridge Gallery", "530", "505"],
        ["Pine Science Center", "300", "590"],
      ],
    },
    s: "A student claims that, from 2021 to 2023, the Pine Science Center had the largest increase in average daily visitors of the three museums in the table.",
    p: "Which choice most effectively uses data from the table to support the student's claim?",
    c: [
      "The Pine Science Center's average rose by 290 visitors, compared with 210 for the Harbor Museum, while the Ridge Gallery's average fell.",
      "The Ridge Gallery had the most visitors of the three museums in 2021.",
      "The Harbor Museum had 620 average daily visitors in 2023.",
      "The Pine Science Center had fewer visitors than the Ridge Gallery in 2021.",
    ],
    a: "D",
    e: "The claim is about the size of each increase, so the support must compare increases: 590 - 300 = 290, 620 - 410 = 210, and 505 - 530 is a decrease.",
  },
  {
    id: "ps-r-15",
    skill: "quantitative-evidence",
    d: "hard",
    fig: {
      kind: "bar",
      title: "Oak Seedlings Surviving After 60 Days",
      yLabel: "Percent surviving",
      categories: ["No mulch", "Straw mulch", "Bark mulch"],
      series: [{ name: "Percent surviving", values: [48, 81, 74] }],
      y: [0, 100, 20],
      alt: "Bar chart: 48 percent with no mulch, 81 percent with straw mulch, 74 percent with bark mulch.",
    },
    s: "Horticulturist Dana Whitfield tested whether covering soil with mulch helps young oak seedlings survive a dry summer. She concluded that both mulches improved survival and that straw was the more effective of the two.",
    p: "Which choice most effectively uses data from the graph to support Whitfield's conclusion?",
    c: [
      "81% of seedlings survived with straw mulch and 74% with bark mulch, compared with 48% with no mulch.",
      "48% of seedlings survived with no mulch.",
      "Seedlings with bark mulch survived at a rate of 74%.",
      "Survival was lower with bark mulch than with straw mulch.",
    ],
    a: "B",
    e: "The conclusion has two parts, so the evidence needs all three bars: both mulches beat no mulch (81% and 74% versus 48%), and straw beat bark. The last choice supports only the second part.",
  },
  {
    id: "ps-r-16",
    skill: "quantitative-evidence",
    d: "medium",
    fig: {
      kind: "table",
      title: "Share of Surveyed Residents Using Each Option",
      head: ["Option", "Weekdays", "Weekends"],
      rows: [
        ["Bus", "38%", "22%"],
        ["Bicycle", "12%", "19%"],
        ["Train", "27%", "9%"],
      ],
    },
    s: "A city planner claims that bicycles are the only option in the survey used by a greater share of residents on weekends than on weekdays.",
    p: "Which choice most effectively uses data from the table to support the planner's claim?",
    c: [
      "Bicycle use rose from 12% on weekdays to 19% on weekends, while bus and train use both fell.",
      "Bus use was 38% on weekdays, the highest share of any option.",
      "Train use fell from 27% on weekdays to 9% on weekends.",
      "Bicycle use was 19% on weekends, less than bus use on weekdays.",
    ],
    a: "A",
    e: "\"The only option\" needs two facts: bicycles rose, and the others did not. Only the first choice gives both.",
  },
  {
    id: "ps-r-17",
    skill: "inferences",
    d: "easy",
    s: "Every plant in Rosa's garden that was placed in full sun grew taller than the same kind of plant placed in shade. Rosa gave all the plants the same amount of water. Rosa's results suggest that ______",
    p: STEM.complete,
    c: [
      "sunlight helped these plants grow taller.",
      "watering had no effect on plant growth.",
      "the plants in shade received more water.",
      "all plants grow best in shade.",
    ],
    a: "A",
    e: "Water was held equal, and sunlight was the difference between the taller and shorter plants.",
  },
  {
    id: "ps-r-18",
    skill: "inferences",
    d: "medium",
    s: "In a survey of commuters in the city of Belden, most riders said they would take the bus more often if buses came more frequently. After the city doubled the number of buses on two routes, ridership on those routes rose sharply, while ridership on routes with no added buses stayed about the same. This suggests that ______",
    p: STEM.complete,
    c: [
      "how often buses came was a major factor in commuters' decisions about whether to ride.",
      "commuters in Belden preferred driving to riding the bus under all conditions.",
      "the routes with added buses were already the city's busiest routes.",
      "bus fares affected ridership more than the number of buses did.",
    ],
    a: "A",
    e: "Only the routes that got more buses gained riders, which matches what commuters said in the survey. Fares are never mentioned.",
  },
  {
    id: "ps-r-19",
    skill: "inferences",
    d: "hard",
    s: "Archaeologists excavating an ancient settlement found tools made of a stone that occurs naturally only in mountains about 300 kilometers away. No waste chips from shaping that stone were found at the settlement, though waste from local stone was abundant. The archaeologists concluded that ______",
    p: STEM.complete,
    c: [
      "the tools were most likely made elsewhere and brought to the settlement as finished objects.",
      "the settlement's residents shaped the tools from the distant stone on site.",
      "the distant stone was easier to work than the local stone.",
      "the settlement was founded by people from the mountains.",
    ],
    a: "C",
    e: "Shaping stone leaves waste chips. Plenty of local-stone waste but none from the distant stone means the distant-stone tools arrived already made.",
  },

  // Expression of Ideas
  {
    id: "ps-r-20",
    skill: "transitions",
    d: "easy",
    s: "The coastal town receives very little rain in summer. ______ its reservoirs are usually at their lowest in early autumn.",
    p: STEM.transition,
    c: ["As a result,", "However,", "For example,", "Similarly,"],
    a: "B",
    e: "Low reservoirs follow from a dry summer: a cause and its effect, so \"As a result.\"",
  },
  {
    id: "ps-r-21",
    skill: "transitions",
    d: "medium",
    s: "Early bicycles had a very large front wheel and a small rear wheel, which made them fast but hard to mount. ______ later designs used two wheels of equal size and a chain drive, making bicycles safer for ordinary riders.",
    p: STEM.transition,
    c: ["In contrast,", "Therefore,", "For instance,", "In addition,"],
    a: "A",
    e: "The second sentence describes a design unlike the first, so the relationship is contrast.",
  },
  {
    id: "ps-r-22",
    skill: "transitions",
    d: "medium",
    s: "Chef Laila Osei's cookbook includes recipes from twelve countries. ______ it features a Ghanaian groundnut stew, a Peruvian corn soup, and a Korean rice dish.",
    p: STEM.transition,
    c: ["For example,", "Nevertheless,", "In contrast,", "Consequently,"],
    a: "D",
    e: "The three dishes are instances of the recipes from many countries named in the first sentence.",
  },
  {
    id: "ps-r-23",
    skill: "transitions",
    d: "hard",
    s: "Critics praised the film's striking photography. ______ many viewers found its slow pace hard to sit through, and it earned little at the box office.",
    p: STEM.transition,
    c: ["Still,", "Thus,", "Likewise,", "In other words,"],
    a: "C",
    e: "Praise is followed by a drawback that cuts against it, which calls for a concession: \"Still.\" \"Thus\" would wrongly make the praise the cause of the poor reception.",
  },
  {
    id: "ps-r-24",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "The Lindqvist Tower is a skyscraper in the city of Varn.",
      "It was completed in 1988.",
      "It is 212 meters tall.",
      "The Marlow Building, also in Varn, is 187 meters tall.",
      "The Marlow Building was completed in 1975.",
    ),
    p: goal("compare the heights of the two buildings."),
    c: [
      "At 212 meters, the Lindqvist Tower is taller than the 187-meter Marlow Building.",
      "The Lindqvist Tower and the Marlow Building are both in the city of Varn.",
      "The Marlow Building was completed in 1975, thirteen years before the Lindqvist Tower.",
      "The Lindqvist Tower, completed in 1988, is a skyscraper in Varn.",
    ],
    a: "C",
    e: "Only the first choice gives both heights and compares them. The others compare location or dates, or describe one building.",
  },
  {
    id: "ps-r-25",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "Monarch butterflies migrate each year between Canada and central Mexico.",
      "Some travel more than 4,000 kilometers.",
      "No single butterfly completes the round trip.",
      "The journey north takes three to four generations.",
    ),
    p: goal("emphasize that the migration spans more than one generation."),
    c: [
      "Because the journey north takes three to four generations, no single monarch completes the round-trip migration.",
      "Monarch butterflies migrate each year between Canada and central Mexico.",
      "Some monarch butterflies travel more than 4,000 kilometers.",
      "Monarchs migrate between Canada and Mexico, a journey of more than 4,000 kilometers.",
    ],
    a: "B",
    e: "The goal is the generational point, and only the first choice mentions generations at all.",
  },

  // Standard English Conventions
  {
    id: "ps-r-26",
    skill: "boundaries",
    d: "easy",
    s: "The hikers reached the summit just after ______ they stayed only long enough to take photographs before the clouds rolled in.",
    p: STEM.sec,
    c: ["noon;", "noon,", "noon", "noon and,"],
    a: "D",
    e: "Two independent clauses meet here. A semicolon can join them; a comma alone makes a comma splice, and no punctuation makes a run-on.",
  },
  {
    id: "ps-r-27",
    skill: "boundaries",
    d: "medium",
    s: "Researcher Paulo Ribeiro studies an unusual ______ a moss that can survive being completely dried out for decades.",
    p: STEM.sec,
    c: ["plant:", "plant;", "plant", "plant. A"],
    a: "A",
    e: "A colon can introduce the phrase that explains \"an unusual plant.\" A semicolon needs a full clause after it, and \"A moss that can survive...\" on its own is a fragment.",
  },
  {
    id: "ps-r-28",
    skill: "boundaries",
    d: "hard",
    s: "The novel's narrator, a retired ship ______ recalls her years at sea with a mix of fondness and regret.",
    p: STEM.sec,
    c: ["captain,", "captain", "captain;", "captain--"],
    a: "B",
    e: "The phrase \"a retired ship captain\" opens with a comma, so it must close with one. A dash would mismatch the opening comma, and a semicolon would cut the subject off from its verb.",
  },
  {
    id: "ps-r-29",
    skill: "boundaries",
    d: "medium",
    s: "The festival includes performances by musicians from three ______ Lagos, Nigeria; Recife, Brazil; and Oslo, Norway.",
    p: STEM.sec,
    c: ["cities:", "cities;", "cities,", "cities"],
    a: "D",
    e: "A colon introduces a list after a complete clause. A comma would blur into the commas inside the list, and a semicolon needs a clause on both sides.",
  },
  {
    id: "ps-r-30",
    skill: "form-structure-sense",
    d: "medium",
    s: "Walking through the old market, ______",
    p: STEM.sec,
    c: [
      "Omar noticed the smell of spices drifting from a nearby stall.",
      "the smell of spices drifting from a nearby stall caught Omar's attention.",
      "a nearby stall's spices were noticed by Omar.",
      "there was a smell of spices from a nearby stall that Omar noticed.",
    ],
    a: "C",
    e: "The opening phrase describes whoever was walking, so the subject right after the comma must be Omar. Otherwise the smell, or the spices, would be doing the walking.",
  },
  {
    id: "ps-r-31",
    skill: "form-structure-sense",
    d: "easy",
    s: "Last spring, the city council ______ a plan to plant 5,000 trees along its main roads.",
    p: STEM.sec,
    c: ["approved", "approves", "will approve", "has been approving"],
    a: "A",
    e: "\"Last spring\" places the action in the finished past, which calls for the simple past tense.",
  },
  {
    id: "ps-r-32",
    skill: "form-structure-sense",
    d: "hard",
    s: "When the orchestra finished ______ final piece, the audience rose to applaud.",
    p: STEM.sec,
    c: ["its", "their", "it's", "they're"],
    a: "B",
    e: "\"The orchestra\" is a single group here, so the possessive pronoun is \"its.\" \"It's\" means \"it is.\"",
  },
  {
    id: "ps-r-33",
    skill: "subject-verb",
    d: "easy",
    s: "The collection of rare stamps, which includes items from over forty countries, ______ on display at the city museum.",
    p: STEM.sec,
    c: ["is", "are", "were", "have been"],
    a: "D",
    e: "The subject is \"collection,\" which is singular; \"stamps\" is inside a prepositional phrase. A singular subject takes \"is.\"",
  },
  {
    id: "ps-r-34",
    skill: "subject-verb",
    d: "medium",
    s: "Neither the players nor the coach ______ expecting the storm to arrive so quickly.",
    p: STEM.sec,
    c: ["was", "were", "are", "have been"],
    a: "C",
    e: "With \"neither ... nor,\" the verb agrees with the nearer subject, \"the coach,\" which is singular. The past-tense story calls for \"was.\"",
  },
];

export const PSAT_QUESTIONS = [...MATH, ...RW].map((s) => q(s, undefined, "psat"));
