/**
 * Practice Test 1.
 *
 * Written for Pathforge to the digital SAT's published specification: the
 * same question types, stems, domain mix and difficulty spread as the real
 * test, in the order the real modules present them. Nothing here is College
 * Board material. Passages about named researchers describe invented people
 * and studies unless they concern well-documented history.
 *
 * Module 1 of each section is mixed in difficulty. Module 2 here is the
 * harder route, served to students who do well on Module 1; the easier route
 * is assembled from the question bank at sitting time (see `forms.ts`).
 */

import { STEM, goal, notes, q, texts, type QSpec } from "./author";

const F = "pt1";
const build = (specs: QSpec[]) => specs.map((s) => q(s, F));

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 1                                       */
/* ------------------------------------------------------------------ */

export const PT1_RW1 = build([
  {
    id: "pt1-rw1-01",
    skill: "words-in-context",
    d: "easy",
    s: "Although the desert lily spends most of the year as a bulb buried deep beneath the sand, it is far from ______: within days of a heavy rain, it can send up a stalk and burst into bloom.",
    p: STEM.wic,
    c: ["unresponsive", "colorful", "common", "delicate"],
    a: "B",
    e: "The colon introduces evidence that the plant reacts quickly to rain, so the blank must describe what it is 'far from': not reacting. 'Unresponsive' fits. Nothing in the text concerns the plant's color, how common it is, or how delicate it is.",
  },
  {
    id: "pt1-rw1-02",
    skill: "words-in-context",
    d: "medium",
    s: "In her study of urban gardens, sociologist Priya Nandakumar found that community plots did more than supply fresh produce; they also ______ social ties among neighbors who had previously had little contact, as gardeners traded tools, advice, and surplus vegetables.",
    p: STEM.wic,
    c: ["fostered", "replaced", "disguised", "predicted"],
    a: "C",
    e: "Neighbors who had little contact began trading tools and advice, so the gardens encouraged, or fostered, new ties. The gardens did not replace or hide relationships, and 'predicted' does not describe something the gardens did.",
  },
  {
    id: "pt1-rw1-03",
    skill: "words-in-context",
    d: "medium",
    s: "Because the fossil record for early flowering plants is so ______, paleobotanists have often relied on molecular data to estimate when the group first appeared: well-preserved specimens from the relevant period are exceedingly rare.",
    p: STEM.wic,
    c: ["fragmentary", "contentious", "extensive", "recent"],
    a: "D",
    e: "The text explains that well-preserved specimens are 'exceedingly rare,' which is why researchers turn to other data. A record with large gaps is 'fragmentary.' 'Extensive' says the opposite, and nothing suggests the record is disputed or new.",
  },
  {
    id: "pt1-rw1-04",
    skill: "words-in-context",
    d: "hard",
    s: "Though the novelist's public statements about her work were often ______, her private letters reveal a writer who was candid, even blunt, about her ambitions and her frustrations with publishers.",
    p: STEM.wic,
    c: ["guarded", "effusive", "mundane", "prolific"],
    a: "D",
    e: "'Though' sets the public statements against letters that were 'candid, even blunt,' so the blank needs the opposite of candid: 'guarded.' 'Effusive' (gushing) is not the opposite of candid, and 'mundane' and 'prolific' do not create the contrast.",
  },
  {
    id: "pt1-rw1-05",
    skill: "text-structure",
    d: "medium",
    s: "For decades, astronomers assumed that the faint reddish glow surrounding some young stars came from dust grains reflecting starlight. In 2019, however, a team led by Tomas Ibarra noted that the glow's color did not match what reflected light should produce. Using a spectrograph, the team showed that much of the glow was emitted by the dust itself as it was heated, a finding that has led researchers to revise their estimates of how much dust young stellar systems contain.",
    p: STEM.purpose,
    c: [
      "To describe a finding that challenged a long-held assumption about a phenomenon and to note one consequence of that finding",
      "To explain why astronomers prefer spectrographs to other instruments when studying young stars",
      "To argue that estimates of the amount of dust in young stellar systems are unreliable and should be abandoned",
      "To compare two competing methods for measuring the brightness of young stars",
    ],
    a: "A",
    e: "The text presents an old assumption, a finding that overturned it, and the result (revised dust estimates). It never compares instruments or methods, and it says the estimates were revised, not abandoned.",
  },
  {
    id: "pt1-rw1-06",
    skill: "text-structure",
    d: "medium",
    s: "Many economists have assumed that workers who switch jobs frequently earn less over their careers than those who stay with a single employer. [u]A 2021 analysis of payroll records by economist Hana Sorensen complicates this picture.[/u] Sorensen found that for workers in the first decade of their careers, moderate job switching was associated with higher lifetime earnings, although very frequent switching was not.",
    p: STEM.underlined,
    c: [
      "It introduces a study whose findings qualify the assumption presented in the previous sentence.",
      "It provides an example that supports the assumption presented in the previous sentence.",
      "It explains the method Sorensen used to collect the data described in the final sentence.",
      "It summarizes a consensus that the rest of the text goes on to defend.",
    ],
    a: "C",
    e: "The underlined sentence announces that Sorensen's analysis 'complicates' the economists' assumption, and the final sentence gives the complicating result. It does not support the assumption, describe a method, or state a consensus.",
  },
  {
    id: "pt1-rw1-07",
    skill: "text-structure",
    d: "hard",
    s: "The following text is from a short story. Marguerite has returned to her family's farm after several years in the city.\n\nThe kitchen was smaller than she remembered, though nothing in it had been moved. The same blue pitcher stood on the sill; the same calendar, three years out of date, hung by the door. Marguerite set down her bag and waited for the room to welcome her. It did not. It went on being exactly itself, indifferent to her absence and to her return, and she understood, with a small shock, that the place she had been homesick for no longer existed anywhere but in her memory.",
    p: STEM.structure,
    c: [
      "It describes a setting in detail and then presents a realization that the setting prompts in a character.",
      "It recounts a character's journey and then explains her reasons for undertaking it.",
      "It introduces a conflict between two characters and then shows how that conflict is resolved.",
      "It presents a character's memory of a place and then confirms that the memory was accurate.",
    ],
    a: "B",
    e: "The first half describes the unchanged kitchen; the second half gives Marguerite's realization that the home she missed exists only in memory. There is no journey narrative, no second character, and the realization undercuts rather than confirms her memory.",
  },
  {
    id: "pt1-rw1-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Some linguists contend that the spread of text messaging has degraded young people's writing skills. They point to abbreviations and missing punctuation in students' messages as evidence that students can no longer distinguish casual from formal registers of language.",
      "Linguist Adaeze Okafor studied writing samples from 600 secondary school students and found that students who texted heavily used abbreviations in their messages but almost never in their school essays. Okafor argues that switching between registers is itself a sophisticated skill--one that frequent texters may actually practice more than their peers do.",
    ),
    p: "Based on the texts, how would Okafor (Text 2) most likely respond to the linguists' claim in Text 1?",
    c: [
      "By arguing that the evidence the linguists cite does not show that students cannot distinguish between registers, since heavy texters adjust their writing to the context",
      "By agreeing that texting has harmed students' writing but arguing that the harm is limited to punctuation",
      "By arguing that abbreviations are more common in school essays than the linguists assume",
      "By suggesting that the linguists' claim is accurate for students who text frequently but not for students who rarely text",
    ],
    a: "D",
    e: "Okafor found that heavy texters leave abbreviations out of formal essays, which is evidence that they do distinguish registers. Her findings contradict, rather than partly accept, the claim, and they show abbreviations are rare in essays.",
  },
  {
    id: "pt1-rw1-09",
    skill: "central-ideas",
    d: "easy",
    s: "Before mechanical refrigeration, ice cut from frozen lakes in New England was shipped as far as India and the Caribbean. Workers harvested the blocks in winter and packed them in sawdust, which insulated the ice so well that much of it survived voyages lasting months. For much of the nineteenth century, this trade turned ice--once a luxury available only near cold climates--into a common commodity in warm ports around the world.",
    p: STEM.mainIdea,
    c: [
      "A nineteenth-century trade used simple insulation to ship ice over long distances, making ice widely available in warm places.",
      "Mechanical refrigeration was invented because shipping ice was too expensive.",
      "Sawdust was one of the most valuable exports of nineteenth-century New England.",
      "Most of the ice shipped from New England melted before it reached its destination.",
    ],
    a: "C",
    e: "The text describes how insulated New England ice reached distant warm ports and became common there. It gives no reason for refrigeration's invention, treats sawdust only as packing, and says much of the ice survived.",
  },
  {
    id: "pt1-rw1-10",
    skill: "central-ideas",
    d: "medium",
    s: "The following text is from a novel. Theo, a young pianist, is practicing before a competition.\n\nTheo played the opening bars again, and again they came out correct and lifeless. Every note was where it belonged; his teacher could not have faulted a single one. Yet he felt like a man reciting a poem in a language he did not speak, shaping the sounds perfectly and understanding none of them. He lifted his hands from the keys and sat for a long while in the silent room.",
    p: STEM.mainIdea,
    c: [
      "Theo is troubled that his technically accurate playing lacks feeling or meaning.",
      "Theo worries that his teacher will criticize the mistakes in his playing.",
      "Theo regrets that he never learned to speak a second language.",
      "Theo decides that he will withdraw from the competition.",
    ],
    a: "C",
    e: "The notes are 'correct and lifeless,' and the comparison to reciting a poem without understanding it shows Theo's unease that precision is not enough. The text says his teacher could not fault a note, the language is only a comparison, and he makes no decision.",
  },
  {
    id: "pt1-rw1-11",
    skill: "command-evidence",
    d: "medium",
    s: "Marine biologist Selin Kaya hypothesizes that cleaner wrasses--small fish that remove parasites from larger 'client' fish--adjust their behavior depending on whether other potential clients are watching. Specifically, Kaya proposes that wrasses are less likely to cheat by biting their clients' healthy tissue when other fish are nearby.",
    p: "Which finding, if true, would most directly support Kaya's hypothesis?",
    c: [
      "Wrasses bit their clients' healthy tissue significantly less often when other fish were observing than when no other fish were present.",
      "Wrasses removed more parasites from large clients than from small clients.",
      "Clients that had been bitten by wrasses sometimes chased the wrasses away.",
      "Wrasses were observed cleaning clients at all times of the day.",
    ],
    a: "B",
    e: "The hypothesis links cheating to the presence of onlookers, so the supporting finding must compare biting with and without observers. The other choices describe wrasse behavior that has nothing to do with being watched.",
  },
  {
    id: "pt1-rw1-12",
    skill: "command-evidence",
    d: "hard",
    s: "Some historians have argued that the fourteenth-century decline of the trading city of Caraval resulted primarily from a prolonged drought that ruined local agriculture. Archaeologist Mirela Vasquez disputes this claim, arguing instead that the city declined because shifting trade routes diverted merchants, and their wealth, elsewhere.",
    p: "Which finding, if true, would most directly weaken Vasquez's argument?",
    c: [
      "Sediment cores show that rainfall in the region fell sharply for several decades just before Caraval's population began to decline, while tax records show that trade through the city remained steady during that period.",
      "Documents from a rival city describe an increase in merchant traffic during the fourteenth century.",
      "Excavations reveal that Caraval's markets contained goods from many distant regions.",
      "Several other cities in the region also lost population during the fifteenth century.",
    ],
    a: "A",
    e: "Vasquez blames lost trade. Evidence that trade held steady while a drought struck just before the decline undercuts her explanation and supports the drought account. Rising traffic in a rival city would, if anything, support her.",
  },
  {
    id: "pt1-rw1-13",
    skill: "quantitative-evidence",
    d: "medium",
    s: "A city arts council reported that attendance at some of the city's museums rose substantially between 2019 and 2023, while attendance at others remained roughly the same or fell slightly. For example, ______",
    fig: {
      kind: "table",
      title: "Average Daily Visitors at Four City Museums",
      head: ["Museum", "2019", "2023"],
      rows: [
        ["Harbor Museum", "1,240", "1,610"],
        ["Science Hall", "2,050", "1,980"],
        ["Folk Art Center", "460", "720"],
        ["City Gallery", "890", "905"],
      ],
      rowHeaders: true,
    },
    p: STEM.tableExample,
    c: [
      "the Folk Art Center's average daily visitors rose from 460 to 720, while the Science Hall's fell slightly, from 2,050 to 1,980.",
      "the Harbor Museum had more average daily visitors than the City Gallery did in both 2019 and 2023.",
      "the Science Hall had the most average daily visitors of the four museums in 2019.",
      "the City Gallery's average daily visitors rose from 890 to 905.",
    ],
    a: "D",
    e: "The example must show both halves of the claim: a substantial rise at one museum and a flat or slightly lower figure at another. Only the Folk Art Center and Science Hall pairing does both. The City Gallery figure alone shows only the 'roughly the same' half.",
  },
  {
    id: "pt1-rw1-14",
    skill: "quantitative-evidence",
    d: "hard",
    s: "Ecologist Ruth Adeyemi grew seedlings of two tree species under three light conditions and recorded how many survived for 60 days. She concluded that Species Y is better suited than Species X to shaded forest understories, where little direct sunlight reaches the ground.",
    fig: {
      kind: "bar",
      title: "Seedling Survival After 60 Days",
      yLabel: "Seedlings surviving (%)",
      categories: ["Full sun", "Partial shade", "Full shade"],
      series: [
        { name: "Species X", values: [82, 64, 30] },
        { name: "Species Y", values: [45, 70, 68] },
      ],
      y: [0, 100, 20],
    },
    p: "Which choice best describes data from the graph that support Adeyemi's conclusion?",
    c: [
      "In full shade, 68% of Species Y seedlings survived, compared with 30% of Species X seedlings.",
      "In full sun, 82% of Species X seedlings survived, compared with 45% of Species Y seedlings.",
      "Species X had its highest survival rate in full sun.",
      "In partial shade, the survival rates of the two species differed by less than 10 percentage points.",
    ],
    a: "C",
    e: "The conclusion concerns shaded conditions, so the relevant comparison is full shade, where Species Y survived at more than twice the rate of Species X. The full-sun figures are accurate but describe the wrong condition, and a small gap in partial shade does not show Y is better suited.",
  },
  {
    id: "pt1-rw1-15",
    skill: "inferences",
    d: "medium",
    s: "Fireflies of many species flash in species-specific patterns that allow males and females to recognize one another. Females of some *Photuris* species, however, can mimic the flash patterns of other species. When males of those species approach, expecting to find a mate, the *Photuris* females capture and eat them. Researchers have found that the females acquire, from these males, defensive chemicals that deter spiders and birds--chemicals that *Photuris* fireflies cannot produce on their own. This suggests that ______",
    p: STEM.complete,
    c: [
      "the mimicry of Photuris females may provide them with a benefit beyond nutrition.",
      "Photuris males are unable to recognize the flash patterns of their own species.",
      "the defensive chemicals produced by other firefly species have no effect on predators.",
      "most firefly species are unable to produce defensive chemicals.",
    ],
    a: "A",
    e: "The females gain protective chemicals they cannot make themselves, so luring other males yields protection as well as food. The text says the chemicals deter predators and says nothing about Photuris males or most species.",
  },
  {
    id: "pt1-rw1-16",
    skill: "boundaries",
    d: "easy",
    s: "In 1953, Jonas Salk announced that he had developed a vaccine against ______ two years later, after extensive field trials, the vaccine was declared safe and effective.",
    p: STEM.sec,
    c: ["polio; two", "polio, two", "polio two", "polio, and, two"],
    a: "B",
    e: "Both halves are independent clauses, so they need a semicolon (or a period). A comma alone creates a comma splice, no punctuation creates a run-on, and the comma after 'and' is unnecessary.",
  },
  {
    id: "pt1-rw1-17",
    skill: "boundaries",
    d: "medium",
    s: "The committee's report identified three priorities for the coming year: expanding the library's digital archive, which currently holds more than 40,000 ______ restoring the reading room's original ceiling; and extending weekend hours.",
    p: STEM.sec,
    c: ["items;", "items,", "items", "items:"],
    a: "D",
    e: "The list's items contain internal commas, and the second and third items are already separated by a semicolon, so the first item must end with a semicolon as well.",
  },
  {
    id: "pt1-rw1-18",
    skill: "boundaries",
    d: "easy",
    s: "Chemist Rosalind ______ whose X-ray images of DNA helped reveal the molecule's double-helix structure, died in 1958 at the age of 37.",
    p: STEM.sec,
    c: ["Franklin,", "Franklin", "Franklin;", "Franklin--"],
    a: "A",
    e: "'Whose X-ray images...structure' is a nonessential clause that the text closes with a comma, so it must open with a comma too. A dash would not match the closing comma.",
  },
  {
    id: "pt1-rw1-19",
    skill: "boundaries",
    d: "hard",
    s: "The novel's final chapter--in which the narrator, now elderly, returns to the village where she was ______ recasts every event that came before it.",
    p: STEM.sec,
    c: ["born--", "born,", "born", "born;"],
    a: "C",
    e: "The interruption opens with a dash after 'chapter,' so it must close with a dash before the verb 'recasts.' A comma would mismatch, and leaving it open or using a semicolon breaks the sentence.",
  },
  {
    id: "pt1-rw1-20",
    skill: "subject-verb",
    d: "easy",
    s: "The collection of rare maps donated to the university library last year ______ several charts drawn by sixteenth-century Portuguese navigators.",
    p: STEM.sec,
    c: ["includes", "include", "are including", "have included"],
    a: "B",
    e: "The subject is the singular noun 'collection,' not 'maps,' so the verb must be singular: 'includes.'",
  },
  {
    id: "pt1-rw1-21",
    skill: "form-structure-sense",
    d: "medium",
    s: "Honeybees communicate the location of food through the 'waggle dance,' a series of movements that encodes both the direction and the distance of a food source. The dance is remarkably precise: by watching ______ closely, other bees can locate flowers more than a kilometer away.",
    p: STEM.sec,
    c: ["it", "them", "one", "these"],
    a: "D",
    e: "The pronoun refers to 'the dance,' a singular noun, so 'it' is correct. 'Them' and 'these' are plural, and 'one' does not refer back to a specific dance.",
  },
  {
    id: "pt1-rw1-22",
    skill: "form-structure-sense",
    d: "hard",
    s: "Having spent nearly a decade photographing the migration of monarch butterflies across North America, ______",
    p: STEM.sec,
    c: [
      "photographer Lucia Mendes has collected more than 200 of her images in a new book.",
      "the new book by photographer Lucia Mendes collects more than 200 of her images.",
      "more than 200 images have been collected by photographer Lucia Mendes in a new book.",
      "Lucia Mendes's new book collects more than 200 of the photographer's images.",
    ],
    a: "A",
    e: "The opening phrase describes someone who spent a decade photographing, so the subject that follows it must be that person: Lucia Mendes. The other choices make the book or the images the ones who did the photographing.",
  },
  {
    id: "pt1-rw1-23",
    skill: "transitions",
    d: "easy",
    s: "Octopuses can change the color of their skin in a fraction of a second. ______ they can alter its texture, raising small bumps to mimic the surface of rocks or coral.",
    p: STEM.transition,
    c: ["Moreover,", "However,", "Instead,", "For instance,"],
    a: "C",
    e: "The second sentence adds another camouflage ability to the first, so an additive transition fits. It does not contrast with the first sentence or give an example of it.",
  },
  {
    id: "pt1-rw1-24",
    skill: "transitions",
    d: "medium",
    s: "For centuries, the city's canals served as its main thoroughfares, carrying goods and people from one district to another. By the middle of the twentieth century, ______ many of the canals had been filled in and paved over to make room for automobile traffic.",
    p: STEM.transition,
    c: ["however,", "similarly,", "for example,", "in addition,"],
    a: "B",
    e: "The second sentence reverses the first: the canals that once carried the city's traffic were paved over. That change calls for a contrasting transition.",
  },
  {
    id: "pt1-rw1-25",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "The okapi is a mammal native to the rainforests of the Democratic Republic of the Congo.",
      "Its legs have horizontal black-and-white stripes resembling those of a zebra.",
      "Despite this resemblance, the okapi's closest living relative is the giraffe.",
      "Like the giraffe, the okapi has a long, flexible tongue that it uses to strip leaves from branches.",
    ),
    p: goal("emphasize a similarity between the okapi and the giraffe."),
    c: [
      "Like the giraffe, its closest living relative, the okapi uses a long, flexible tongue to strip leaves from branches.",
      "The okapi, which is native to the Democratic Republic of the Congo, has striped legs.",
      "Although the okapi's legs resemble a zebra's, the okapi's closest living relative is not the zebra.",
      "The okapi is a mammal that lives in rainforests.",
    ],
    a: "D",
    e: "Only the first choice names something the okapi and the giraffe share: the tongue they use to strip leaves. The others describe the okapi alone or its resemblance to the zebra.",
  },
  {
    id: "pt1-rw1-26",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "In 1911, Marie Curie became the first person to win Nobel Prizes in two different sciences.",
      "Her first Nobel Prize, in physics (1903), was shared with Pierre Curie and Henri Becquerel for research on radioactivity.",
      "Her second Nobel Prize, in chemistry (1911), was awarded to her alone for her discovery of the elements polonium and radium.",
    ),
    p: goal("emphasize a difference between Curie's two Nobel Prizes."),
    c: [
      "While Curie shared her 1903 Nobel Prize in physics with two other scientists, she received her 1911 Nobel Prize in chemistry alone.",
      "Curie won Nobel Prizes in both 1903 and 1911.",
      "In 1911, Curie became the first person to win Nobel Prizes in two different sciences.",
      "Curie's research on radioactivity was recognized with a Nobel Prize.",
    ],
    a: "A",
    e: "The first choice contrasts the two prizes directly: one shared, one won alone. The others state facts about the prizes without setting them against each other.",
  },
  {
    id: "pt1-rw1-27",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "A team led by nutrition scientist Imani Okoro studied whether the color of a plate affects how much food people serve themselves.",
      "Participants served themselves pasta with either a white sauce or a red sauce.",
      "Each participant used either a white plate or a red plate.",
      "Participants whose sauce matched the color of their plate served themselves about 20% more pasta than those whose sauce contrasted with it.",
    ),
    p: goal("explain the purpose of Okoro's study."),
    c: [
      "Okoro's team investigated whether the color of a plate influences how much food people serve themselves.",
      "Participants whose sauce matched their plate served themselves about 20% more pasta than those whose sauce did not.",
      "Participants in Okoro's study used either a white plate or a red plate and served themselves pasta.",
      "The pasta in Okoro's study came with either a white sauce or a red sauce.",
    ],
    a: "B",
    e: "The purpose is the question the study set out to answer, which only the first choice states. The second choice gives the result, and the last two describe the method.",
  },
]);

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 2 (harder)                              */
/* ------------------------------------------------------------------ */

export const PT1_RW2 = build([
  {
    id: "pt1-rw2-01",
    skill: "words-in-context",
    d: "medium",
    s: "Critics who expected the director's second film to be as ______ as her acclaimed debut were surprised: where the debut was sprawling and ornate, the new film is spare, with minimal dialogue and a single setting.",
    p: STEM.wic,
    c: ["lavish", "restrained", "derivative", "lighthearted"],
    a: "A",
    e: "Critics expected the new film to resemble the debut, which was 'sprawling and ornate.' 'Lavish' captures that. 'Restrained' describes the new film, which is what surprised them.",
  },
  {
    id: "pt1-rw2-02",
    skill: "words-in-context",
    d: "hard",
    s: "The treaty's provisions were ______ at first, with each side interpreting the key clauses to its own advantage; only a 1932 amendment specifying the boundaries in question ended the dispute.",
    p: STEM.wic,
    c: ["equivocal", "unanimous", "punitive", "perfunctory"],
    a: "C",
    e: "Each side could read the clauses its own way until an amendment specified the terms, so the provisions were open to more than one interpretation: 'equivocal.' Nothing suggests they were agreed by all, harsh, or carelessly done.",
  },
  {
    id: "pt1-rw2-03",
    skill: "words-in-context",
    d: "hard",
    s: "Marine ecologist Johan Lindqvist cautions that the recovery of the bay's oyster population, though encouraging, remains ______: a single season of unusually warm water or heavy runoff could undo a decade of gains.",
    p: STEM.wic,
    c: ["precarious", "inevitable", "exemplary", "negligible"],
    a: "B",
    e: "If one bad season could erase the gains, the recovery is insecure: 'precarious.' 'Inevitable' contradicts the warning, and 'negligible' contradicts 'encouraging.'",
  },
  {
    id: "pt1-rw2-04",
    skill: "words-in-context",
    d: "hard",
    s: "Historian Wen Liu's account of the 1912 mill strike does not ______ the workers' grievances; rather, it treats their complaints as serious and well founded while also examining the financial pressures the mill's owners faced.",
    p: STEM.wic,
    c: ["discount", "substantiate", "anticipate", "publicize"],
    a: "D",
    e: "'Rather' signals that the account does the opposite of the blank: it takes the grievances seriously. So the blank means to dismiss or 'discount' them. The account does substantiate the grievances, so saying it does not would contradict the text.",
  },
  {
    id: "pt1-rw2-05",
    skill: "text-structure",
    d: "medium",
    s: "The following text is from a novel. Isaura, a botanist, has arrived on a remote island to catalog its plants.\n\nIsaura had expected the island's flora to be meager--a few salt-tolerant grasses, perhaps, and some stunted shrubs. Instead, the interior valleys were choked with ferns taller than she was, and orchids clung to every trunk. She filled her first notebook in two days. By the end of the week she had stopped trying to name everything and had begun, simply, to look.",
    p: STEM.purpose,
    c: [
      "To depict a character whose expectations are overturned and whose approach changes in response",
      "To explain the scientific reasons for the island's unusually rich plant life",
      "To describe the physical difficulty of traveling through dense vegetation",
      "To suggest that a character regrets her decision to visit the island",
    ],
    a: "B",
    e: "Isaura expects sparse plants, finds abundance, and shifts from naming everything to simply looking. The text offers no scientific explanation, no account of hardship, and no regret.",
  },
  {
    id: "pt1-rw2-06",
    skill: "text-structure",
    d: "hard",
    s: "Economists have long compared the cost of living across countries by pricing a standard basket of goods in each one. [u]Such comparisons can mislead, however, when the basket includes items that are consumed very differently from place to place.[/u] Rice, for instance, is a daily staple in some countries and an occasional side dish in others, so a rise in its price affects households in those places very unequally.",
    p: STEM.underlined,
    c: [
      "It identifies a limitation of the method described in the first sentence, which the final sentence then illustrates.",
      "It proposes an alternative to the method described in the first sentence.",
      "It presents evidence that the method described in the first sentence is more accurate than critics claim.",
      "It summarizes the findings of a study that the final sentence then challenges.",
    ],
    a: "A",
    e: "The underlined sentence names a weakness of basket comparisons, and the rice example shows that weakness in action. No alternative method, defense, or study appears.",
  },
  {
    id: "pt1-rw2-07",
    skill: "text-structure",
    d: "medium",
    s: "In the 1950s, many biologists assumed that the genes of complex organisms were laid out like those of bacteria, in continuous stretches of DNA. That assumption was overturned in 1977, when two research groups independently discovered that many genes are interrupted by long sequences that are removed before the gene's instructions are used. These sequences, later named introns, were at first regarded as genetic clutter. Researchers now know that introns can help regulate when, and how strongly, genes are expressed.",
    p: STEM.structure,
    c: [
      "It describes an early belief about genes, presents a discovery that contradicted it, and traces how understanding of the newly discovered feature has changed.",
      "It explains a laboratory method and then describes the results that method produced.",
      "It compares the genes of bacteria with those of complex organisms and concludes that they are identical.",
      "It presents a hypothesis about introns and then describes evidence that confirmed it.",
    ],
    a: "C",
    e: "The text moves from the 1950s assumption, to the 1977 discovery that disproved it, to the shift from seeing introns as clutter to seeing them as regulators. It describes no method and concludes that the genes differ.",
  },
  {
    id: "pt1-rw2-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Many archaeologists interpret the large stone enclosures scattered across the grasslands of central Asia as fortifications. They point to the enclosures' thick walls and hilltop locations and conclude that the enclosures were built by communities facing frequent raids.",
      "Archaeologist Batu Erdene notes that most of the enclosures lack gates that could have been sealed, and few show signs of attack, such as arrowheads or layers of burned material. Erdene contends that the enclosures more likely served as seasonal gathering places for livestock trading, with their hilltop locations making them visible from far across the plains.",
    ),
    p: "Based on the texts, how would Erdene (Text 2) most likely respond to the interpretation described in Text 1?",
    c: [
      "By arguing that a feature taken as evidence of defense has another explanation, and that signs one would expect from defensive sites are largely absent",
      "By agreeing that the enclosures were fortifications but arguing that they were rarely attacked",
      "By questioning whether most of the enclosures were actually built on hilltops",
      "By claiming that livestock trading was a frequent cause of the raids the archaeologists describe",
    ],
    a: "D",
    e: "Erdene reinterprets the hilltop locations as a matter of visibility and points out that sealable gates and signs of attack are missing. Erdene rejects the fortification reading rather than accepting it, and accepts that the sites are on hilltops.",
  },
  {
    id: "pt1-rw2-09",
    skill: "central-ideas",
    d: "medium",
    s: "Plants lack nervous systems, yet some respond to touch with surprising speed: the leaflets of the sensitive plant, *Mimosa pudica*, fold within seconds of being brushed. Plant physiologist Aiko Tanabe has studied how. When the plant is touched, an electrical signal travels through its stem and triggers specialized cells at the base of each leaflet to release water. The cells shrink, and the leaflet collapses. Tanabe argues that electrical signaling, long associated with animal nerves, may be far more widespread among plants than researchers once assumed.",
    p: STEM.mainIdea,
    c: [
      "Research on a plant's rapid response to touch suggests that electrical signaling may play a larger role in plants than was previously believed.",
      "The sensitive plant is the only plant known to respond to touch.",
      "Tanabe has discovered that some plants possess simple nervous systems.",
      "Most plant movements are caused by changes in the amount of water in leaf cells.",
    ],
    a: "A",
    e: "The text explains the mechanism behind Mimosa's folding in order to support Tanabe's broader argument about electrical signaling in plants. It begins by saying plants lack nervous systems and never claims Mimosa is unique or generalizes about most movements.",
  },
  {
    id: "pt1-rw2-10",
    skill: "central-ideas",
    d: "hard",
    s: "The following text is from a short story. Mr. Aldous has run the town's only bookstore for forty years.\n\nPeople assumed that Mr. Aldous loved books, and he let them assume it. In truth, what he loved was the moment when a customer, having wandered the shelves with no particular aim, stopped suddenly and drew out a volume as though it had called to them by name. Over the decades he had arranged the store to make that moment as likely as possible, and he considered it the chief accomplishment of his life.",
    p: STEM.mainIdea,
    c: [
      "What Mr. Aldous values most is not books themselves but helping customers make unexpected discoveries.",
      "Mr. Aldous regrets having spent his life running a bookstore.",
      "Mr. Aldous rarely reads the books that he sells.",
      "Most customers at the bookstore know exactly which book they want before they arrive.",
    ],
    a: "C",
    e: "The text separates what people assume he loves (books) from what he actually loves (the moment of discovery he has designed the store around). It never says he doesn't read, and he takes pride rather than regret in his work.",
  },
  {
    id: "pt1-rw2-11",
    skill: "command-evidence",
    d: "medium",
    s: "Sociologist Marcus Bell claims that the shift to remote work has weakened the informal mentoring that junior employees once received from senior colleagues. To test this claim, Bell surveyed junior employees at twelve large companies, asking how often they received unplanned advice from more experienced coworkers.",
    p: "Which survey result, if true, would most directly support Bell's claim?",
    c: [
      "Junior employees who worked mostly remotely reported receiving unplanned advice from senior colleagues far less often than junior employees who worked mostly in offices.",
      "Senior employees reported that they preferred remote work to working in an office.",
      "Junior employees at all twelve companies reported that formal training programs were helpful.",
      "Junior employees who worked mostly remotely reported slightly higher job satisfaction than those who worked in offices.",
    ],
    a: "B",
    e: "Bell's claim is about informal mentoring under remote work, and the survey measured unplanned advice. A result showing remote juniors get much less of it supports the claim. The other results concern preferences, formal training, or satisfaction.",
  },
  {
    id: "pt1-rw2-12",
    skill: "command-evidence",
    d: "hard",
    s: "Paleontologists have often proposed that the extraordinarily long necks of sauropod dinosaurs evolved mainly to let the animals reach leaves high in trees. Biomechanist Leonie Brandt has challenged this view, arguing that sauropods mostly held their necks roughly horizontal, sweeping them from side to side to crop low vegetation across a wide area without moving their massive bodies.",
    p: "Which finding, if true, would most directly support Brandt's argument?",
    c: [
      "Analyses of sauropod neck vertebrae indicate that the joints allowed wide side-to-side movement but only limited upward bending.",
      "Some sauropod species had necks more than 10 meters long.",
      "Fossilized sauropod teeth show wear consistent with eating plant material.",
      "Modern giraffes spend most of their feeding time browsing on high branches.",
    ],
    a: "A",
    e: "Brandt's view predicts necks that swing sideways more easily than they lift, which is exactly what the vertebrae finding shows. Neck length, plant-eating, and giraffe behavior do not distinguish her view from the high-browsing one.",
  },
  {
    id: "pt1-rw2-13",
    skill: "quantitative-evidence",
    d: "hard",
    s: "Education researcher Dana Whitfield compared three approaches to improving students' reading scores over one semester. Whitfield concluded that although all three approaches were associated with some improvement relative to no intervention, the frequency of in-person tutoring appeared to matter most.",
    fig: {
      kind: "table",
      title: "Average Reading Scores Before and After One Semester",
      head: ["Group", "Number of students", "Average score before", "Average score after"],
      rows: [
        ["Weekly tutoring", "40", "61", "74"],
        ["Daily tutoring", "38", "60", "79"],
        ["Reading app", "42", "62", "66"],
        ["No intervention", "41", "61", "63"],
      ],
      rowHeaders: true,
    },
    p: "Which choice most effectively uses data from the table to support Whitfield's conclusion?",
    c: [
      "The daily tutoring group's average score rose by 19 points, compared with 13 points for the weekly tutoring group and 4 points for the reading app group.",
      "The reading app group had the highest average score before the semester began.",
      "The no-intervention group's average score rose from 61 to 63.",
      "The daily tutoring group included fewer students than any other group.",
    ],
    a: "D",
    e: "To show that tutoring frequency matters most, compare the gains: daily tutoring (60 to 79, +19) beat weekly tutoring (61 to 74, +13), and both beat the app (+4). The other choices report facts that say nothing about the effect of tutoring frequency.",
  },
  {
    id: "pt1-rw2-14",
    skill: "quantitative-evidence",
    d: "medium",
    s: "In many turtle species, the temperature at which eggs incubate determines the sex of the hatchlings. Biologist Carmen Ruiz incubated eggs of one such species at seven temperatures and found that ______",
    fig: {
      kind: "plot",
      title: "Female Hatchlings by Incubation Temperature",
      xLabel: "Incubation temperature ({deg}C)",
      yLabel: "Female hatchlings (%)",
      x: [26, 32, 1],
      y: [0, 100, 20],
      series: [
        { type: "polyline", pts: [[26, 5], [27, 12], [28, 30], [29, 52], [30, 78], [31, 94], [32, 99]] },
        { type: "points", pts: [[26, 5], [27, 12], [28, 30], [29, 52], [30, 78], [31, 94], [32, 99]] },
      ],
    },
    p: STEM.graphComplete,
    c: [
      "the percentage of female hatchlings increased as incubation temperature increased, from about 5% at 26{deg}C to nearly 100% at 32{deg}C.",
      "the percentage of female hatchlings was highest at 26{deg}C.",
      "roughly equal numbers of male and female hatchlings emerged at every temperature.",
      "the percentage of female hatchlings fell sharply between 29{deg}C and 30{deg}C.",
    ],
    a: "B",
    e: "The line rises steadily from about 5% to about 99% as temperature goes up. It is lowest, not highest, at 26 degrees, is near 50% only around 29 degrees, and rises rather than falls between 29 and 30 degrees.",
  },
  {
    id: "pt1-rw2-15",
    skill: "inferences",
    d: "hard",
    s: "A species of freshwater snail introduced to Lake Tovan faces far fewer shell-crushing predators there than in its native rivers. Over thirty years, researchers observed that snails in the lake developed noticeably thinner shells than snails of the same species in the rivers. Because building a thick shell requires considerable energy, the researchers suggest that ______",
    p: STEM.complete,
    c: [
      "without strong pressure from predators, snails with thinner shells may have been able to devote more energy to growth and reproduction, giving them an advantage.",
      "the snails in Lake Tovan will eventually lose their shells entirely.",
      "predators in the snails' native rivers prefer to eat snails with thin shells.",
      "thick shells are more common among snails that live in lakes than among snails that live in rivers.",
    ],
    a: "C",
    e: "Thick shells cost energy and protect against predators; with few predators, that cost buys little, so thinner-shelled snails could spend the energy elsewhere. The other choices overreach or contradict the observation that lake snails have thinner shells.",
  },
  {
    id: "pt1-rw2-16",
    skill: "boundaries",
    d: "hard",
    s: "The data that the probe transmitted during its brief flyby of the ______ revealed a thin atmosphere composed mostly of nitrogen.",
    p: STEM.sec,
    c: ["moon", "moon,", "moon;", "moon--"],
    a: "A",
    e: "Everything before the blank is the subject ('The data that the probe transmitted...'), and 'revealed' is its verb. No punctuation belongs between a subject and its verb.",
  },
  {
    id: "pt1-rw2-17",
    skill: "boundaries",
    d: "hard",
    s: "Ada Lovelace's notes on Charles Babbage's proposed Analytical ______ published in 1843--included what many historians consider the first published computer program.",
    p: STEM.sec,
    c: ["Engine--", "Engine,", "Engine", "Engine;"],
    a: "D",
    e: "The phrase 'published in 1843' is set off by a dash after it, so it must be opened by a dash too. Mismatched punctuation around an interruption is an error.",
  },
  {
    id: "pt1-rw2-18",
    skill: "boundaries",
    d: "medium",
    s: "The first transatlantic telegraph cable was completed in 1858 and carried messages between Ireland and ______ however, it failed after only about three weeks of operation.",
    p: STEM.sec,
    c: ["Newfoundland;", "Newfoundland,", "Newfoundland", "Newfoundland:"],
    a: "B",
    e: "'However, it failed...' is an independent clause, so it must be separated from the first clause with a semicolon. A comma before 'however' would create a comma splice.",
  },
  {
    id: "pt1-rw2-19",
    skill: "boundaries",
    d: "medium",
    s: "The festival featured performers from Accra, ______ Lagos, Nigeria; and Dakar, Senegal.",
    p: STEM.sec,
    c: ["Ghana;", "Ghana,", "Ghana", "Ghana:"],
    a: "C",
    e: "Each item in the list contains a comma ('Lagos, Nigeria'), so the items are separated by semicolons, as the later ones already are.",
  },
  {
    id: "pt1-rw2-20",
    skill: "form-structure-sense",
    d: "medium",
    s: "Anita Rao and Felix Moreau have spent twenty years tracking the wood thrush from its summer breeding grounds to its winter range. The two ______ research has changed how conservationists protect songbird habitat.",
    p: STEM.sec,
    c: ["ornithologists'", "ornithologist's", "ornithologists", "ornithologists's"],
    a: "B",
    e: "The research belongs to two people, so the plural possessive 'ornithologists'' is needed. 'Ornithologist's' is singular, and 'ornithologists' has no possessive.",
  },
  {
    id: "pt1-rw2-21",
    skill: "subject-verb",
    d: "hard",
    s: "Each of the paintings in the museum's newest exhibition, which features works by artists from twelve countries, ______ accompanied by a short audio description recorded by the artist.",
    p: STEM.sec,
    c: ["is", "are", "were", "have been"],
    a: "D",
    e: "The subject is 'Each,' which is singular; 'paintings' and 'countries' sit inside modifying phrases. The verb must be the singular 'is.'",
  },
  {
    id: "pt1-rw2-22",
    skill: "form-structure-sense",
    d: "medium",
    s: "By the time the Brooklyn Bridge opened to the public in 1883, construction ______ for fourteen years.",
    p: STEM.sec,
    c: ["had been underway", "is underway", "has been underway", "will have been underway"],
    a: "A",
    e: "The construction happened before another past event (the 1883 opening), which calls for the past perfect: 'had been underway.'",
  },
  {
    id: "pt1-rw2-23",
    skill: "transitions",
    d: "medium",
    s: "Early studies of the drug suggested that it could slow the progression of the disease in most patients. Later trials involving larger and more varied groups of patients, ______ found the benefit to be modest and limited to people in the earliest stages of the disease.",
    p: STEM.transition,
    c: ["however,", "for instance,", "moreover,", "consequently,"],
    a: "C",
    e: "The later trials found a much smaller benefit than the early studies suggested, a contrast that 'however' signals.",
  },
  {
    id: "pt1-rw2-24",
    skill: "transitions",
    d: "hard",
    s: "The Hawaiian bobtail squid uses light produced by bacteria living in a special organ to match the moonlight above it, erasing its silhouette from the view of predators below. The bacteria, in turn, receive nutrients and a sheltered place to live. The relationship, ______ benefits both partners.",
    p: STEM.transition,
    c: ["in other words,", "nevertheless,", "by contrast,", "for example,"],
    a: "B",
    e: "The last sentence restates what the first two show--the squid gets camouflage and the bacteria get food and shelter--so a restating transition fits. Nothing is contrasted or exemplified.",
  },
  {
    id: "pt1-rw2-25",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "Hawaiian and Maori are both Polynesian languages.",
      "The standard Hawaiian alphabet has 13 letters.",
      "The standard Maori alphabet has 15 letters.",
      "In the late twentieth century, both languages became the focus of revitalization efforts, including the founding of immersion schools.",
    ),
    p: goal("emphasize a similarity between the two languages' recent histories."),
    c: [
      "Both Hawaiian and Maori became the focus of revitalization efforts, including immersion schools, in the late twentieth century.",
      "The Hawaiian alphabet has 13 letters, while the Maori alphabet has 15.",
      "Hawaiian and Maori are both Polynesian languages.",
      "The Maori alphabet has two more letters than the Hawaiian alphabet.",
    ],
    a: "D",
    e: "The goal is a similarity in recent history. Being Polynesian is a similarity but not a historical one, and the alphabet facts are a difference. Only the revitalization choice meets both conditions.",
  },
  {
    id: "pt1-rw2-26",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "The Atacama Desert is located in northern Chile.",
      "Some weather stations in the Atacama have never recorded rainfall.",
      "Because of its dry air, clear skies, and high altitude, the Atacama is home to several major astronomical observatories.",
      "One of them, the Atacama Large Millimeter/submillimeter Array (ALMA), consists of 66 radio antennas.",
    ),
    p: goal("explain why the Atacama Desert is well suited to astronomy."),
    c: [
      "The Atacama Desert's dry air, clear skies, and high altitude make it an ideal location for astronomical observatories such as ALMA.",
      "ALMA, an observatory in the Atacama Desert, consists of 66 radio antennas.",
      "Some weather stations in the Atacama Desert, which is in northern Chile, have never recorded rainfall.",
      "The Atacama Desert in northern Chile is home to several observatories.",
    ],
    a: "A",
    e: "Only the first choice gives the reasons the desert suits astronomy. The last choice says observatories are there but not why.",
  },
  {
    id: "pt1-rw2-27",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "*Things Fall Apart* is a 1958 novel by Nigerian author Chinua Achebe.",
      "It follows Okonkwo, a respected leader in the fictional Igbo village of Umuofia.",
      "The novel depicts the effects of British colonialism and Christian missionaries on Igbo society.",
      "It has been translated into more than 50 languages.",
    ),
    p: goal("introduce the novel and its subject to an audience unfamiliar with it."),
    c: [
      "Chinua Achebe's 1958 novel *Things Fall Apart* follows Okonkwo, a leader in an Igbo village, as British colonialism and Christian missionaries transform his society.",
      "*Things Fall Apart* has been translated into more than 50 languages.",
      "Okonkwo is a respected leader in Umuofia, a fictional Igbo village.",
      "Chinua Achebe, a Nigerian author, published a novel in 1958.",
    ],
    a: "B",
    e: "An introduction for newcomers needs the title, author, and what the book is about. Only the first choice supplies all three; the others give one detail each.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 1                                                      */
/* ------------------------------------------------------------------ */

export const PT1_M1 = build([
  {
    id: "pt1-m1-01",
    skill: "linear-eq-1var",
    d: "easy",
    p: "If 5x + 7 = 42, what is the value of x?",
    c: ["7", "5", "9.8", "35"],
    a: "B",
    e: "Subtract 7 from both sides: 5x = 35. Divide by 5: x = 7.",
  },
  {
    id: "pt1-m1-02",
    skill: "percentages",
    d: "easy",
    p: "What is 15% of 240?",
    c: ["36", "16", "24", "225"],
    a: "C",
    e: "15% of 240 is 0.15 {times} 240 = 36.",
  },
  {
    id: "pt1-m1-03",
    skill: "linear-functions",
    d: "easy",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-5, 5, 1],
      y: [-5, 5, 1],
      series: [{ type: "fn", f: (x) => 2 * x - 3 }],
      alt: "A line crossing the y-axis at negative 3 and passing through the point (2, 1).",
    },
    p: "The graph of the linear function f is shown. What is the slope of the graph of y = f(x)?",
    c: ["2", "-3", "1/2", "3"],
    a: "C",
    e: "The line passes through (0, -3) and (2, 1). Slope = (1 - (-3))/(2 - 0) = 4/2 = 2.",
  },
  {
    id: "pt1-m1-04",
    skill: "lines-angles-triangles",
    d: "easy",
    fig: {
      kind: "diagram",
      w: 240,
      h: 110,
      items: [
        { t: "line", a: [0, 100], b: [240, 100] },
        { t: "line", a: [120, 100], b: [184, 23] },
        { t: "dot", at: [120, 100] },
        { t: "text", at: [150, 86], s: "x{deg}" },
        { t: "text", at: [82, 72], s: "(2x + 30){deg}" },
      ],
      note: "Note: Figure not drawn to scale.",
      alt: "A straight line with a ray from a point on it, forming two adjacent angles labeled x degrees and (2x + 30) degrees.",
    },
    p: "In the figure, a ray extends from a point on a straight line. What is the value of x?",
    c: ["50", "30", "60", "75"],
    a: "D",
    e: "The two angles form a straight line, so x + (2x + 30) = 180. Then 3x = 150 and x = 50.",
  },
  {
    id: "pt1-m1-05",
    skill: "linear-eq-2var",
    d: "easy",
    p: "A store sells pens for $2 each and notebooks for $5 each. Mila spent a total of $41 on pens and notebooks, and she bought 7 notebooks. How many pens did Mila buy?",
    a: "3",
    e: "The notebooks cost 7 {times} $5 = $35, leaving $41 - $35 = $6 for pens. At $2 each, that is 3 pens.",
  },
  {
    id: "pt1-m1-06",
    skill: "equivalent-expressions",
    d: "easy",
    p: "Which expression is equivalent to 3x(x - 4) + 2x?",
    c: ["3x^2 - 10x", "3x^2 - 12x + 2", "3x^2 - 14x", "5x^2 - 12x"],
    a: "A",
    e: "Distribute: 3x(x - 4) = 3x^2 - 12x. Adding 2x gives 3x^2 - 10x.",
  },
  {
    id: "pt1-m1-07",
    skill: "ratios-rates",
    d: "medium",
    p: "A car travels 234 miles using 9 gallons of gasoline. At this rate, how many gallons of gasoline would the car use to travel 390 miles?",
    c: ["15", "12", "18", "26"],
    a: "B",
    e: "The car gets 234/9 = 26 miles per gallon. To go 390 miles it needs 390/26 = 15 gallons.",
  },
  {
    id: "pt1-m1-08",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The function g is defined by g(x) = x^2 - 6x + 11. What is the minimum value of g(x)?",
    c: ["2", "3", "6", "11"],
    a: "A",
    e: "Complete the square: g(x) = (x - 3)^2 + 2. The squared term is never negative, so the minimum is 2, reached at x = 3. (3 is where the minimum occurs, not its value.)",
  },
  {
    id: "pt1-m1-09",
    skill: "systems-linear",
    d: "medium",
    s: "x + y = 14\n3x - y = 22",
    p: "What is the value of x in the solution (x, y) to the given system of equations?",
    c: ["9", "4", "5", "12"],
    a: "D",
    e: "Add the equations to eliminate y: 4x = 36, so x = 9. (Then y = 5.)",
  },
  {
    id: "pt1-m1-10",
    skill: "linear-inequalities",
    d: "medium",
    p: "A delivery van can carry at most 1,800 pounds, including its driver. The driver weighs 180 pounds, and each box to be loaded weighs 45 pounds. Which inequality represents the possible numbers of boxes, b, that the van can carry on one trip with the driver?",
    c: ["180 + 45b <= 1,800", "45 + 180b <= 1,800", "180 + 45b >= 1,800", "45b <= 1,800 + 180"],
    a: "A",
    e: "Total weight is the driver's 180 pounds plus 45 pounds per box, 180 + 45b, and it can be at most 1,800: 180 + 45b <= 1,800.",
  },
  {
    id: "pt1-m1-11",
    skill: "data-distributions",
    d: "medium",
    fig: {
      kind: "table",
      title: "Books Read Over the Summer",
      head: ["Number of books", "Number of students"],
      rows: [["0", "2"], ["1", "5"], ["2", "6"], ["3", "4"], ["4", "3"]],
    },
    p: "The table shows the number of books read over the summer by each of the 20 students in a class. What is the median number of books read by these students?",
    c: ["2", "1", "2.05", "3"],
    a: "B",
    e: "With 20 values, the median is the mean of the 10th and 11th values in order. The first 2 are 0s, the next 5 (3rd to 7th) are 1s, and the next 6 (8th to 13th) are 2s, so both middle values are 2. (2.05 is the mean.)",
  },
  {
    id: "pt1-m1-12",
    skill: "quadratics",
    d: "medium",
    p: "What is the positive solution to the equation x^2 - 2x - 35 = 0?",
    a: "7",
    e: "Factor: (x - 7)(x + 5) = 0, so x = 7 or x = -5. The positive solution is 7.",
  },
  {
    id: "pt1-m1-13",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "table",
      head: ["x", "f(x)"],
      rows: [["1", "7"], ["3", "13"], ["6", "22"]],
    },
    p: "The table shows three values of x and their corresponding values of f(x), where f is a linear function. What is the value of f(10)?",
    a: "34",
    e: "The slope is (13 - 7)/(3 - 1) = 3, so f(x) = 3x + b. Using f(1) = 7 gives b = 4. Then f(10) = 3(10) + 4 = 34.",
  },
  {
    id: "pt1-m1-14",
    skill: "right-triangles-trig",
    d: "medium",
    p: "In right triangle ABC, angle C is the right angle, AB = 25, and BC = 7. What is the value of sin A?",
    c: ["7/25", "24/25", "7/24", "25/7"],
    a: "C",
    e: "Sine is opposite over hypotenuse. The side opposite angle A is BC = 7 and the hypotenuse is AB = 25, so sin A = 7/25.",
  },
  {
    id: "pt1-m1-15",
    skill: "exponential",
    d: "medium",
    p: "The population of a town was 12,000 in 2020 and has increased by 3% each year since then. Which equation gives the town's population, P, t years after 2020?",
    c: ["P = 12,000(1.03)^{t}", "P = 12,000(0.03)^{t}", "P = 12,000(1.3)^{t}", "P = 12,000 + 1.03t"],
    a: "C",
    e: "Growing by 3% a year multiplies the population by 1 + 0.03 = 1.03 each year, so P = 12,000(1.03)^{t}.",
  },
  {
    id: "pt1-m1-16",
    skill: "linear-eq-2var",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Number of hours",
      yLabel: "Total cost (dollars)",
      x: [0, 6, 1],
      y: [0, 200, 20],
      series: [{ type: "fn", f: (x) => 25 * x + 40, domain: [0, 6] }],
      alt: "A line starting at (0, 40) and rising 25 dollars for each hour, reaching 190 dollars at 6 hours.",
    },
    p: "The graph shows the total cost y, in dollars, of renting a boat for x hours. What is the best interpretation of the y-intercept of the graph in this context?",
    c: [
      "There is a fixed fee of $40 to rent the boat, in addition to an hourly charge.",
      "The boat costs $25 per hour to rent.",
      "Renting the boat for 1 hour costs a total of $40.",
      "The boat can be rented for at most 40 hours.",
    ],
    a: "D",
    e: "The y-intercept, (0, 40), is the cost for 0 hours: a $40 charge paid regardless of time. The $25 is the slope, and 1 hour actually costs $65.",
  },
  {
    id: "pt1-m1-17",
    skill: "probability",
    d: "medium",
    fig: {
      kind: "table",
      head: ["", "Prefer morning", "Prefer evening", "Total"],
      rows: [
        ["Grade 10", "34", "56", "90"],
        ["Grade 11", "48", "62", "110"],
        ["Total", "82", "118", "200"],
      ],
      rowHeaders: true,
    },
    p: "The table summarizes a survey in which 200 students said whether they prefer to study in the morning or in the evening. If one of the students who prefer to study in the evening is selected at random, what is the probability that the student is in grade 11?",
    c: ["31/59", "31/100", "31/55", "59/100"],
    a: "B",
    e: "Restrict to the 118 students who prefer evening; 62 of them are in grade 11. The probability is 62/118 = 31/59. (31/100 uses all 200 students, and 31/55 uses only grade 11.)",
  },
  {
    id: "pt1-m1-18",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The function f is defined by f(x) = (x - 4)(x + 2). The graph of y = f(x) in the xy-plane has its vertex at (h, k). What is the value of k?",
    c: ["-9", "-8", "1", "9"],
    a: "A",
    e: "The zeros are 4 and -2, so the vertex is midway between them, at x = 1. Then k = f(1) = (1 - 4)(1 + 2) = -9.",
  },
  {
    id: "pt1-m1-19",
    skill: "equivalent-expressions",
    d: "hard",
    p: "The expression 6x^2 + bx - 20, where b is a constant, is equivalent to (2x + 5)(3x - 4). What is the value of b?",
    a: "7",
    e: "Expand: (2x + 5)(3x - 4) = 6x^2 - 8x + 15x - 20 = 6x^2 + 7x - 20. So b = 7.",
  },
  {
    id: "pt1-m1-20",
    skill: "systems-linear",
    d: "hard",
    s: "3x - 5y = 8\nkx - 10y = 11",
    p: "In the given system of equations, k is a constant. If the system has no solution, what is the value of k?",
    a: "6",
    e: "A linear system has no solution when the lines are parallel but distinct. Doubling the first equation gives 6x - 10y = 16, so the lines are parallel when k = 6, and they are distinct because 16 != 11.",
  },
  {
    id: "pt1-m1-21",
    skill: "circles",
    d: "hard",
    p: "The equation x^2 + y^2 - 8x + 6y = 11 defines a circle in the xy-plane. What is the length of the circle's radius?",
    c: ["6", "11", "36", "{sqrt}11"],
    a: "C",
    e: "Complete the square: (x^2 - 8x + 16) + (y^2 + 6y + 9) = 11 + 16 + 9, so (x - 4)^2 + (y + 3)^2 = 36. The radius is {sqrt}36 = 6.",
  },
  {
    id: "pt1-m1-22",
    skill: "quadratics",
    d: "hard",
    p: "For what value of c does the equation 2x^2 - 12x + c = 0 have exactly one real solution?",
    c: ["18", "6", "9", "36"],
    a: "C",
    e: "A quadratic has exactly one real solution when its discriminant is 0: (-12)^2 - 4(2)(c) = 144 - 8c = 0, so c = 18.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 2 (harder)                                             */
/* ------------------------------------------------------------------ */

export const PT1_M2 = build([
  {
    id: "pt1-m2-01",
    skill: "linear-eq-1var",
    d: "medium",
    p: "If 3(2x - 5) = 4x + 9, what is the value of x - 2?",
    c: ["10", "12", "14", "24"],
    a: "A",
    e: "Distribute: 6x - 15 = 4x + 9, so 2x = 24 and x = 12. The question asks for x - 2 = 10.",
  },
  {
    id: "pt1-m2-02",
    skill: "percentages",
    d: "medium",
    p: "The price of a jacket was reduced by 20%. Later, the reduced price was increased by 25%. The final price is what percent of the original price?",
    c: ["100%", "95%", "105%", "125%"],
    a: "B",
    e: "Multiply the factors: 0.80 {times} 1.25 = 1.00. The final price equals the original price, which is 100% of it.",
  },
  {
    id: "pt1-m2-03",
    skill: "exponential",
    d: "medium",
    p: "The function m(t) = 800(0.75)^{t} gives the mass, in milligrams, of a substance remaining t hours after an experiment began. Which statement is true?",
    c: [
      "The mass of the substance decreases by 25% each hour.",
      "The mass of the substance decreases by 75% each hour.",
      "The mass of the substance decreases by 0.75 milligram each hour.",
      "The initial mass of the substance was 600 milligrams.",
    ],
    a: "D",
    e: "Each hour the mass is multiplied by 0.75, keeping 75% and losing 25%. The initial mass is m(0) = 800 milligrams.",
  },
  {
    id: "pt1-m2-04",
    skill: "linear-functions",
    d: "hard",
    p: "Line {l} in the xy-plane is perpendicular to the line y = (2/3)x + 4 and passes through the point (6, 1). What is the y-coordinate of the y-intercept of line {l}?",
    a: "10",
    e: "A perpendicular line has slope -3/2. Using point (6, 1): y - 1 = -(3/2)(x - 6), so y = -(3/2)x + 9 + 1 = -(3/2)x + 10. The y-intercept is at y = 10.",
  },
  {
    id: "pt1-m2-05",
    skill: "inference",
    d: "medium",
    p: "A random sample of 400 registered voters in a city found that 58% of them support a proposed new park. The margin of error associated with this estimate is 4.9%. Which of the following is the most plausible conclusion about all registered voters in the city?",
    c: [
      "It is plausible that between 53.1% and 62.9% of them support the proposed park.",
      "Exactly 58% of them support the proposed park.",
      "It is plausible that between 53.1% and 62.9% of the city's residents under 30 support the proposed park.",
      "The proposal will be approved with 58% of the vote.",
    ],
    a: "C",
    e: "The margin of error gives a plausible range for the whole population the sample represents: 58% plus or minus 4.9%, or 53.1% to 62.9%. It says nothing exact, nothing about a subgroup, and nothing about a vote.",
  },
  {
    id: "pt1-m2-06",
    skill: "area-volume",
    d: "medium",
    p: "A right circular cylinder has a volume of 360{pi} cubic centimeters and a height of 10 centimeters. What is the diameter, in centimeters, of the cylinder's base?",
    c: ["12", "6", "18", "36"],
    a: "D",
    e: "V = {pi}r^2h, so 360{pi} = {pi}r^2(10), giving r^2 = 36 and r = 6. The diameter is 2r = 12.",
  },
  {
    id: "pt1-m2-07",
    skill: "equivalent-expressions",
    d: "hard",
    p: "Which expression is equivalent to 4/(x - 3) - 2/(x + 1), for x > 3?",
    c: [
      "(2x + 10)/((x - 3)(x + 1))",
      "2/((x - 3)(x + 1))",
      "(2x - 2)/((x - 3)(x + 1))",
      "(6x - 2)/((x - 3)(x + 1))",
    ],
    a: "B",
    e: "Over the common denominator (x - 3)(x + 1), the numerator is 4(x + 1) - 2(x - 3) = 4x + 4 - 2x + 6 = 2x + 10.",
  },
  {
    id: "pt1-m2-08",
    skill: "systems-linear",
    d: "medium",
    p: "A theater sold 40 tickets for a matinee for a total of $1,150. Adult tickets cost $35 each, and student tickets cost $25 each. How many adult tickets were sold?",
    a: "15",
    e: "Let a be adult tickets; then 40 - a are student tickets. 35a + 25(40 - a) = 1,150 gives 10a + 1,000 = 1,150, so a = 15.",
  },
  {
    id: "pt1-m2-09",
    skill: "data-distributions",
    d: "hard",
    p: "Data set A consists of the values 12, 15, 15, 18, 20, 22, and 24. Data set B consists of the values in data set A and the value 60. Which statement best compares the mean and the median of data set B with those of data set A?",
    c: [
      "Both the mean and the median of data set B are greater, and the mean increases by more than the median does.",
      "The mean of data set B is greater, but the median is the same.",
      "The mean and the median of data set B are both the same as those of data set A.",
      "Both are greater, and the median increases by more than the mean does.",
    ],
    a: "A",
    e: "Set A has mean 126/7 = 18 and median 18. Set B has mean 186/8 = 23.25 and median (18 + 20)/2 = 19. Both rise, but the outlier pulls the mean up much more.",
  },
  {
    id: "pt1-m2-10",
    skill: "nonlinear-functions",
    d: "hard",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-3, 7, 1],
      y: [-2, 10, 1],
      series: [{ type: "fn", f: (x) => -((x - 2) ** 2) + 9 }],
      alt: "A downward-opening parabola with x-intercepts at negative 1 and 5 and vertex at (2, 9).",
    },
    p: "The graph of y = f(x) is shown, where f is a quadratic function. Which equation could define f?",
    c: ["f(x) = -(x + 1)(x - 5)", "f(x) = (x + 1)(x - 5)", "f(x) = -(x - 1)(x + 5)", "f(x) = -(x - 2)^2 - 9"],
    a: "D",
    e: "The parabola opens downward and crosses the x-axis at -1 and 5, so f(x) = a(x + 1)(x - 5) with a < 0. Checking the vertex: -(2 + 1)(2 - 5) = 9, which matches.",
  },
  {
    id: "pt1-m2-11",
    skill: "linear-inequalities",
    d: "medium",
    p: "What is the greatest integer value of x that satisfies the inequality 5 - 3(x - 2) > 2x - 9?",
    a: "3",
    e: "Simplify: 11 - 3x > 2x - 9, so 20 > 5x and x < 4. The greatest integer less than 4 is 3.",
  },
  {
    id: "pt1-m2-12",
    skill: "lines-angles-triangles",
    d: "hard",
    fig: {
      kind: "diagram",
      w: 240,
      h: 200,
      items: [
        { t: "poly", pts: [[120, 10], [20, 190], [240, 190]] },
        { t: "line", a: [60, 118], b: [192, 118] },
        { t: "text", at: [120, -2], s: "A" },
        { t: "text", at: [8, 196], s: "B" },
        { t: "text", at: [252, 196], s: "C" },
        { t: "text", at: [46, 116], s: "D" },
        { t: "text", at: [206, 116], s: "E" },
        { t: "text", at: [78, 58], s: "6" },
        { t: "text", at: [28, 150], s: "4" },
        { t: "text", at: [126, 108], s: "9" },
      ],
      note: "Note: Figure not drawn to scale.",
      alt: "Triangle ABC with segment DE parallel to BC; AD is 6, DB is 4, and DE is 9.",
    },
    p: "In the figure, segment DE is parallel to segment BC, AD = 6, DB = 4, and DE = 9. What is the length of segment BC?",
    c: ["15", "13", "13.5", "22.5"],
    a: "C",
    e: "Because DE is parallel to BC, triangle ADE is similar to triangle ABC. AB = 6 + 4 = 10, so BC/DE = AB/AD = 10/6, and BC = 9(10/6) = 15.",
  },
  {
    id: "pt1-m2-13",
    skill: "exponential",
    d: "hard",
    p: "The balance, in dollars, of an investment account t years after it was opened is modeled by A(t) = 5,000(1.02)^{4t}. Which of the following is the best interpretation of 1.02 in this context?",
    c: [
      "The balance increases by 2% every 3 months.",
      "The balance increases by 2% every year.",
      "The balance increases by 8% every 3 months.",
      "The balance increases by 1.02% every year.",
    ],
    a: "C",
    e: "The exponent 4t counts quarter-years: every 1/4 year (3 months) the balance is multiplied by 1.02, a 2% increase.",
  },
  {
    id: "pt1-m2-14",
    skill: "quadratics",
    d: "hard",
    p: "What is the sum of the solutions to the equation 2x^2 - 7x - 15 = 0?",
    a: "7/2",
    alt: ["3.5"],
    e: "Factor: (2x + 3)(x - 5) = 0, so x = -3/2 or x = 5. Their sum is 7/2. (For ax^2 + bx + c = 0 the sum is always -b/a = 7/2.)",
  },
  {
    id: "pt1-m2-15",
    skill: "ratios-rates",
    d: "medium",
    p: "A bag contains red marbles and blue marbles in a ratio of 3 to 5. After 12 red marbles are added to the bag, the numbers of red and blue marbles are equal. How many blue marbles are in the bag?",
    c: ["30", "18", "24", "42"],
    a: "D",
    e: "Let the bag hold 3k red and 5k blue marbles. Then 3k + 12 = 5k, so k = 6 and there are 5(6) = 30 blue marbles.",
  },
  {
    id: "pt1-m2-16",
    skill: "linear-functions",
    d: "hard",
    p: "In the xy-plane, line p has the equation 2x - 3y = 12. Line q is parallel to line p and passes through the point (0, 5). What is the x-coordinate of the x-intercept of line q?",
    c: ["-15/2", "-5", "5", "15/2"],
    a: "A",
    e: "Line p has slope 2/3, so line q is y = (2/3)x + 5. Setting y = 0: (2/3)x = -5, so x = -15/2.",
  },
  {
    id: "pt1-m2-17",
    skill: "nonlinear-functions",
    d: "hard",
    s: "y = 2x + 3\ny = x^2 - 2x + 3",
    p: "The graphs of the given equations in the xy-plane intersect at two points. What is the sum of the x-coordinates of the two points?",
    c: ["4", "0", "2", "6"],
    a: "B",
    e: "Set the expressions equal: x^2 - 2x + 3 = 2x + 3, so x^2 - 4x = 0 and x(x - 4) = 0. The x-coordinates are 0 and 4, with sum 4.",
  },
  {
    id: "pt1-m2-18",
    skill: "circles",
    d: "medium",
    p: "Points A and B lie on a circle with center O and radius 9. The measure of central angle AOB is 2{pi}/3 radians. What is the length of minor arc AB?",
    c: ["6{pi}", "3{pi}", "9{pi}", "12{pi}"],
    a: "B",
    e: "Arc length equals radius times the angle in radians: 9 {times} 2{pi}/3 = 6{pi}.",
  },
  {
    id: "pt1-m2-19",
    skill: "right-triangles-trig",
    d: "hard",
    p: "In right triangle XYZ, the right angle is at Y, and cos X = 0.6. What is the value of tan Z?",
    c: ["3/4", "3/5", "4/5", "4/3"],
    a: "A",
    e: "cos X = XY/XZ = 3/5, so take XY = 3 and XZ = 5, making YZ = 4. For angle Z, the opposite side is XY = 3 and the adjacent side is YZ = 4, so tan Z = 3/4.",
  },
  {
    id: "pt1-m2-20",
    skill: "inference",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Weeks after planting",
      yLabel: "Height (centimeters)",
      x: [0, 11, 1],
      y: [0, 35, 5],
      series: [
        { type: "points", pts: [[1, 14], [2, 15.2], [3, 17.8], [4, 18.5], [5, 21.4], [6, 22.2], [7, 24.9], [8, 26.1], [9, 27.5], [10, 30.4]] },
        { type: "fn", f: (x) => 1.8 * x + 12, domain: [0, 11] },
      ],
      alt: "A scatterplot of plant height against weeks, with a rising line of best fit.",
    },
    p: "The scatterplot shows the height of a plant, in centimeters, over 10 weeks, along with the line of best fit, y = 1.8x + 12. Which of the following is the best interpretation of 1.8 in this context?",
    c: [
      "For each additional week, the plant's predicted height increases by 1.8 centimeters.",
      "The plant's predicted height when it was planted was 1.8 centimeters.",
      "The plant grew a total of 1.8 centimeters over the 10 weeks.",
      "For each additional centimeter of height, the predicted number of weeks increases by 1.8.",
    ],
    a: "C",
    e: "1.8 is the slope: the predicted change in height (y) for each one-week increase in x. The initial predicted height is the y-intercept, 12.",
  },
  {
    id: "pt1-m2-21",
    skill: "equivalent-expressions",
    d: "hard",
    p: "For x > 0, the expression (x^{5/3})(x^{1/2}) is equivalent to x^{k}, where k is a constant. What is the value of k?",
    a: "13/6",
    alt: ["2.166", "2.167"],
    e: "Multiplying powers of the same base adds the exponents: 5/3 + 1/2 = 10/6 + 3/6 = 13/6.",
  },
  {
    id: "pt1-m2-22",
    skill: "quadratics",
    d: "hard",
    p: "In the xy-plane, the graph of y = x^2 + bx + 16, where b is a positive constant, intersects the graph of y = 4x at exactly one point. What is the value of b?",
    a: "12",
    e: "Set x^2 + bx + 16 = 4x, so x^2 + (b - 4)x + 16 = 0. One intersection means the discriminant is 0: (b - 4)^2 - 64 = 0, so b - 4 = 8 or -8. Since b > 0, b = 12.",
  },
]);
