/**
 * Practice Test 3. See `pt1.ts` for how the practice tests are written.
 */

import { STEM, goal, notes, q, texts, type QSpec } from "./author";

const F = "pt3";
const build = (specs: QSpec[]) => specs.map((s) => q(s, F));

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 1                                       */
/* ------------------------------------------------------------------ */

export const PT3_RW1 = build([
  {
    id: "pt3-rw1-01",
    skill: "words-in-context",
    d: "easy",
    s: "The museum's new wing was designed to be ______ to all visitors, with ramps, wide elevators, and exhibit labels printed in large type and in braille.",
    p: STEM.wic,
    c: ["accessible", "familiar", "profitable", "invisible"],
    a: "B",
    e: "Ramps, elevators, and large-print and braille labels are features that let everyone use the space, so the wing is accessible.",
  },
  {
    id: "pt3-rw1-02",
    skill: "words-in-context",
    d: "medium",
    s: "Although the engineering team's first prototype was crude, it ______ the central idea well enough to persuade investors to fund further development.",
    p: STEM.wic,
    c: ["demonstrated", "concealed", "contradicted", "postponed"],
    a: "A",
    e: "A prototype that persuaded investors must have shown, or demonstrated, the idea. Concealing or contradicting it would not have won funding.",
  },
  {
    id: "pt3-rw1-03",
    skill: "words-in-context",
    d: "medium",
    s: "Ecologists call the gray wolf a keystone species because its influence on its ecosystem is ______ relative to its numbers: by preying on elk, a small population of wolves can reshape the vegetation of an entire valley.",
    p: STEM.wic,
    c: ["disproportionate", "negligible", "predictable", "temporary"],
    a: "C",
    e: "A few wolves reshaping a whole valley have an influence far larger than their numbers suggest: disproportionate. 'Negligible' says the opposite.",
  },
  {
    id: "pt3-rw1-04",
    skill: "words-in-context",
    d: "hard",
    s: "The senator's speech was notably ______: rather than taking a clear position on the proposed tax, she praised the merits of both sides and avoided committing to either.",
    p: STEM.wic,
    c: ["noncommittal", "impassioned", "incendiary", "concise"],
    a: "D",
    e: "A speech that avoids taking a position is noncommittal. 'Impassioned' and 'incendiary' describe strong, provocative positions, the opposite of what she did.",
  },
  {
    id: "pt3-rw1-05",
    skill: "text-structure",
    d: "medium",
    s: "Monarch butterflies that emerge in late summer differ from those born earlier in the year. Instead of breeding within a few weeks and dying, as the summer generations do, these butterflies delay reproduction and fly thousands of kilometers south to spend the winter in the mountains of central Mexico. They can live for as long as eight months--several times longer than their parents.",
    p: STEM.purpose,
    c: [
      "To describe how one generation of monarch butterflies differs from other generations in its behavior and life span",
      "To explain why monarch butterflies have become endangered",
      "To argue that the summer generations of monarchs are more important than the late-summer generation",
      "To describe the plants that monarch butterflies feed on during migration",
    ],
    a: "A",
    e: "Every sentence contrasts the late-summer generation with earlier ones: delayed breeding, long migration, longer life. The text says nothing about endangerment, importance, or diet.",
  },
  {
    id: "pt3-rw1-06",
    skill: "text-structure",
    d: "medium",
    s: "For many years, scholars assumed that the Maya city of Tikal was abandoned mainly because of warfare. [u]Recent excavations have complicated that view.[/u] Researchers found that some of the city's reservoirs had become contaminated with mercury and toxic algae in the ninth century, suggesting that the loss of safe drinking water may have contributed to the city's decline.",
    p: STEM.underlined,
    c: [
      "It signals that the information that follows will challenge a long-standing explanation.",
      "It summarizes the evidence that supports the explanation given in the first sentence.",
      "It describes the method the researchers used to test the reservoirs.",
      "It states the text's final conclusion about why Tikal was abandoned.",
    ],
    a: "D",
    e: "The underlined sentence announces that new findings complicate the warfare explanation, and the next sentence gives those findings. It does not support the old view or describe a method.",
  },
  {
    id: "pt3-rw1-07",
    skill: "text-structure",
    d: "hard",
    s: "The following text is from a novel. Mr. Oduya is a retired schoolteacher.\n\nEvery morning Mr. Oduya walked to the end of the pier and back, a distance of exactly one mile, which he had measured himself the year he retired. He did not walk for his health, whatever his daughter believed, nor for the view, which he had long since stopped seeing. He walked because for forty years a bell had told him where to be, and without one, he had needed to invent a reason to leave the house.",
    p: STEM.structure,
    c: [
      "It describes a character's daily routine, rules out two possible explanations for it, and then reveals the actual reason for it.",
      "It recounts a conflict between a character and his daughter and then describes how they resolve it.",
      "It describes a place in detail and then explains how the place has changed over time.",
      "It presents a character's plans for the future and then explains why he abandons them.",
    ],
    a: "B",
    e: "The text sets out the walk, dismisses health and the view as reasons, and ends with the real one: he needs a structure the school bell once gave him. There is no conflict with his daughter and no account of the pier changing.",
  },
  {
    id: "pt3-rw1-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Many nutrition researchers have argued that breakfast is the most important meal of the day. They cite studies showing that people who regularly eat breakfast weigh less, on average, than people who skip it.",
      "Most studies linking breakfast to lower body weight have been observational: they compared people who already chose to eat breakfast with people who did not. When researcher Sanna Virtanen randomly assigned participants to either eat or skip breakfast for sixteen weeks, she found no significant difference in weight change between the two groups.",
    ),
    p: "Based on the texts, how would Virtanen (Text 2) most likely respond to the researchers' argument in Text 1?",
    c: [
      "By arguing that the studies they cite cannot show that eating breakfast causes lower weight, since people who choose to eat breakfast may differ in other ways from people who skip it",
      "By agreeing that eating breakfast causes weight loss but only over periods longer than sixteen weeks",
      "By claiming that people who skip breakfast generally weigh less than people who eat it",
      "By suggesting that observational studies are more reliable than randomized experiments",
    ],
    a: "C",
    e: "Virtanen contrasts self-selected groups with random assignment and finds no effect when choice is removed. That implies the earlier correlation may reflect other differences between breakfast eaters and skippers, not an effect of breakfast.",
  },
  {
    id: "pt3-rw1-09",
    skill: "central-ideas",
    d: "easy",
    s: "The Great Pacific Garbage Patch is often imagined as a floating island of trash. In reality, most of its debris consists of tiny fragments of plastic, many smaller than a grain of rice, spread through the upper layers of the ocean. Because the particles are so small and so widely dispersed, the patch is difficult to see from a ship or a satellite--and far harder to clean up than a solid island would be.",
    p: STEM.mainIdea,
    c: [
      "The Great Pacific Garbage Patch consists mostly of small, scattered plastic particles rather than a solid mass, which makes it hard to see and to clean up.",
      "The Great Pacific Garbage Patch is a solid island of trash that can be seen from space.",
      "Most ocean plastic sinks quickly to the sea floor.",
      "Satellites are the most effective tool for cleaning up ocean plastic.",
    ],
    a: "A",
    e: "The text corrects the 'island' image and explains the consequence of the debris being tiny and dispersed. It says the patch is hard to see from satellites and describes debris in the upper layers, not on the sea floor.",
  },
  {
    id: "pt3-rw1-10",
    skill: "central-ideas",
    d: "medium",
    s: "The following text is from a short story. Farida is about to begin her first day as a ferry pilot.\n\nFarida had studied the charts until she could draw them from memory: every sandbar, every channel marker, every place where the current turned. Still, standing at the wheel before dawn, she felt the river's width in a way no chart had conveyed. The water was darker and faster than the blue paper had suggested, and it did not care in the least how carefully she had prepared.",
    p: STEM.mainIdea,
    c: [
      "Despite her careful preparation, Farida finds the real river more daunting than her study of it had led her to expect.",
      "Farida realizes that the charts she studied contained serious errors.",
      "Farida decides that she is not ready to pilot the ferry.",
      "Farida is confident that her preparation has made the job easy.",
    ],
    a: "D",
    e: "'Still' turns from her thorough study to the river's unsettling reality: darker, faster, and indifferent to her preparation. The charts are not called wrong, and she does not give up.",
  },
  {
    id: "pt3-rw1-11",
    skill: "command-evidence",
    d: "medium",
    s: "Economist Dev Malhotra claims that the spread of mobile phones in rural Kenya raised household incomes, in large part by allowing families to receive money transfers quickly and cheaply from relatives working in cities.",
    p: "Which finding, if true, would most directly support Malhotra's claim?",
    c: [
      "Households that adopted mobile money services saw larger increases in income than otherwise similar households that did not, mostly because of transfers from relatives in cities.",
      "Mobile phones became common in Kenyan cities several years before they became common in rural areas.",
      "Many rural households used their phones mainly to check weather forecasts.",
      "The price of mobile phones in Kenya fell steadily over the period studied.",
    ],
    a: "B",
    e: "The claim links phone use to higher income through transfers. A comparison showing adopters gained more income, driven by transfers, supports exactly that link. The other findings do not connect phones to income.",
  },
  {
    id: "pt3-rw1-12",
    skill: "command-evidence",
    d: "medium",
    s: "*The Glass Orchard* is a novel about a family of apple growers. In the novel, the author portrays the grandmother, Nana, as someone whose calm authority governs the household.",
    p: "Which quotation from *The Glass Orchard* most effectively illustrates the claim?",
    c: [
      "\"When Nana spoke, even the youngest children set down their spoons; she never raised her voice, and she never needed to.\"",
      "\"The orchard stretched down to the river in long, crooked rows.\"",
      "\"Each autumn the family hired pickers from the neighboring town.\"",
      "\"Nana's kitchen smelled of cinnamon and woodsmoke.\"",
    ],
    a: "C",
    e: "Children falling silent when she speaks shows her authority, and never needing to raise her voice shows it is calm. The other lines describe the setting or the family's work.",
  },
  {
    id: "pt3-rw1-13",
    skill: "quantitative-evidence",
    d: "medium",
    s: "Transportation researcher Nadia Hale studied four cities, two of which--Aldgate and Delmont--built networks of protected bike lanes between 2012 and 2022. Hale concluded that building protected bike lanes is associated with substantial increases in cycling.",
    fig: {
      kind: "table",
      title: "Share of Trips Made by Bicycle",
      head: ["City", "2012", "2022"],
      rows: [
        ["Aldgate", "3%", "11%"],
        ["Brookvale", "5%", "6%"],
        ["Carrow", "8%", "9%"],
        ["Delmont", "2%", "10%"],
      ],
      rowHeaders: true,
    },
    p: "Which choice most effectively uses data from the table to support Hale's conclusion?",
    c: [
      "In the two cities that built protected bike lanes, the share of trips made by bicycle rose by 8 percentage points, while in the other two cities it rose by only 1 percentage point.",
      "Carrow had the highest share of trips made by bicycle in 2012.",
      "Brookvale's share of trips made by bicycle rose from 5% to 6%.",
      "Aldgate had a higher share of trips made by bicycle than Delmont did in 2022.",
    ],
    a: "A",
    e: "Supporting the association requires comparing cities with and without the lanes: +8 points in Aldgate and Delmont against +1 in Brookvale and Carrow. The other choices describe single cities.",
  },
  {
    id: "pt3-rw1-14",
    skill: "quantitative-evidence",
    d: "medium",
    s: "A researcher found that among the participants in a sleep study, those who slept more each night tended to have faster reaction times. For example, ______",
    fig: {
      kind: "plot",
      title: "Sleep and Reaction Time",
      xLabel: "Average sleep per night (hours)",
      yLabel: "Reaction time (ms)",
      x: [5, 9, 0.5],
      y: [280, 400, 20],
      labelEvery: 2,
      series: [{ type: "points", pts: [[5, 390], [5.5, 372], [6, 360], [6.5, 345], [7, 330], [7.5, 318], [8, 305], [8.5, 300], [9, 295]] }],
    },
    p: STEM.graphComplete,
    c: [
      "participants who averaged 5 hours of sleep had reaction times of about 390 milliseconds, while those who averaged 9 hours had reaction times of about 295 milliseconds.",
      "participants who averaged 7 hours of sleep had reaction times of about 330 milliseconds.",
      "the slowest reaction time recorded in the study was about 295 milliseconds.",
      "reaction times became slower as the amount of sleep increased.",
    ],
    a: "D",
    e: "The example must show more sleep going with faster (lower) times, which requires comparing two sleep levels. 295 milliseconds is the fastest time, not the slowest, and times fall rather than rise with more sleep.",
  },
  {
    id: "pt3-rw1-15",
    skill: "inferences",
    d: "medium",
    s: "Tardigrades, microscopic animals found in moss and soil, can survive extreme drying by entering a state in which their metabolism nearly stops. Researchers discovered that tardigrades produce unusual proteins that form a glass-like material inside their cells as they dry out. Tardigrades that were genetically altered so that they could not make these proteins died when dried. These findings suggest that ______",
    p: STEM.complete,
    c: [
      "the proteins play an essential role in allowing tardigrades to survive drying.",
      "tardigrades cannot survive in moss or soil.",
      "the proteins are produced only when tardigrades are fully hydrated.",
      "most animals produce the same proteins that tardigrades do.",
    ],
    a: "A",
    e: "Removing the proteins removed the ability to survive drying, which points to the proteins being necessary for it. The text says tardigrades live in moss and soil and that the proteins form as the animals dry out.",
  },
  {
    id: "pt3-rw1-16",
    skill: "boundaries",
    d: "easy",
    s: "Mount Kilimanjaro, the highest mountain in ______ rises nearly 5,900 meters above sea level.",
    p: STEM.sec,
    c: ["Africa,", "Africa", "Africa;", "Africa:"],
    a: "C",
    e: "The appositive 'the highest mountain in Africa' opens with a comma after 'Kilimanjaro,' so it must close with one before the verb 'rises.'",
  },
  {
    id: "pt3-rw1-17",
    skill: "boundaries",
    d: "medium",
    s: "The research vessel carried three kinds of ______ sonar arrays for mapping the seafloor, remotely operated vehicles for collecting samples, and cameras built to withstand extreme pressure.",
    p: STEM.sec,
    c: ["equipment:", "equipment;", "equipment", "equipment, and"],
    a: "B",
    e: "A complete clause ('The research vessel carried three kinds of equipment') introduces the list, so a colon is correct. A semicolon would leave the list as a fragment.",
  },
  {
    id: "pt3-rw1-18",
    skill: "boundaries",
    d: "medium",
    s: "When the poet Phillis Wheatley published *Poems on Various Subjects, Religious and Moral* in ______ she became one of the first African American authors to publish a book of poetry.",
    p: STEM.sec,
    c: ["1773,", "1773", "1773;", "1773:"],
    a: "A",
    e: "An introductory dependent clause ('When...1773') is followed by a comma before the main clause.",
  },
  {
    id: "pt3-rw1-19",
    skill: "boundaries",
    d: "hard",
    s: "According to the historian, the treaty ______ \"a compromise that satisfied no one and endured for a century.\"",
    p: STEM.sec,
    c: ["was", "was:", "was,", "was;"],
    a: "D",
    e: "The quotation completes the sentence as the complement of 'was,' so it is integrated with no punctuation, just as it would be without quotation marks.",
  },
  {
    id: "pt3-rw1-20",
    skill: "form-structure-sense",
    d: "easy",
    s: "Last spring, volunteers ______ more than 2,000 native trees along the riverbank to reduce erosion.",
    p: STEM.sec,
    c: ["planted", "plant", "will plant", "have been planting"],
    a: "B",
    e: "'Last spring' places the action in the completed past, so the simple past 'planted' is needed.",
  },
  {
    id: "pt3-rw1-21",
    skill: "form-structure-sense",
    d: "medium",
    s: "Unlike the cheetah, which relies on short bursts of speed, ______",
    p: STEM.sec,
    c: [
      "the African wild dog pursues its prey over long distances until the prey is exhausted.",
      "the African wild dog's hunting strategy is to pursue prey over long distances.",
      "pursuing prey over long distances is the strategy of the African wild dog.",
      "the prey of the African wild dog is pursued over long distances until exhausted.",
    ],
    a: "C",
    e: "The comparison must be between two animals: the cheetah and the African wild dog. The other choices compare the cheetah with a strategy, an action, or the prey.",
  },
  {
    id: "pt3-rw1-22",
    skill: "subject-verb",
    d: "hard",
    s: "The number of students enrolled in computer science courses at the university ______ tripled over the past decade.",
    p: STEM.sec,
    c: ["has", "have", "are", "were"],
    a: "D",
    e: "The subject is 'The number,' which is singular; 'students' and 'courses' are inside modifying phrases. So the verb is 'has.'",
  },
  {
    id: "pt3-rw1-23",
    skill: "transitions",
    d: "medium",
    s: "Honeybees are often credited with pollinating most of the world's crops. ______ many crops, such as tomatoes and blueberries, are pollinated more effectively by wild bees, which can vibrate flowers to release pollen in a way that honeybees cannot.",
    p: STEM.transition,
    c: ["However,", "Therefore,", "Similarly,", "For example,"],
    a: "B",
    e: "The second sentence qualifies the common credit given to honeybees by pointing to crops wild bees pollinate better, a contrast that 'However' signals.",
  },
  {
    id: "pt3-rw1-24",
    skill: "transitions",
    d: "hard",
    s: "The first vaccines were developed long before scientists understood how the immune system works. Edward Jenner's smallpox vaccine, ______ was introduced in 1796, nearly a century before antibodies were discovered.",
    p: STEM.transition,
    c: ["for instance,", "however,", "consequently,", "in contrast,"],
    a: "A",
    e: "Jenner's vaccine is an example of a vaccine developed before the immune system was understood, so 'for instance' fits.",
  },
  {
    id: "pt3-rw1-25",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "The Great Wall of China was built and rebuilt over many centuries.",
      "Most of the wall that survives today was built during the Ming dynasty (1368-1644).",
      "The Ming sections were built largely of brick and stone.",
      "Earlier sections were often made of rammed earth.",
    ),
    p: goal("contrast the materials used in different sections of the Great Wall."),
    c: [
      "While the surviving Ming-dynasty sections of the Great Wall were built largely of brick and stone, earlier sections were often made of rammed earth.",
      "The Great Wall of China was built and rebuilt over many centuries.",
      "Most of the Great Wall that survives today was built during the Ming dynasty.",
      "The Ming dynasty lasted from 1368 to 1644.",
    ],
    a: "D",
    e: "Only the first choice sets one section's materials against another's.",
  },
  {
    id: "pt3-rw1-26",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "Zaha Hadid was an Iraqi-born British architect.",
      "In 2004, she became the first woman to receive the Pritzker Architecture Prize.",
      "Her designs include the MAXXI museum in Rome and the London Aquatics Centre, built for the 2012 Olympics.",
      "Her buildings are known for their flowing, curved forms.",
    ),
    p: goal("highlight an achievement that made Hadid a pioneer in her field."),
    c: [
      "In 2004, Zaha Hadid became the first woman to receive the Pritzker Architecture Prize.",
      "Zaha Hadid's buildings are known for their flowing, curved forms.",
      "Zaha Hadid designed the London Aquatics Centre for the 2012 Olympics.",
      "Zaha Hadid was an architect who was born in Iraq.",
    ],
    a: "B",
    e: "Being the first woman to win the field's top prize is what marks her as a pioneer. The other choices describe her style, a building, or her background.",
  },
  {
    id: "pt3-rw1-27",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "Researchers wanted to know whether urban noise affects how songbirds sing.",
      "They recorded great tits living in cities and in nearby forests.",
      "The city birds sang at higher pitches than the forest birds did.",
      "Higher-pitched songs are less likely to be drowned out by low-frequency traffic noise.",
    ),
    p: goal("present the researchers' finding along with a likely explanation for it."),
    c: [
      "City great tits sang at higher pitches than forest birds did, likely because higher-pitched songs are less easily drowned out by low-frequency traffic noise.",
      "City great tits sang at higher pitches than great tits living in nearby forests did.",
      "Researchers recorded great tits in cities and forests to learn whether urban noise affects birdsong.",
      "Low-frequency traffic noise can drown out sounds in cities.",
    ],
    a: "C",
    e: "The goal needs both the result and the reason. The second choice gives only the result, the third only the purpose, and the last only background.",
  },
]);

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 2 (harder)                              */
/* ------------------------------------------------------------------ */

export const PT3_RW2 = build([
  {
    id: "pt3-rw2-01",
    skill: "words-in-context",
    d: "hard",
    s: "The diarist's entries are strikingly ______: she records the outbreak of war in the same flat, even tone she uses to note the price of eggs.",
    p: STEM.wic,
    c: ["dispassionate", "effusive", "anguished", "whimsical"],
    a: "A",
    e: "Recording war in the same flat tone as egg prices shows an absence of emotion: dispassionate. 'Effusive' and 'anguished' imply strong feeling.",
  },
  {
    id: "pt3-rw2-02",
    skill: "words-in-context",
    d: "hard",
    s: "Though often described as a recluse, the composer was hardly ______: his letters show that he corresponded warmly with dozens of friends and hosted musicians at his home nearly every week.",
    p: STEM.wic,
    c: ["solitary", "gregarious", "eccentric", "prolific"],
    a: "C",
    e: "The evidence of a busy social life shows he was not the lonely figure a 'recluse' would be, so he was hardly solitary. Saying he was hardly 'gregarious' would contradict that evidence.",
  },
  {
    id: "pt3-rw2-03",
    skill: "words-in-context",
    d: "hard",
    s: "The new policy was intended to ______ the effects of the drought on small farmers, providing low-interest loans and emergency water supplies to those hardest hit.",
    p: STEM.wic,
    c: ["mitigate", "exacerbate", "document", "predict"],
    a: "D",
    e: "Loans and emergency water reduce the drought's harm, which is what 'mitigate' means. 'Exacerbate' means to make worse.",
  },
  {
    id: "pt3-rw2-04",
    skill: "words-in-context",
    d: "hard",
    s: "Critics have called the novel's ending ______, arguing that the sudden reconciliation of characters who have been bitter enemies for three hundred pages is not earned by anything that comes before it.",
    p: STEM.wic,
    c: ["contrived", "inevitable", "ambiguous", "understated"],
    a: "B",
    e: "An ending that nothing earlier prepares for feels artificial, or contrived. 'Inevitable' would mean the story made it unavoidable, the opposite of the critics' point.",
  },
  {
    id: "pt3-rw2-05",
    skill: "text-structure",
    d: "hard",
    s: "Mapmakers have long faced an unavoidable problem: Earth's curved surface cannot be shown on a flat map without distortion. The widely used Mercator projection preserves the shapes of small areas and makes it easy to plot a constant compass heading, which is why it became standard for navigation. But it greatly enlarges regions far from the equator, making Greenland appear roughly the size of Africa, which is in fact about fourteen times larger.",
    p: STEM.purpose,
    c: [
      "To explain a trade-off involved in one approach to mapmaking",
      "To argue that the Mercator projection should no longer be used",
      "To describe the history of navigation at sea",
      "To compare the climates of Greenland and Africa",
    ],
    a: "C",
    e: "The text sets the Mercator projection's navigational strengths against its distortion of area: a trade-off. It does not call for abandoning it, trace navigation's history, or discuss climate.",
  },
  {
    id: "pt3-rw2-06",
    skill: "text-structure",
    d: "hard",
    s: "Many songbirds migrate at night, finding their way by the stars. [u]Young indigo buntings, however, are not born knowing which stars to follow.[/u] In a classic series of planetarium experiments, researcher Stephen Emlen showed that the birds learn, during their first summer, to find the point in the sky around which the stars appear to rotate, and later use that point to orient themselves.",
    p: STEM.underlined,
    c: [
      "It qualifies the claim in the first sentence by indicating that the ability described is learned rather than inborn in one species, setting up the explanation that follows.",
      "It contradicts the claim that songbirds use the stars to navigate.",
      "It summarizes the conclusion Emlen reached at the end of his experiments.",
      "It describes the method Emlen used in his planetarium experiments.",
    ],
    a: "A",
    e: "The underlined sentence accepts that the birds navigate by stars but adds that young buntings must learn how, which the final sentence then explains. It neither denies star navigation nor describes the method.",
  },
  {
    id: "pt3-rw2-07",
    skill: "text-structure",
    d: "hard",
    s: "The following text is from a poem.\n\nMy mother's hands were maps I could not read--\nthe white scar where a kettle once had slipped,\nthe knuckle swollen from a winter's work,\nthe ring worn thin. I study them at last\nnow that my own have started to resemble them.",
    p: STEM.structure,
    c: [
      "The speaker describes features of her mother's hands that she once did not understand and then reveals why she is examining them now.",
      "The speaker recounts a single accident in detail and then describes its lasting effects.",
      "The speaker compares her mother's hands to a real map and then describes a journey.",
      "The speaker lists her mother's possessions and then explains how they were inherited.",
    ],
    a: "D",
    e: "The poem lists the scar, knuckle, and ring--marks she 'could not read'--and ends by explaining that she studies them now because her own hands resemble them. The map is a metaphor, and the kettle is one detail among several.",
  },
  {
    id: "pt3-rw2-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Art historians have generally credited the invention of linear perspective to the architect Filippo Brunelleschi, who demonstrated the technique in Florence around 1415. Before this, the argument goes, painters had no method for convincingly depicting depth.",
      "Historian Rosa Delgado acknowledges Brunelleschi's role in making perspective systematic, but she points to Roman wall paintings, such as those preserved at Pompeii, that show buildings receding in consistent, convincing depth. Delgado argues that some ancient painters had an intuitive, if not fully mathematical, command of perspective.",
    ),
    p: "Based on the texts, how would Delgado (Text 2) most likely respond to the argument described in Text 1?",
    c: [
      "By suggesting that it underestimates the understanding of depth shown by some earlier painters, even though they lacked Brunelleschi's systematic method",
      "By rejecting the idea that Brunelleschi played any role in the development of perspective",
      "By arguing that Roman wall paintings were copied from Renaissance works",
      "By agreeing that no painter before 1415 depicted depth convincingly",
    ],
    a: "B",
    e: "Delgado credits Brunelleschi with the system but cites Roman paintings that convincingly show depth, contradicting the claim that earlier painters had no way to do so.",
  },
  {
    id: "pt3-rw2-09",
    skill: "central-ideas",
    d: "hard",
    s: "In 1930, the economist John Maynard Keynes predicted that within a century, rising productivity would allow people in wealthy countries to work as little as fifteen hours a week. Productivity has risen roughly as he expected, yet working hours have fallen far less. Economist Juliet Ansah argues that Keynes underestimated how much people's material wants would expand: rather than turning productivity gains into leisure, societies have largely turned them into greater consumption.",
    p: STEM.mainIdea,
    c: [
      "An economist argues that working hours have not fallen as Keynes predicted because productivity gains have gone mostly toward greater consumption rather than leisure.",
      "Keynes's prediction about productivity turned out to be badly mistaken.",
      "Most workers in wealthy countries now work about fifteen hours a week.",
      "Rising consumption has caused productivity to fall in wealthy countries.",
    ],
    a: "A",
    e: "The text explains why Keynes's prediction about hours failed, according to Ansah. It says his productivity forecast was roughly right, and hours have not fallen to fifteen.",
  },
  {
    id: "pt3-rw2-10",
    skill: "central-ideas",
    d: "hard",
    s: "The following text is from a novel. Tomas has returned to his village after studying medicine abroad.\n\nThe villagers still called him by his childhood nickname, and old Senora Ruiz still scolded him for tracking mud onto her floor. They listened politely when he spoke of his training, then asked whether he remembered the summer he fell out of the Garcias' fig tree. Tomas had imagined returning as a doctor. He began to understand that, here, he would always be a boy who had once fallen from a tree--and to his surprise, he did not entirely mind.",
    p: STEM.mainIdea,
    c: [
      "Tomas realizes that the villagers see him mainly as the person they knew in his childhood rather than as a doctor, and he finds that he partly accepts this.",
      "Tomas is angry that the villagers refuse to let him practice medicine.",
      "Tomas regrets having left the village to study abroad.",
      "The villagers are eager to hear about Tomas's medical training.",
    ],
    a: "C",
    e: "The villagers treat him as the boy they remember, and he discovers he 'did not entirely mind.' They listen only politely, and nothing suggests anger or regret.",
  },
  {
    id: "pt3-rw2-11",
    skill: "command-evidence",
    d: "hard",
    s: "Historian Paulo Mendes argues that the printing press spread more quickly to cities that were major centers of trade than to other cities, because merchants supplied both the money to set up print shops and a ready market for printed materials such as account books and price lists.",
    p: "Which finding, if true, would most directly support Mendes's argument?",
    c: [
      "Among European cities of similar population, those that were major trade centers gained print shops, on average, about two decades earlier than those that were not.",
      "The first printed books in Europe were mostly religious texts.",
      "Some merchants continued to keep handwritten account books into the 1600s.",
      "Print shops appeared earlier in university towns than in centers of trade.",
    ],
    a: "D",
    e: "Mendes claims trade centers got the press sooner. A comparison that holds population constant and finds trade centers two decades ahead supports this directly. The last choice would weaken it.",
  },
  {
    id: "pt3-rw2-12",
    skill: "command-evidence",
    d: "medium",
    s: "In the essay \"On Walking Slowly,\" the author contends that moving at a slow pace allows a person to notice details that would otherwise be overlooked.",
    p: "Which quotation from the essay most effectively illustrates the claim?",
    c: [
      "\"At a stroll, the city discloses itself: the date carved above a doorway, the fern rooted in a crack of the wall, the cat asleep in a window I have passed a thousand times.\"",
      "\"Walking is the oldest form of human transportation.\"",
      "\"My doctor recommends thirty minutes of walking each day.\"",
      "\"I have never owned a car, and I have never wanted one.\"",
    ],
    a: "A",
    e: "The first quotation lists small details the slow walker notices, including one in a window passed 'a thousand times.' The others say nothing about noticing details.",
  },
  {
    id: "pt3-rw2-13",
    skill: "quantitative-evidence",
    d: "hard",
    s: "Seed bank manager Hiroshi Sato claims that although cooler storage improves the germination rates of stored seeds, humidity matters even more than temperature.",
    fig: {
      kind: "table",
      title: "Germination Rates of Seeds After Two Years of Storage",
      head: ["Storage temperature", "Low humidity", "High humidity"],
      rows: [
        ["5{deg}C", "94%", "71%"],
        ["15{deg}C", "88%", "52%"],
        ["25{deg}C", "76%", "30%"],
      ],
      rowHeaders: true,
    },
    p: "Which choice most effectively uses data from the table to support Sato's claim?",
    c: [
      "Seeds stored at 25{deg}C with low humidity germinated at a higher rate (76%) than seeds stored at 5{deg}C with high humidity (71%).",
      "Seeds stored at 5{deg}C with low humidity had the highest germination rate, 94%.",
      "At every temperature, seeds stored with low humidity germinated at a higher rate than seeds stored with high humidity.",
      "Seeds stored at 25{deg}C with high humidity germinated at a rate of only 30%.",
    ],
    a: "B",
    e: "To show humidity matters more than temperature, the best evidence is that the warmest storage with low humidity beats the coolest storage with high humidity. The third choice shows humidity matters, but not that it matters more than temperature.",
  },
  {
    id: "pt3-rw2-14",
    skill: "quantitative-evidence",
    d: "hard",
    s: "An analyst claims that although the South lagged far behind the North in broadband adoption during the early years shown, the gap between the two regions had nearly closed by 2020.",
    fig: {
      kind: "plot",
      title: "Households with Broadband Internet",
      xLabel: "Year",
      yLabel: "Households (%)",
      x: [2000, 2020, 5],
      y: [0, 100, 20],
      series: [
        { type: "polyline", label: "North", pts: [[2000, 5], [2005, 30], [2010, 62], [2015, 78], [2020, 88]] },
        { type: "polyline", label: "South", dashed: true, pts: [[2000, 2], [2005, 12], [2010, 35], [2015, 63], [2020, 84]] },
      ],
    },
    p: "Which choice best describes data from the graph that support the analyst's claim?",
    c: [
      "In 2010, the North's rate exceeded the South's by 27 percentage points, but by 2020 the difference was only 4 percentage points.",
      "Both regions' rates increased during every five-year period shown.",
      "The North's rate was higher than the South's rate in every year shown.",
      "The South's rate rose from 2% in 2000 to 84% in 2020.",
    ],
    a: "C",
    e: "The claim is about a gap narrowing, so the data must compare the gap at two times: 27 points in 2010 (62 against 35) and 4 points in 2020 (88 against 84). The other choices are true but say nothing about the gap shrinking.",
  },
  {
    id: "pt3-rw2-15",
    skill: "inferences",
    d: "hard",
    s: "Linguists reconstructing the common ancestor of the Indo-European languages have noted that many of its descendant languages share related words for 'wheel,' 'axle,' and 'wagon.' Because wheeled vehicles are not known to have existed before about 4000 BCE, some researchers argue that ______",
    p: STEM.complete,
    c: [
      "the ancestral language was probably still spoken as a single language after about 4000 BCE.",
      "the ancestral language had already split into its descendants long before 4000 BCE.",
      "each Indo-European language developed its own words for wheeled vehicles independently.",
      "wheeled vehicles were invented by speakers of a language unrelated to Indo-European.",
    ],
    a: "D",
    e: "Shared, related words suggest the vocabulary was inherited from the common ancestor, so that language must have had words for wheels--which means it was still one language after wheels existed. The second choice contradicts this.",
  },
  {
    id: "pt3-rw2-16",
    skill: "boundaries",
    d: "hard",
    s: "Octavia E. Butler's novel ______ published in 1979, follows a Black woman in 1976 California who is repeatedly pulled back in time to a plantation in pre-Civil War Maryland.",
    p: STEM.sec,
    c: ["*Kindred*, first", "*Kindred* first", "*Kindred*: first", "*Kindred*; first"],
    a: "C",
    e: "The title is essential ('novel Kindred'), and 'first published in 1979' is a nonessential phrase that closes with a comma before 'follows,' so it must open with a comma.",
  },
  {
    id: "pt3-rw2-17",
    skill: "boundaries",
    d: "hard",
    s: "Some of the most detailed records of daily life in ancient Egypt come not from monuments but from ______ pieces of broken pottery and limestone that workers used as scrap paper for notes, sketches, and receipts.",
    p: STEM.sec,
    c: ["ostraca:", "ostraca;", "ostraca", "ostraca. Pieces"],
    a: "A",
    e: "The colon introduces an explanation of what ostraca are. A semicolon would leave a fragment after it, and so would a period.",
  },
  {
    id: "pt3-rw2-18",
    skill: "boundaries",
    d: "medium",
    s: "The leatherback is the largest living ______ adults can weigh more than 600 kilograms.",
    p: STEM.sec,
    c: ["turtle; adults", "turtle, adults", "turtle adults", "turtle; and adults"],
    a: "B",
    e: "Two independent clauses meet here, so a semicolon joins them. A comma alone is a comma splice, and a semicolon should not be followed by 'and.'",
  },
  {
    id: "pt3-rw2-19",
    skill: "boundaries",
    d: "hard",
    s: "The competition's three finalists--a sculptor from Lagos, a painter from Lima, and a photographer from ______ will show their work at the museum next month.",
    p: STEM.sec,
    c: ["Seoul--", "Seoul,", "Seoul", "Seoul;"],
    a: "D",
    e: "The list is set off by a dash after 'finalists,' so it must close with a dash before the verb 'will show.'",
  },
  {
    id: "pt3-rw2-20",
    skill: "subject-verb",
    d: "hard",
    s: "The findings of the study, which surveyed more than 3,000 households across nine provinces, ______ that access to clean water improved significantly over the previous decade.",
    p: STEM.sec,
    c: ["suggest", "suggests", "has suggested", "is suggesting"],
    a: "C",
    e: "The subject is 'findings,' which is plural. The singular nouns 'study' and 'households' sit inside modifiers, so the verb is 'suggest.'",
  },
  {
    id: "pt3-rw2-21",
    skill: "form-structure-sense",
    d: "medium",
    s: "Though the two species of finch look nearly identical, each has a beak shaped for ______ own preferred food: one cracks hard seeds, while the other probes flowers for nectar.",
    p: STEM.sec,
    c: ["its", "their", "it's", "they're"],
    a: "A",
    e: "The antecedent is 'each,' which is singular, so the possessive is 'its.' 'It's' means 'it is.'",
  },
  {
    id: "pt3-rw2-22",
    skill: "form-structure-sense",
    d: "hard",
    s: "By the time astronomers observed the planet Neptune for the first time in 1846, mathematicians ______ its position from small irregularities in the orbit of Uranus.",
    p: STEM.sec,
    c: ["had already predicted", "already predict", "will have already predicted", "are already predicting"],
    a: "B",
    e: "The prediction came before another past event, the 1846 observation, so the past perfect 'had already predicted' is needed.",
  },
  {
    id: "pt3-rw2-23",
    skill: "transitions",
    d: "hard",
    s: "Early critics dismissed the photographer's images of ordinary street scenes as unworthy of serious attention. Today, ______ those same images hang in major museums and are studied as essential records of twentieth-century city life.",
    p: STEM.transition,
    c: ["by contrast,", "similarly,", "for this reason,", "in addition,"],
    a: "D",
    e: "Present-day acclaim is the opposite of early dismissal, so a contrasting transition fits. The dismissal is not the reason for the acclaim.",
  },
  {
    id: "pt3-rw2-24",
    skill: "transitions",
    d: "medium",
    s: "Large volcanic eruptions can cool the global climate by releasing sulfur particles that reflect sunlight back into space. The 1991 eruption of Mount Pinatubo in the Philippines, ______ lowered average global temperatures by about 0.5{deg}C over the following year.",
    p: STEM.transition,
    c: ["for example,", "however,", "in contrast,", "meanwhile,"],
    a: "C",
    e: "Pinatubo is an instance of the cooling effect the first sentence describes, so 'for example' fits.",
  },
  {
    id: "pt3-rw2-25",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "The Hubble Space Telescope observes mainly visible and ultraviolet light.",
      "The James Webb Space Telescope, launched in 2021, observes mainly infrared light.",
      "Infrared light can pass through clouds of dust that block visible light.",
      "As a result, Webb can observe stars forming inside dusty regions.",
    ),
    p: goal("explain an advantage of the James Webb Space Telescope's design."),
    c: [
      "Because the James Webb Space Telescope observes mainly infrared light, which passes through dust that blocks visible light, it can observe stars forming inside dusty regions.",
      "The James Webb Space Telescope was launched in 2021.",
      "While the Hubble Space Telescope observes mainly visible and ultraviolet light, the James Webb Space Telescope observes mainly infrared light.",
      "Infrared light can pass through clouds of dust.",
    ],
    a: "A",
    e: "An advantage needs the design feature and what it makes possible. The Hubble comparison states a difference but not the benefit.",
  },
  {
    id: "pt3-rw2-26",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "In 1928, Alexander Fleming noticed that a mold contaminating one of his bacterial cultures had killed the bacteria around it.",
      "The mold produced a substance Fleming named penicillin.",
      "Fleming was unable to produce penicillin in large quantities.",
      "In the early 1940s, Howard Florey and Ernst Chain developed ways to purify and mass-produce it.",
    ),
    p: goal("emphasize that making penicillin a practical medicine required the work of more than one researcher."),
    c: [
      "Although Alexander Fleming discovered penicillin in 1928, it was Howard Florey and Ernst Chain who, in the early 1940s, found ways to purify and mass-produce it.",
      "In 1928, Alexander Fleming noticed that a mold had killed the bacteria in one of his cultures.",
      "Alexander Fleming named the substance produced by the mold penicillin.",
      "Howard Florey and Ernst Chain worked on penicillin in the early 1940s.",
    ],
    a: "C",
    e: "The first choice shows both halves--Fleming's discovery and the others' work making it usable. The rest mention one contribution only.",
  },
  {
    id: "pt3-rw2-27",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "Frida Kahlo was a Mexican painter born in 1907.",
      "She painted about 55 self-portraits.",
      "Many of her works draw on Mexican folk art.",
      "Her 1939 painting *The Two Fridas* shows two versions of the artist seated side by side, holding hands.",
    ),
    p: goal("describe *The Two Fridas* to an audience unfamiliar with it."),
    c: [
      "*The Two Fridas* (1939), a painting by the Mexican artist Frida Kahlo, shows two versions of the artist seated side by side, holding hands.",
      "Frida Kahlo, who was born in 1907, painted about 55 self-portraits.",
      "Many of Frida Kahlo's works draw on Mexican folk art.",
      "Frida Kahlo was a Mexican painter.",
    ],
    a: "D",
    e: "Only the first choice names the painting, its artist, and what it shows. The others do not mention the painting at all.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 1                                                      */
/* ------------------------------------------------------------------ */

export const PT3_M1 = build([
  {
    id: "pt3-m1-01",
    skill: "linear-eq-1var",
    d: "easy",
    p: "If 7 - 2x = 15, what is the value of x?",
    c: ["-4", "4", "-11", "11"],
    a: "B",
    e: "Subtract 7: -2x = 8. Divide by -2: x = -4.",
  },
  {
    id: "pt3-m1-02",
    skill: "percentages",
    d: "easy",
    p: "A shirt that originally cost $40 is on sale for 25% off. What is the sale price of the shirt?",
    c: ["$30", "$10", "$15", "$35"],
    a: "A",
    e: "25% of $40 is $10, so the sale price is $40 - $10 = $30. ($10 is the discount, not the price.)",
  },
  {
    id: "pt3-m1-03",
    skill: "equivalent-expressions",
    d: "easy",
    p: "Which expression is equivalent to (4x^2 + 3x) - (x^2 - 5x)?",
    c: ["3x^2 + 8x", "3x^2 - 2x", "5x^2 + 8x", "3x^2 + 2x"],
    a: "D",
    e: "Distribute the subtraction: 4x^2 + 3x - x^2 + 5x = 3x^2 + 8x.",
  },
  {
    id: "pt3-m1-04",
    skill: "lines-angles-triangles",
    d: "easy",
    p: "In triangle ABC, AB = AC and the measure of angle A is 50{deg}. What is the measure of angle B?",
    c: ["65{deg}", "50{deg}", "80{deg}", "130{deg}"],
    a: "C",
    e: "Since AB = AC, angles B and C are equal. They share 180 - 50 = 130 degrees, so each is 65 degrees.",
  },
  {
    id: "pt3-m1-05",
    skill: "linear-eq-2var",
    d: "easy",
    p: "A gym charges a one-time fee of $25 to join plus $30 per month. Kiara has paid the gym a total of $265. For how many months has she been a member?",
    a: "8",
    e: "25 + 30m = 265, so 30m = 240 and m = 8.",
  },
  {
    id: "pt3-m1-06",
    skill: "data-distributions",
    d: "easy",
    fig: {
      kind: "table",
      head: ["Month", "March", "April", "May", "June", "July"],
      rows: [["Days with rain", "8", "12", "10", "6", "4"]],
      rowHeaders: true,
    },
    p: "The table shows the number of days with rain in a city in each of five months. What is the mean number of days with rain per month?",
    c: ["8", "6", "8.5", "12"],
    a: "A",
    e: "The total is 8 + 12 + 10 + 6 + 4 = 40, and 40/5 = 8.",
  },
  {
    id: "pt3-m1-07",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-2, 6, 1],
      y: [-2, 8, 1],
      series: [{ type: "fn", f: (x) => -2 * x + 6 }],
      alt: "A line crossing the y-axis at 6 and the x-axis at 3.",
    },
    p: "The graph of line {l} is shown in the xy-plane. Which equation defines line {l}?",
    c: ["y = -2x + 6", "y = 2x + 6", "y = -(1/2)x + 6", "y = -2x + 3"],
    a: "B",
    e: "The line crosses the y-axis at 6 and the x-axis at 3, so its slope is (0 - 6)/(3 - 0) = -2. The equation is y = -2x + 6.",
  },
  {
    id: "pt3-m1-08",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The function f is defined by f(x) = 2x^2 - 3x. Which expression is equivalent to f(x + 1)?",
    c: ["2x^2 + x - 1", "2x^2 - 3x + 1", "2x^2 + 4x - 1", "2x^2 + x + 5"],
    a: "C",
    e: "f(x + 1) = 2(x + 1)^2 - 3(x + 1) = 2x^2 + 4x + 2 - 3x - 3 = 2x^2 + x - 1.",
  },
  {
    id: "pt3-m1-09",
    skill: "ratios-rates",
    d: "medium",
    p: "A faucet leaks 12 milliliters of water per minute. At this rate, how many liters of water will leak from the faucet in one day? (1 liter = 1,000 milliliters)",
    c: ["17.28", "1.728", "0.72", "172.8"],
    a: "D",
    e: "One day has 24 {times} 60 = 1,440 minutes. 12 {times} 1,440 = 17,280 milliliters, which is 17.28 liters.",
  },
  {
    id: "pt3-m1-10",
    skill: "systems-linear",
    d: "medium",
    s: "y = 3x - 1\ny = -x + 7",
    p: "The solution to the given system of equations is (x, y). What is the value of x + y?",
    a: "7",
    e: "Set 3x - 1 = -x + 7, so 4x = 8 and x = 2. Then y = 5, and x + y = 7.",
  },
  {
    id: "pt3-m1-11",
    skill: "exponential",
    d: "medium",
    fig: {
      kind: "table",
      head: ["x", "0", "1", "2"],
      rows: [["f(x)", "5", "15", "45"]],
      rowHeaders: true,
    },
    p: "For the exponential function f, the table shows three values of x and their corresponding values of f(x). What is the value of f(4)?",
    a: "405",
    e: "f(0) = 5 and each step multiplies by 3, so f(x) = 5(3)^{x}. Then f(4) = 5 {times} 81 = 405.",
  },
  {
    id: "pt3-m1-12",
    skill: "circles",
    d: "medium",
    p: "A circle has a radius of 6. What is the area of a sector of the circle with a central angle of 120{deg}?",
    c: ["12{pi}", "4{pi}", "6{pi}", "36{pi}"],
    a: "A",
    e: "120 degrees is 1/3 of the circle, whose area is {pi}(6)^2 = 36{pi}. The sector's area is 36{pi}/3 = 12{pi}.",
  },
  {
    id: "pt3-m1-13",
    skill: "inference",
    d: "medium",
    fig: {
      kind: "plot",
      xLabel: "Ticket price (dollars)",
      yLabel: "Tickets sold (hundreds)",
      x: [15, 65, 5],
      y: [0, 35, 5],
      labelEvery: 2,
      series: [
        { type: "points", pts: [[20, 31], [25, 27.5], [30, 25.8], [35, 22], [40, 21], [45, 17], [50, 15.5], [55, 12], [60, 10.6]] },
        { type: "fn", f: (x) => -0.5 * x + 40, domain: [15, 65] },
      ],
      alt: "A scatterplot of tickets sold falling as ticket price rises, with a downward line of best fit.",
    },
    p: "The scatterplot shows the ticket price x, in dollars, and the number of tickets sold y, in hundreds, for nine concerts, along with the line of best fit y = -0.5x + 40. Based on the line of best fit, how many tickets would be sold for a concert with a ticket price of $50?",
    c: ["1,500", "15", "2,500", "3,500"],
    a: "C",
    e: "At x = 50, y = -0.5(50) + 40 = 15. Since y is in hundreds, that predicts 1,500 tickets.",
  },
  {
    id: "pt3-m1-14",
    skill: "linear-inequalities",
    d: "medium",
    p: "Jamal wants to save at least $600. He has already saved $150 and plans to save $45 each week. Which inequality can be used to find the number of weeks, w, after which Jamal will have saved at least $600?",
    c: ["150 + 45w >= 600", "45 + 150w >= 600", "150 + 45w <= 600", "150w + 45 <= 600"],
    a: "B",
    e: "His savings after w weeks are 150 + 45w, and he wants that to be at least 600: 150 + 45w >= 600.",
  },
  {
    id: "pt3-m1-15",
    skill: "quadratics",
    d: "medium",
    p: "What is the positive solution to the equation 2x^2 = 5x + 12?",
    a: "4",
    e: "Rewrite as 2x^2 - 5x - 12 = 0 and factor: (2x + 3)(x - 4) = 0. The solutions are -3/2 and 4; the positive one is 4.",
  },
  {
    id: "pt3-m1-16",
    skill: "lines-angles-triangles",
    d: "medium",
    fig: {
      kind: "diagram",
      w: 240,
      h: 160,
      items: [
        { t: "line", a: [0, 40], b: [240, 40] },
        { t: "line", a: [0, 120], b: [240, 120] },
        { t: "line", a: [51, 160], b: [189, 0] },
        { t: "text", at: [254, 40], s: "{l}", italic: true },
        { t: "text", at: [254, 120], s: "m", italic: true },
        { t: "text", at: [178, 29], s: "x{deg}" },
        { t: "text", at: [100, 142], s: "115{deg}" },
      ],
      note: "Note: Figure not drawn to scale.",
      alt: "Two parallel horizontal lines, l and m, cut by a transversal. The angle above line l to the right of the transversal is x degrees; the angle below line m to the right of the transversal is 115 degrees.",
    },
    p: "In the figure, line {l} is parallel to line m. What is the value of x?",
    c: ["65", "115", "55", "75"],
    a: "D",
    e: "The 115-degree angle below line m corresponds to the angle below line {l} on the same side of the transversal, which is also 115 degrees. That angle and x form a straight line, so x = 180 - 115 = 65.",
  },
  {
    id: "pt3-m1-17",
    skill: "percentages",
    d: "medium",
    p: "After a 20% increase, the price of a bicycle is $360. What was the price of the bicycle before the increase?",
    c: ["$300", "$288", "$340", "$432"],
    a: "B",
    e: "1.20p = 360, so p = 300. Taking 20% off $360 gives $288, which is the common mistake.",
  },
  {
    id: "pt3-m1-18",
    skill: "nonlinear-functions",
    d: "hard",
    p: "The function h(t) = -16t^2 + 64t + 5 gives the height, in feet, of a ball t seconds after it is thrown. What is the maximum height, in feet, that the ball reaches?",
    c: ["69", "64", "5", "2"],
    a: "A",
    e: "The maximum is at t = -64/(2(-16)) = 2. Then h(2) = -64 + 128 + 5 = 69 feet. (2 is the time, not the height.)",
  },
  {
    id: "pt3-m1-19",
    skill: "linear-functions",
    d: "hard",
    p: "In the xy-plane, the line kx + 3y = 9, where k is a constant, is perpendicular to the line y = (3/4)x - 2. What is the value of k?",
    a: "4",
    e: "The line kx + 3y = 9 has slope -k/3. Perpendicular to slope 3/4 means slope -4/3, so -k/3 = -4/3 and k = 4.",
  },
  {
    id: "pt3-m1-20",
    skill: "area-volume",
    d: "hard",
    p: "A right circular cone has a height of 12 centimeters and a slant height of 13 centimeters. What is the volume of the cone, in cubic centimeters?",
    c: ["100{pi}", "300{pi}", "65{pi}", "260{pi}"],
    a: "C",
    e: "The radius, height, and slant height form a right triangle: r = {sqrt}(13^2 - 12^2) = 5. V = (1/3){pi}r^2h = (1/3){pi}(25)(12) = 100{pi}.",
  },
  {
    id: "pt3-m1-21",
    skill: "equivalent-expressions",
    d: "hard",
    p: "If x^2 - y^2 = 48 and x + y = 12, what is the value of x - y?",
    a: "4",
    e: "x^2 - y^2 = (x + y)(x - y), so 48 = 12(x - y) and x - y = 4.",
  },
  {
    id: "pt3-m1-22",
    skill: "quadratics",
    d: "hard",
    p: "For the function f(x) = x^2 + bx + c, where b and c are constants, f(1) = 0 and f(5) = 0. What is the minimum value of f(x)?",
    c: ["-4", "3", "-3", "4"],
    a: "C",
    e: "The zeros are 1 and 5, so f(x) = (x - 1)(x - 5). The minimum is midway, at x = 3: f(3) = (2)(-2) = -4.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 2 (harder)                                             */
/* ------------------------------------------------------------------ */

export const PT3_M2 = build([
  {
    id: "pt3-m2-01",
    skill: "linear-eq-1var",
    d: "medium",
    p: "If 3x + 4 = 2x - 5, what is the value of 2x?",
    c: ["-18", "-9", "-1", "18"],
    a: "C",
    e: "Subtract 2x and 4 from both sides: x = -9. So 2x = -18.",
  },
  {
    id: "pt3-m2-02",
    skill: "ratios-rates",
    d: "medium",
    p: "The ratio of boys to girls in a club is 4 to 5. If the club has 36 members, how many of the members are girls?",
    c: ["20", "16", "25", "9"],
    a: "A",
    e: "The ratio has 4 + 5 = 9 parts, so each part is 36/9 = 4 members. Girls: 5 {times} 4 = 20.",
  },
  {
    id: "pt3-m2-03",
    skill: "equivalent-expressions",
    d: "medium",
    p: "Which expression is equivalent to (x^3y^2)^2 / (x^2y), where x and y are positive?",
    c: ["x^{4}y^{3}", "x^{3}y", "x^{4}y", "x^{8}y^{3}"],
    a: "B",
    e: "(x^3y^2)^2 = x^{6}y^{4}. Dividing by x^2y subtracts exponents: x^{6 - 2}y^{4 - 1} = x^{4}y^{3}.",
  },
  {
    id: "pt3-m2-04",
    skill: "area-volume",
    d: "medium",
    p: "A square has a diagonal of length 10{sqrt}2. What is the area of the square?",
    c: ["100", "50", "200", "10{sqrt}2"],
    a: "B",
    e: "A square's diagonal is its side times {sqrt}2, so the side is 10 and the area is 10^2 = 100.",
  },
  {
    id: "pt3-m2-05",
    skill: "linear-functions",
    d: "medium",
    fig: {
      kind: "table",
      head: ["Time (minutes)", "0", "4", "10"],
      rows: [["Water in tank (gallons)", "180", "156", "120"]],
      rowHeaders: true,
    },
    p: "A tank is drained at a constant rate. The table shows the amount of water in the tank at three times. How many minutes after draining begins will the tank be empty?",
    a: "30",
    e: "The water falls 24 gallons in 4 minutes, a rate of 6 gallons per minute. 180 gallons will take 180/6 = 30 minutes.",
  },
  {
    id: "pt3-m2-06",
    skill: "data-distributions",
    d: "hard",
    p: "A data set of 9 numbers has a mean of 20. When one number is removed, the remaining 8 numbers have a mean of 18. What number was removed?",
    c: ["36", "2", "20", "38"],
    a: "D",
    e: "The original total is 9 {times} 20 = 180, and the new total is 8 {times} 18 = 144. The removed number is 180 - 144 = 36.",
  },
  {
    id: "pt3-m2-07",
    skill: "exponential",
    d: "hard",
    p: "The function f(t) = 900(1.2)^{t/5} models the number of members of an online forum t years after it was founded. Which of the following functions is equivalent to f and shows the approximate yearly percent increase as a constant?",
    c: ["f(t) = 900(1.037)^{t}", "f(t) = 900(1.04)^{t/5}", "f(t) = 900(1.2)^{t}", "f(t) = 900(1.24)^{t}"],
    a: "A",
    e: "(1.2)^{t/5} = ((1.2)^{1/5})^{t}, and (1.2)^{1/5} is about 1.037. So f(t) is about 900(1.037)^{t}: roughly 3.7% growth each year.",
  },
  {
    id: "pt3-m2-08",
    skill: "systems-linear",
    d: "hard",
    s: "2x - 5y = 7\n6x + cy = 20",
    p: "In the given system of equations, c is a constant. For what value of c does the system have no solution?",
    a: "-15",
    e: "Tripling the first equation gives 6x - 15y = 21. With c = -15 the left sides match but 21 != 20, so the lines are parallel and distinct: no solution.",
  },
  {
    id: "pt3-m2-09",
    skill: "circles",
    d: "hard",
    p: "The equation x^2 + y^2 + 10x - 4y + 20 = 0 defines a circle in the xy-plane. What are the coordinates of the center of the circle?",
    c: ["(-5, 2)", "(5, -2)", "(-10, 4)", "(-5, -2)"],
    a: "C",
    e: "Complete the square: (x + 5)^2 + (y - 2)^2 = -20 + 25 + 4 = 9. The center is (-5, 2) and the radius is 3.",
  },
  {
    id: "pt3-m2-10",
    skill: "inference",
    d: "medium",
    p: "A company randomly selected 150 of its 6,000 customers and asked whether they would switch to a new service plan. Of those selected, 18 said yes. Based on this survey, which is the best estimate of the number of the company's 6,000 customers who would say they would switch?",
    c: ["720", "18", "900", "5,280"],
    a: "B",
    e: "In the sample, 18/150 = 12% would switch. 12% of 6,000 is 720.",
  },
  {
    id: "pt3-m2-11",
    skill: "quadratics",
    d: "hard",
    p: "The function g is defined by g(x) = ax^2 + 12x + 5, where a is a constant. The graph of y = g(x) in the xy-plane has its vertex at x = 3. What is the value of a?",
    a: "-2",
    e: "The vertex is at x = -b/(2a) = -12/(2a). Setting -12/(2a) = 3 gives 2a = -4, so a = -2.",
  },
  {
    id: "pt3-m2-12",
    skill: "linear-functions",
    d: "hard",
    p: "Line {l} in the xy-plane passes through the points (-1, 4) and (3, -4). Which equation defines a line that is parallel to line {l}?",
    c: ["4x + 2y = 7", "2x - y = 5", "x + 2y = 1", "x - 2y = 3"],
    a: "D",
    e: "Line {l} has slope (-4 - 4)/(3 - (-1)) = -2. Rewriting 4x + 2y = 7 as y = -2x + 7/2 gives slope -2, so it is parallel. The others have slopes 2, -1/2, and 1/2.",
  },
  {
    id: "pt3-m2-13",
    skill: "right-triangles-trig",
    d: "hard",
    p: "For acute angles measuring x{deg} and y{deg}, sin(x{deg}) = cos(y{deg}). If x = 3k + 10 and y = 2k - 5, what is the value of k?",
    a: "17",
    e: "For acute angles, sin x = cos y exactly when x + y = 90. So 3k + 10 + 2k - 5 = 90, giving 5k = 85 and k = 17.",
  },
  {
    id: "pt3-m2-14",
    skill: "nonlinear-functions",
    d: "hard",
    p: "What is the solution to the equation 3/(x - 2) = x/(x - 2) + 1?",
    c: ["5/2", "2", "1", "There is no solution."],
    a: "C",
    e: "Multiply every term by (x - 2): 3 = x + (x - 2), so 2x = 5 and x = 5/2. This does not make any denominator zero, so it is a valid solution.",
  },
  {
    id: "pt3-m2-15",
    skill: "percentages",
    d: "hard",
    p: "In 2019, 35% of a company's 1,200 employees worked remotely. In 2021, the company had 1,500 employees, and 60% of them worked remotely. By approximately what percent did the number of employees working remotely increase from 2019 to 2021?",
    c: ["114%", "25%", "71%", "53%"],
    a: "C",
    e: "Remote workers went from 0.35 {times} 1,200 = 420 to 0.60 {times} 1,500 = 900. The increase is 480, and 480/420 is about 1.14, a 114% increase.",
  },
  {
    id: "pt3-m2-16",
    skill: "linear-inequalities",
    d: "hard",
    p: "A bakery sells muffins for $3 each and scones for $4 each. On a given day, it must sell at least 200 items and take in at least $700. If the bakery sells 120 muffins that day, what is the minimum number of scones it must sell?",
    c: ["85", "80", "90", "100"],
    a: "B",
    e: "The item goal needs 120 + s >= 200, so s >= 80. The money goal needs 3(120) + 4s >= 700, so 4s >= 340 and s >= 85. Both must hold, so the minimum is 85.",
  },
  {
    id: "pt3-m2-17",
    skill: "equivalent-expressions",
    d: "hard",
    p: "Which expression is equivalent to (x^2 - 4)/(x^2 + 4x + 4), for x != -2?",
    c: ["(x - 2)/(x + 2)", "(x + 2)/(x - 2)", "-1", "(x - 4)/(x + 4)"],
    a: "D",
    e: "Factor: (x^2 - 4) = (x - 2)(x + 2) and x^2 + 4x + 4 = (x + 2)^2. Cancelling one factor of (x + 2) leaves (x - 2)/(x + 2).",
  },
  {
    id: "pt3-m2-18",
    skill: "circles",
    d: "hard",
    fig: {
      kind: "diagram",
      w: 200,
      h: 200,
      items: [
        { t: "circle", c: [100, 100], r: 80 },
        { t: "poly", pts: [[36, 52], [164, 52], [164, 148], [36, 148]] },
        { t: "text", at: [100, 42], s: "8" },
        { t: "text", at: [176, 100], s: "6" },
      ],
      alt: "A rectangle with sides 8 and 6 whose four corners lie on a circle.",
    },
    p: "A rectangle with side lengths 8 and 6 is inscribed in a circle, as shown. What is the area of the circle?",
    c: ["25{pi}", "100{pi}", "10{pi}", "48{pi}"],
    a: "A",
    e: "The rectangle's diagonal is a diameter of the circle: {sqrt}(8^2 + 6^2) = 10. So the radius is 5 and the area is 25{pi}.",
  },
  {
    id: "pt3-m2-19",
    skill: "probability",
    d: "hard",
    p: "In a class of 30 students, 18 play a sport, 12 play a musical instrument, and 7 do both. If a student who plays a musical instrument is selected at random, what is the probability that the student also plays a sport?",
    c: ["7/12", "7/18", "7/30", "2/5"],
    a: "C",
    e: "Restrict to the 12 students who play an instrument; 7 of them also play a sport. The probability is 7/12.",
  },
  {
    id: "pt3-m2-20",
    skill: "nonlinear-functions",
    d: "medium",
    p: "For x > 0, if (x^2 + 5x)/x = 2x - 1, what is the value of x?",
    c: ["6", "4", "1", "5"],
    a: "D",
    e: "For x > 0, (x^2 + 5x)/x = x + 5. So x + 5 = 2x - 1, and x = 6.",
  },
  {
    id: "pt3-m2-21",
    skill: "quadratics",
    d: "hard",
    p: "In the xy-plane, the graph of y = x^2 - 6x + k, where k is a constant, and the graph of y = -2 have exactly one point in common. What is the value of k?",
    a: "7",
    e: "The parabola touches y = -2 only at its vertex, x = 3. So 9 - 18 + k = -2, and k = 7. (Equivalently, x^2 - 6x + k + 2 = 0 has discriminant 36 - 4(k + 2) = 0.)",
  },
  {
    id: "pt3-m2-22",
    skill: "right-triangles-trig",
    d: "hard",
    p: "In the xy-plane, an angle with its vertex at the origin has its initial side on the positive x-axis and its terminal side passing through the point (6, 8). What is the cosine of the angle?",
    a: "3/5",
    alt: ["0.6", ".6"],
    e: "The point (6, 8) is {sqrt}(6^2 + 8^2) = 10 units from the origin. The cosine is the x-coordinate divided by that distance: 6/10 = 3/5.",
  },
]);
