/**
 * Practice Test 4. See `pt1.ts` for how the practice tests are written.
 *
 * The hardest of the four: its harder Module 2s lean further toward the top
 * of the difficulty range, for students aiming at the upper end of the scale.
 */

import { STEM, goal, notes, q, texts, type QSpec } from "./author";

const F = "pt4";
const build = (specs: QSpec[]) => specs.map((s) => q(s, F));

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 1                                       */
/* ------------------------------------------------------------------ */

export const PT4_RW1 = build([
  {
    id: "pt4-rw1-01",
    skill: "words-in-context",
    d: "easy",
    s: "Because the bridge's original design could not ______ the weight of modern trucks, engineers reinforced it with steel beams in 1998.",
    p: STEM.wic,
    c: ["support", "measure", "resemble", "attract"],
    a: "A",
    e: "The bridge had to be reinforced because it could not bear, or support, heavy trucks. The other verbs do not describe carrying a load.",
  },
  {
    id: "pt4-rw1-02",
    skill: "words-in-context",
    d: "medium",
    s: "Long regarded as a minor figure, the painter has been ______ by recent scholarship, which places her at the center of the movement she was once thought merely to have imitated.",
    p: STEM.wic,
    c: ["elevated", "dismissed", "imitated", "concealed"],
    a: "D",
    e: "Moving from 'minor figure' to 'the center of the movement' is a rise in standing: she has been elevated. 'Dismissed' describes her earlier treatment.",
  },
  {
    id: "pt4-rw1-03",
    skill: "words-in-context",
    d: "medium",
    s: "Unlike her earlier novels, which unfold over decades, Reyes's latest book is ______ in scope, covering just a single afternoon in one family's kitchen.",
    p: STEM.wic,
    c: ["limited", "sweeping", "ambitious", "uncertain"],
    a: "C",
    e: "One afternoon in one kitchen, set against novels spanning decades, is a narrow or limited scope. 'Sweeping' describes the earlier novels.",
  },
  {
    id: "pt4-rw1-04",
    skill: "words-in-context",
    d: "hard",
    s: "The historian argues that the treaty's significance has been ______: though often described as a turning point, it changed little in practice, since both sides continued to ignore its terms.",
    p: STEM.wic,
    c: ["overstated", "overlooked", "questioned", "documented"],
    a: "B",
    e: "Called a turning point but changing little, the treaty's importance has been exaggerated, or overstated. 'Overlooked' would mean its importance has been missed, the opposite.",
  },
  {
    id: "pt4-rw1-05",
    skill: "text-structure",
    d: "medium",
    s: "A newborn rattlesnake has only a small 'button' at the tip of its tail. Each time the snake sheds its skin, a new segment is added to the rattle. Because snakes may shed several times a year, and because segments often break off, the number of segments reveals little about a rattlesnake's age--despite a popular belief to the contrary.",
    p: STEM.purpose,
    c: [
      "To explain how a rattlesnake's rattle forms and why it is an unreliable indicator of the snake's age",
      "To describe how rattlesnakes use their rattles to warn predators",
      "To argue that rattlesnakes shed their skin more often than other snakes",
      "To explain how scientists determine the ages of wild rattlesnakes",
    ],
    a: "D",
    e: "The text describes how segments are added and then explains why counting them does not reveal age. It does not discuss warnings, compare species, or describe how age is actually measured.",
  },
  {
    id: "pt4-rw1-06",
    skill: "text-structure",
    d: "medium",
    s: "Economists often gauge a country's prosperity by its gross domestic product (GDP), the total value of the goods and services it produces. [u]But GDP counts only activities that involve a market transaction.[/u] The hours a parent spends caring for a child at home, for instance, add nothing to GDP, while the same care purchased from a daycare center does.",
    p: STEM.underlined,
    c: [
      "It points out a shortcoming of the measure described in the first sentence, which the final sentence then illustrates.",
      "It explains why economists prefer GDP to other measures of prosperity.",
      "It introduces a measure that is meant to replace GDP.",
      "It restates the definition of GDP given in the first sentence.",
    ],
    a: "C",
    e: "The underlined sentence identifies what GDP leaves out, and the childcare example shows it. It does not defend GDP, propose a replacement, or merely repeat the definition.",
  },
  {
    id: "pt4-rw1-07",
    skill: "text-structure",
    d: "medium",
    s: "The following text is from a short story. Ines is waiting to hear whether she got a job.\n\nFor three days Ines checked her phone every few minutes. She rearranged her bookshelves, repainted a chair, and walked the dog so often that the dog began to hide when she reached for the leash. On the fourth morning the email arrived. She read it once, set the phone face down on the table, and went back to painting the chair.",
    p: STEM.structure,
    c: [
      "It shows a character's restless activity while she waits for news and then presents her restrained response when the news arrives.",
      "It describes a character's new job and then explains why she decides to leave it.",
      "It recounts a disagreement between a character and a friend and then describes how it ends.",
      "It describes a character's home in detail and then explains how she came to live there.",
    ],
    a: "A",
    e: "The first sentences show anxious busyness; the last shows a quiet, withheld reaction to the email. The text never reveals the job itself, and there is no second character.",
  },
  {
    id: "pt4-rw1-08",
    skill: "cross-text",
    d: "medium",
    s: texts(
      "Some urban planners argue that adding lanes to highways is the best way to reduce traffic congestion. More capacity, they reason, lets the same number of cars move more freely.",
      "Transportation researchers have documented a pattern known as induced demand. When new lanes are added, driving becomes more convenient, so people make trips they would otherwise have skipped or made by other means. Within a few years, traffic on widened highways often returns to its earlier level of congestion.",
    ),
    p: "Based on the texts, how would the researchers in Text 2 most likely respond to the planners' reasoning in Text 1?",
    c: [
      "By arguing that it overlooks how added capacity changes the number of people who choose to drive",
      "By agreeing that adding lanes permanently reduces congestion",
      "By arguing that highways should have fewer lanes than they do now",
      "By claiming that most drivers prefer public transportation to highways",
    ],
    a: "B",
    e: "The planners assume 'the same number of cars,' but induced demand means more lanes attract more driving. Text 2 says congestion returns, and it proposes no lane reduction.",
  },
  {
    id: "pt4-rw1-09",
    skill: "central-ideas",
    d: "easy",
    s: "Lichens look like single organisms, but each is actually a partnership between a fungus and an alga or a cyanobacterium. The fungus provides structure and absorbs water and minerals, while its partner uses sunlight to make food through photosynthesis. Together, they can survive on bare rock, tree bark, and other surfaces where neither could live alone.",
    p: STEM.mainIdea,
    c: [
      "Lichens are partnerships between different organisms that together can survive in places where neither partner could survive alone.",
      "Lichens are a kind of plant that grows only on tree bark.",
      "Fungi are able to perform photosynthesis on bare rock.",
      "Most algae live on bare rock without any partner.",
    ],
    a: "C",
    e: "The text explains that lichens are partnerships and what the partnership makes possible. It assigns photosynthesis to the partner, not the fungus, and says neither partner survives alone in those places.",
  },
  {
    id: "pt4-rw1-10",
    skill: "central-ideas",
    d: "medium",
    s: "The following text is from a novel. Walter has just retired after thirty years as a train conductor.\n\nOn his first free Monday, Walter rose at five, as always, and put on a pressed shirt. He had nowhere to be. He made coffee, sat at the kitchen table, and listened to the 6:12 pass on the far side of the valley, its horn sounding twice at the crossing. He found himself checking his watch. Right on time, he thought, and felt an unexpected pang that it had managed without him.",
    p: STEM.mainIdea,
    c: [
      "Walter keeps his old habits after retiring and feels a twinge of sadness that the trains run perfectly well without him.",
      "Walter is relieved that he no longer has to wake up early.",
      "Walter regrets that he never became a train conductor.",
      "Walter is angry that the train was late on his first day of retirement.",
    ],
    a: "B",
    e: "He wakes at five and dresses as if for work, and the on-time train gives him a 'pang' that it did not need him. The train is on time, and nothing suggests relief.",
  },
  {
    id: "pt4-rw1-11",
    skill: "command-evidence",
    d: "medium",
    s: "Plant biologist Yusuf Adebayo hypothesizes that tomato plants attacked by caterpillars release airborne chemicals that cause nearby tomato plants to strengthen their defenses before any caterpillars reach them.",
    p: "Which finding, if true, would most directly support Adebayo's hypothesis?",
    c: [
      "Undamaged tomato plants placed downwind of caterpillar-damaged plants produced more defensive compounds than undamaged plants placed downwind of other undamaged plants.",
      "Caterpillars ate more leaves from large tomato plants than from small ones.",
      "Tomato plants that were damaged by caterpillars grew more slowly than undamaged plants.",
      "Caterpillars were found on tomato plants in every field that was surveyed.",
    ],
    a: "D",
    e: "The hypothesis predicts that undamaged neighbors react to airborne signals from damaged plants. Comparing plants downwind of damaged versus undamaged plants tests exactly that.",
  },
  {
    id: "pt4-rw1-12",
    skill: "command-evidence",
    d: "medium",
    s: "\"Evening Tide\" is a poem about a harbor at sunset. In the poem, the speaker expresses a feeling of peace at the end of the day.",
    p: "Which quotation from \"Evening Tide\" most effectively illustrates the claim?",
    c: [
      "\"The harbor stills; the last gull folds its wings, / and all my worries loosen, one by one.\"",
      "\"The fishermen will haul their nets at dawn.\"",
      "\"A storm is building somewhere out at sea.\"",
      "\"I count the hours until the morning train.\"",
    ],
    a: "A",
    e: "A stilled harbor and worries loosening express peace. A building storm and counting the hours suggest unease or impatience instead.",
  },
  {
    id: "pt4-rw1-13",
    skill: "quantitative-evidence",
    d: "medium",
    s: "A school counselor noticed that the average time students spend on homework rose from grade 9 through grade 11 but then declined in grade 12. For example, ______",
    fig: {
      kind: "table",
      title: "Average Weekly Homework Time",
      head: ["Grade", "Hours per week"],
      rows: [["9", "6.5"], ["10", "8.0"], ["11", "9.5"], ["12", "7.0"]],
    },
    p: STEM.tableExample,
    c: [
      "average homework time rose from 6.5 hours per week in grade 9 to 9.5 hours in grade 11 and then fell to 7.0 hours in grade 12.",
      "students in grade 10 spent an average of 8.0 hours per week on homework.",
      "students in grade 12 spent more time on homework than students in grade 9 did.",
      "students in grade 11 spent the most time on homework of any grade.",
    ],
    a: "C",
    e: "The example must show both the rise and the later fall. Only the first choice traces the whole pattern; the others each give one fact.",
  },
  {
    id: "pt4-rw1-14",
    skill: "quantitative-evidence",
    d: "hard",
    s: "A researcher claims that Country B made the most progress toward renewable energy between 2000 and 2020, even though Country C still had the largest renewable share in 2020.",
    fig: {
      kind: "bar",
      title: "Share of Energy from Renewable Sources",
      yLabel: "Share (%)",
      categories: ["Country A", "Country B", "Country C"],
      series: [
        { name: "2000", values: [10, 5, 40] },
        { name: "2020", values: [18, 35, 45] },
      ],
      y: [0, 50, 10],
    },
    p: "Which choice best describes data from the graph that support the researcher's claim?",
    c: [
      "Country B's renewable share rose by 30 percentage points, more than Country A's (8) or Country C's (5), though Country C's 2020 share (45%) remained the highest.",
      "Country C had the largest renewable share in both 2000 and 2020.",
      "Country A's renewable share rose from 10% to 18%.",
      "All three countries had larger renewable shares in 2020 than in 2000.",
    ],
    a: "D",
    e: "The claim has two parts: B's gain was largest, and C still led in 2020. Only the first choice supports both. The others are true but miss B's progress.",
  },
  {
    id: "pt4-rw1-15",
    skill: "inferences",
    d: "hard",
    s: "Historians examining a medieval manuscript found that its first twenty pages were written with an ink made from a recipe that local records show was abandoned by about 1300. The remaining pages use an ink recipe that did not appear in the region until after 1350, and the handwriting on those pages differs from that on the first twenty. These findings suggest that ______",
    p: STEM.complete,
    c: [
      "the manuscript was begun by one scribe and completed by another, probably decades later.",
      "the entire manuscript was written by a single scribe in the late 1200s.",
      "the manuscript was copied from an earlier text written after 1350.",
      "the region's scribes never changed the recipes they used for ink.",
    ],
    a: "B",
    e: "Two inks from different periods and two styles of handwriting point to two stages of writing by different hands, separated by at least half a century.",
  },
  {
    id: "pt4-rw1-16",
    skill: "boundaries",
    d: "easy",
    s: "The Amazon discharges more water than any other ______ its flow accounts for roughly one-fifth of all the fresh water that rivers deliver to the oceans.",
    p: STEM.sec,
    c: ["river; its", "river, its", "river its", "river and, its"],
    a: "D",
    e: "Two independent clauses meet here, so a semicolon is needed. A comma alone creates a comma splice.",
  },
  {
    id: "pt4-rw1-17",
    skill: "boundaries",
    d: "medium",
    s: "In her memoir, the astronaut describes three features of the view from ______ the thin blue line of the atmosphere, the lights of cities at night, and the vast darkness surrounding the planet.",
    p: STEM.sec,
    c: ["orbit:", "orbit;", "orbit", "orbit, and"],
    a: "A",
    e: "A complete clause announcing 'three features' introduces the list, which a colon does.",
  },
  {
    id: "pt4-rw1-18",
    skill: "boundaries",
    d: "hard",
    s: "The results of the first clinical trial were promising. The second ______ found no significant effect.",
    p: STEM.sec,
    c: ["trial, however,", "trial however", "trial; however,", "trial, however"],
    a: "C",
    e: "'However' interrupts a single clause ('The second trial found...'), so it is set off with commas on both sides. A semicolon would split the subject from its verb.",
  },
  {
    id: "pt4-rw1-19",
    skill: "boundaries",
    d: "hard",
    s: "Scientists still debate why the Neanderthals ______",
    p: STEM.sec,
    c: ["disappeared.", "disappeared?", "disappeared?.", "had disappeared?"],
    a: "B",
    e: "The sentence is a statement that contains an indirect question ('why the Neanderthals disappeared'), so it ends with a period, not a question mark.",
  },
  {
    id: "pt4-rw1-20",
    skill: "subject-verb",
    d: "easy",
    s: "The paintings in the gallery's east wing ______ from the artist's final decade.",
    p: STEM.sec,
    c: ["date", "dates", "is dating", "has dated"],
    a: "C",
    e: "The subject is 'paintings,' which is plural, so the verb is 'date.'",
  },
  {
    id: "pt4-rw1-21",
    skill: "form-structure-sense",
    d: "medium",
    s: "Researchers asked the volunteers to record ______ sleep patterns in a journal each morning.",
    p: STEM.sec,
    c: ["their", "its", "there", "they're"],
    a: "A",
    e: "The possessive refers to 'volunteers,' a plural noun, so 'their' is correct. 'There' and 'they're' are not possessives.",
  },
  {
    id: "pt4-rw1-22",
    skill: "form-structure-sense",
    d: "hard",
    s: "The coastline of Norway is far longer than ______ because it is cut by thousands of deep fjords.",
    p: STEM.sec,
    c: ["that of Sweden", "Sweden", "Sweden's coast is", "those of Sweden"],
    a: "D",
    e: "The comparison must be between two coastlines. 'That of Sweden' stands for 'the coastline of Sweden.' 'Sweden' compares a coastline with a country, and 'those' is plural.",
  },
  {
    id: "pt4-rw1-23",
    skill: "transitions",
    d: "medium",
    s: "Most metals expand when heated. ______ bridges are built with expansion joints, gaps that allow sections of the roadway to lengthen on hot days without buckling.",
    p: STEM.transition,
    c: ["For this reason,", "However,", "Similarly,", "In contrast,"],
    a: "B",
    e: "Expansion joints exist because metal expands in heat, a cause-and-effect relationship that 'For this reason' signals.",
  },
  {
    id: "pt4-rw1-24",
    skill: "transitions",
    d: "hard",
    s: "The author's first novel sold fewer than 500 copies and received almost no reviews. Her second fared little better. ______ her third novel won a major literary prize and became an international bestseller.",
    p: STEM.transition,
    c: ["Then, unexpectedly,", "As a result,", "Likewise,", "In other words,"],
    a: "A",
    e: "The third novel's success breaks sharply from the earlier failures, and it came later in time, so 'Then, unexpectedly' fits. The failures did not cause the success.",
  },
  {
    id: "pt4-rw1-25",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "Maya Angelou (1928-2014) was an American writer and poet.",
      "Her 1969 memoir *I Know Why the Caged Bird Sings* describes her childhood.",
      "The memoir was nominated for a National Book Award.",
      "In 1993, she read her poem \"On the Pulse of Morning\" at the inauguration of President Bill Clinton.",
    ),
    p: goal("emphasize Angelou's role at a major public event."),
    c: [
      "In 1993, Maya Angelou read her poem \"On the Pulse of Morning\" at the inauguration of President Bill Clinton.",
      "Maya Angelou's 1969 memoir describes her childhood.",
      "Maya Angelou's memoir was nominated for a National Book Award.",
      "Maya Angelou was an American writer and poet who lived from 1928 to 2014.",
    ],
    a: "C",
    e: "A presidential inauguration is the public event, and only the first choice mentions it.",
  },
  {
    id: "pt4-rw1-26",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "Archaeologists have reported finding honey in ancient Egyptian tombs that was still edible.",
      "Honey has a very low water content.",
      "Its high acidity and high concentration of sugar prevent most bacteria from growing.",
      "Bees also add an enzyme that produces small amounts of hydrogen peroxide, which kills microbes.",
    ),
    p: goal("explain why honey can remain edible for a very long time."),
    c: [
      "Honey's low water content, high acidity, and high sugar concentration keep most bacteria from growing, so it can stay edible for a very long time.",
      "Archaeologists have reported finding edible honey in ancient Egyptian tombs.",
      "Bees add an enzyme to honey.",
      "Honey has a very low water content.",
    ],
    a: "D",
    e: "An explanation must connect honey's properties to its not spoiling. The tomb finding shows that it lasts but not why.",
  },
  {
    id: "pt4-rw1-27",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "A 2014 study found that students who took lecture notes by hand remembered the content better than students who typed their notes.",
      "The researchers suggested that typists tended to copy lectures word for word instead of summarizing.",
      "A 2019 attempt to replicate the study found no significant difference between the two groups.",
      "Researchers continue to debate the question.",
    ),
    p: goal("indicate that the evidence on this question is mixed."),
    c: [
      "While a 2014 study found that handwritten notes led to better recall than typed notes, a 2019 attempt to replicate it found no significant difference.",
      "A 2014 study found that students who took notes by hand remembered lectures better than students who typed.",
      "Researchers suggested that students who type their notes tend to copy lectures word for word.",
      "A 2019 study examined whether taking notes by hand improves recall.",
    ],
    a: "B",
    e: "Mixed evidence means studies that disagree. Only the first choice places the original finding beside the failed replication.",
  },
]);

/* ------------------------------------------------------------------ */
/* Reading and Writing, Module 2 (harder)                              */
/* ------------------------------------------------------------------ */

export const PT4_RW2 = build([
  {
    id: "pt4-rw2-01",
    skill: "words-in-context",
    d: "hard",
    s: "Far from being ______, the ancient road network was carefully planned: its routes followed the gentlest slopes available, and its way stations were spaced exactly one day's walk apart.",
    p: STEM.wic,
    c: ["haphazard", "deliberate", "extensive", "durable"],
    a: "B",
    e: "'Far from' signals the opposite of 'carefully planned,' which is haphazard. 'Deliberate' would mean the same as planned.",
  },
  {
    id: "pt4-rw2-02",
    skill: "words-in-context",
    d: "hard",
    s: "The scientist's tone in the paper is notably ______: although her data strongly support the hypothesis, she repeatedly cautions that further studies are needed before any firm conclusions can be drawn.",
    p: STEM.wic,
    c: ["circumspect", "triumphant", "dismissive", "cavalier"],
    a: "D",
    e: "Repeatedly cautioning against firm conclusions despite strong data is careful and wary: circumspect. 'Triumphant' and 'cavalier' suggest overconfidence.",
  },
  {
    id: "pt4-rw2-03",
    skill: "words-in-context",
    d: "hard",
    s: "The festival's organizers hoped the new venue would ______ the overcrowding that had plagued earlier years, and attendance records suggest it did: despite record crowds, waits at the entrances were shorter than ever.",
    p: STEM.wic,
    c: ["alleviate", "intensify", "commemorate", "disregard"],
    a: "A",
    e: "Shorter waits despite bigger crowds show that the venue eased, or alleviated, the overcrowding.",
  },
  {
    id: "pt4-rw2-04",
    skill: "words-in-context",
    d: "hard",
    s: "Although the author's prose is spare, her novels are anything but ______: each packs generations of family history, several interwoven plots, and dozens of vividly drawn characters into fewer than 250 pages.",
    p: STEM.wic,
    c: ["insubstantial", "concise", "lengthy", "ornate"],
    a: "C",
    e: "Novels packed with history, plots, and characters are full and weighty, so they are anything but insubstantial. They are concise (under 250 pages), so saying they are 'anything but concise' would contradict the text.",
  },
  {
    id: "pt4-rw2-05",
    skill: "text-structure",
    d: "hard",
    s: "In 1854, when cholera swept through the Soho district of London, most physicians believed the disease spread through 'miasma,' or bad air. Physician John Snow was skeptical. By mapping the homes of people who had died, he showed that cases clustered around a single water pump on Broad Street, and he persuaded local officials to remove the pump's handle. Snow's map is now regarded as a founding document of epidemiology.",
    p: STEM.purpose,
    c: [
      "To describe how a physician used a new method to challenge a widely held theory about how a disease spread",
      "To explain why cholera was more common in London than in other cities",
      "To argue that most physicians in 1854 were poorly trained",
      "To describe the design of London's water system in the 1800s",
    ],
    a: "B",
    e: "The text sets Snow's mapping against the miasma theory and notes the method's lasting importance. It makes no comparison of cities, no judgment of physicians' training, and no survey of the water system.",
  },
  {
    id: "pt4-rw2-06",
    skill: "text-structure",
    d: "hard",
    s: "The following text is from a novel.\n\nHarriet had always told herself that she stayed in the town for her mother's sake. [u]It was a comfortable story, and it had the advantage of being partly true.[/u] But her mother had been gone for six years now, and Harriet was still here, still renting the same narrow flat above the pharmacy.",
    p: STEM.underlined,
    c: [
      "It suggests that Harriet's explanation for staying is incomplete, preparing for the evidence in the next sentence that it does not fully account for her choice.",
      "It confirms that Harriet's only reason for staying in the town was her mother.",
      "It introduces a new character whose arrival changes Harriet's plans.",
      "It describes the town in which Harriet lives.",
    ],
    a: "A",
    e: "Calling the explanation 'comfortable' and only 'partly true' hints that it is not the whole story, and the next sentence shows she stayed long after her mother died.",
  },
  {
    id: "pt4-rw2-07",
    skill: "text-structure",
    d: "hard",
    s: "Why do zebras have stripes? Researchers have proposed many explanations, including camouflage, temperature regulation, and social signaling. One has recently gained strong support. Biologist Tim Caro and colleagues found that biting flies land far less often on striped surfaces than on solid ones, and that zebra stripes are most pronounced where such flies are most abundant. Although other functions have not been ruled out, protection from flies now appears to be the best-supported explanation.",
    p: STEM.structure,
    c: [
      "It poses a question, notes several proposed answers, presents evidence favoring one of them, and ends with a qualified assessment.",
      "It describes an experiment, reports that its results were inconclusive, and calls for further research.",
      "It compares zebras with other striped animals and concludes that stripes serve the same function in all of them.",
      "It presents a widely accepted explanation and then shows that it is false.",
    ],
    a: "D",
    e: "The text asks why zebras have stripes, lists candidate answers, gives evidence for the fly explanation, and closes with a hedged verdict. The results are presented as strong, and no other animals are discussed.",
  },
  {
    id: "pt4-rw2-08",
    skill: "cross-text",
    d: "hard",
    s: texts(
      "Many ecologists advocate removing invasive species wherever possible, arguing that introduced plants and animals almost always harm the native ecosystems they enter.",
      "Ecologist Mariana Costa has documented cases in which introduced species have come to play valuable roles in their new ecosystems. In some Hawaiian forests, for example, introduced birds now disperse the seeds of native plants whose original seed dispersers have gone extinct. Costa argues that decisions about removal should be made case by case, based on what a species actually does rather than on where it came from.",
    ),
    p: "Based on the texts, how would Costa (Text 2) most likely respond to the position described in Text 1?",
    c: [
      "By arguing that it rests on a generalization that does not hold in every case, and that a species' effects, not its origin, should determine whether it is removed",
      "By agreeing that all introduced species should be removed as quickly as possible",
      "By claiming that native species are generally less valuable than introduced ones",
      "By arguing that the extinction of native seed dispersers was caused by introduced birds",
    ],
    a: "C",
    e: "Costa's Hawaiian example is a counterexample to 'almost always harm,' and she explicitly calls for case-by-case decisions based on effects. She does not rank species by origin or blame the birds for the extinctions.",
  },
  {
    id: "pt4-rw2-09",
    skill: "central-ideas",
    d: "hard",
    s: "Honeybee swarms make collective decisions with remarkable accuracy. When a swarm must choose a new nest site, scout bees inspect candidate cavities and return to perform dances advertising them; the better the site, the longer and more vigorous the dance. Scouts that visit weaker sites dance less and eventually stop, while support for the best site builds on itself. Biologist Thomas Seeley has argued that this process--independent assessment, open competition among options, and gradual agreement--offers useful lessons for how human groups make decisions.",
    p: STEM.mainIdea,
    c: [
      "A researcher suggests that the way honeybee swarms choose nest sites could offer lessons for decision-making in human groups.",
      "Honeybee scouts always choose the nest site closest to their original hive.",
      "Human groups make decisions more accurately than honeybee swarms do.",
      "Scout bees that find weak nest sites dance longer than those that find strong ones.",
    ],
    a: "A",
    e: "The text explains the swarm's process in order to set up Seeley's point about what people can learn from it. The text says scouts at weaker sites dance less, and it never mentions distance.",
  },
  {
    id: "pt4-rw2-10",
    skill: "central-ideas",
    d: "hard",
    s: "The following text is from a novel. Min-jun has been learning to paint from his grandfather.\n\nHis grandfather rarely praised him. When Min-jun finished a painting, the old man would study it in silence for a long time and then point, with the end of his brush, to a single place on the paper--a leaf, a shadow, a stroke of water. He never explained. It took Min-jun years to understand that his grandfather was not pointing to his mistakes but to the one place in each painting where he had stopped trying to impress anyone.",
    p: STEM.mainIdea,
    c: [
      "Min-jun eventually realizes that his grandfather's silent gestures singled out the most genuine part of each of his paintings.",
      "Min-jun's grandfather criticized every painting Min-jun made.",
      "Min-jun gave up painting because his grandfather never praised him.",
      "Min-jun's grandfather preferred paintings of leaves and water to other subjects.",
    ],
    a: "D",
    e: "The passage turns on Min-jun's late understanding that the pointing marked where he painted honestly, not where he failed. It says the pointing was not criticism.",
  },
  {
    id: "pt4-rw2-11",
    skill: "command-evidence",
    d: "hard",
    s: "Some paleontologists have proposed that the unusually large eyes of ichthyosaurs, marine reptiles that lived during the age of dinosaurs, were an adaptation for hunting in the dim light of the deep sea.",
    p: "Which finding, if true, would most directly weaken this proposal?",
    c: [
      "Ichthyosaur bones show none of the damage typically caused by repeated deep dives, and fossilized stomach contents consist mostly of prey that lived near the ocean's surface.",
      "Some modern deep-diving whales have relatively small eyes.",
      "Ichthyosaur eyes were supported by rings of bone.",
      "Fossils of deep-sea fish have been found alongside ichthyosaur remains.",
    ],
    a: "B",
    e: "If ichthyosaurs neither dove deep nor ate deep-sea prey, their large eyes are unlikely to be for deep-sea hunting. Deep-sea fish found with them would support the proposal.",
  },
  {
    id: "pt4-rw2-12",
    skill: "command-evidence",
    d: "hard",
    s: "In *The Salt Road*, a novel, the narrator repeatedly suggests that her grandfather's stories about his youth are more invention than memory.",
    p: "Which quotation from *The Salt Road* most effectively illustrates the claim?",
    c: [
      "\"Each time he told of crossing the desert, the dunes grew higher and the water scarcer, until by my twelfth birthday he had crossed it with no water at all.\"",
      "\"My grandfather was born in a village at the edge of the salt flats.\"",
      "\"He told his stories in the evenings, after the dishes were washed.\"",
      "\"I have kept his old compass on my desk for thirty years.\"",
    ],
    a: "C",
    e: "A story that grows more extreme with each telling, ending in something impossible, shows the narrator doubting its truth. The other lines describe him without questioning his stories.",
  },
  {
    id: "pt4-rw2-13",
    skill: "quantitative-evidence",
    d: "hard",
    s: "An agronomist argues that although Type 2 fertilizer produced the highest yield in a set of trials, Type 1 offers better value: it achieves most of Type 2's gain over using no fertilizer at less than half the cost.",
    fig: {
      kind: "table",
      title: "Results of Fertilizer Trials",
      head: ["Fertilizer", "Average yield (kg per plot)", "Cost per plot (dollars)"],
      rows: [
        ["None", "42", "0"],
        ["Type 1", "58", "12"],
        ["Type 2", "61", "25"],
        ["Type 3", "55", "8"],
      ],
      rowHeaders: true,
    },
    p: "Which choice most effectively uses data from the table to support the agronomist's argument?",
    c: [
      "Type 1 raised yield by 16 kilograms per plot over no fertilizer at a cost of $12, while Type 2 raised yield by 19 kilograms per plot at a cost of $25.",
      "Type 3 had the lowest cost per plot of any fertilizer tested.",
      "Type 2 produced the highest average yield, 61 kilograms per plot.",
      "Plots with no fertilizer produced an average yield of 42 kilograms.",
    ],
    a: "A",
    e: "The argument compares gains and costs: Type 1 gains 16 of Type 2's 19 kilograms for $12 against $25, less than half. The other choices do not compare Type 1 with Type 2.",
  },
  {
    id: "pt4-rw2-14",
    skill: "quantitative-evidence",
    d: "hard",
    s: "A biologist studying a bird species on two islands notes that predator controls were introduced on Island B in 1995 but never on Island A. She argues that the controls were effective, pointing out that ______",
    fig: {
      kind: "plot",
      title: "Bird Population on Two Islands",
      xLabel: "Year",
      yLabel: "Number of birds",
      x: [1990, 2020, 5],
      y: [0, 900, 100],
      labelEvery: 1,
      series: [
        { type: "polyline", label: "Island A", pts: [[1990, 800], [1995, 760], [2000, 680], [2005, 590], [2010, 480], [2015, 390], [2020, 300]] },
        { type: "polyline", label: "Island B", dashed: true, pts: [[1990, 200], [1995, 210], [2000, 290], [2005, 380], [2010, 470], [2015, 570], [2020, 650]] },
      ],
    },
    p: STEM.graphComplete,
    c: [
      "while the population on Island A fell from about 760 to about 300 birds between 1995 and 2020, the population on Island B rose from about 210 to about 650 birds over the same period.",
      "the two islands had roughly equal populations around 2010.",
      "Island A had more birds than Island B in 1990.",
      "the population on Island B rose from about 200 birds in 1990 to about 210 birds in 1995.",
    ],
    a: "C",
    e: "Supporting the controls' effect requires comparing the islands after 1995: B, with controls, grew while A, without them, declined. The 1990-1995 change on Island B happened before the controls could matter.",
  },
  {
    id: "pt4-rw2-15",
    skill: "inferences",
    d: "hard",
    s: "In many languages, the word for 'mother' begins with an 'm' sound, and the word for 'father' often begins with a 'p,' 'b,' or 'd' sound. Some linguists once took this as evidence that these languages all descend from a single ancient ancestor. Others note that 'm,' 'p,' 'b,' and 'd' are among the first consonants infants produce, often in babbled syllables like 'ma' and 'pa,' which parents in many cultures take as references to themselves. If the second group is correct, then ______",
    p: STEM.complete,
    c: [
      "the similarity of these words across languages may reflect a shared stage of infant development rather than a shared linguistic ancestor.",
      "all human languages must descend from a single ancient ancestor.",
      "infants learn the words for 'mother' and 'father' later than most other words.",
      "the words for 'mother' and 'father' differ greatly from one language to another.",
    ],
    a: "D",
    e: "If babbling produces these sounds everywhere and parents adopt them, the words could arise independently, so the similarity need not come from common descent.",
  },
  {
    id: "pt4-rw2-16",
    skill: "boundaries",
    d: "hard",
    s: "The chemist Percy Julian, who pioneered methods for making medicines from compounds found in ______ was the first African American chemist elected to the National Academy of Sciences.",
    p: STEM.sec,
    c: ["plants,", "plants", "plants;", "plants--"],
    a: "B",
    e: "The nonessential clause opens with a comma after 'Julian,' so it must close with a comma before the verb 'was.'",
  },
  {
    id: "pt4-rw2-17",
    skill: "boundaries",
    d: "hard",
    s: "The recipe calls for only one unusual ______ a pinch of smoked salt from the coast of Wales.",
    p: STEM.sec,
    c: ["ingredient:", "ingredient;", "ingredient", "ingredient, it is"],
    a: "A",
    e: "A colon after a complete clause can introduce the item it announces. A semicolon would leave a fragment, and 'ingredient, it is' creates a comma splice.",
  },
  {
    id: "pt4-rw2-18",
    skill: "boundaries",
    d: "medium",
    s: "The Hubble Space Telescope was launched in ______ it has since made more than 1.5 million observations.",
    p: STEM.sec,
    c: ["1990, and", "1990 and,", "1990,", "1990"],
    a: "C",
    e: "Two independent clauses can be joined by a comma plus a coordinating conjunction. A comma alone is a splice, and nothing at all is a run-on.",
  },
  {
    id: "pt4-rw2-19",
    skill: "boundaries",
    d: "hard",
    s: "Birds ______ ostriches, emus, and kiwis cannot fly.",
    p: STEM.sec,
    c: ["such as", ", such as", "such as,", ": such as"],
    a: "D",
    e: "'Such as ostriches, emus, and kiwis' is essential: it tells which birds cannot fly. Setting it off with commas would say that birds in general cannot fly, and it would need a closing comma anyway.",
  },
  {
    id: "pt4-rw2-20",
    skill: "subject-verb",
    d: "hard",
    s: "Ada Lovelace is one of the few early computing pioneers whose work ______ still widely studied today.",
    p: STEM.sec,
    c: ["is", "are", "were", "have been"],
    a: "A",
    e: "Within the clause 'whose work ___ still widely studied,' the subject is 'work,' which is singular, so the verb is 'is.'",
  },
  {
    id: "pt4-rw2-21",
    skill: "form-structure-sense",
    d: "hard",
    s: "Had the expedition ______ a week later, it would have been trapped by the winter storms.",
    p: STEM.sec,
    c: ["departed", "departs", "departing", "depart"],
    a: "B",
    e: "'Had the expedition departed' is an inverted form of 'If the expedition had departed,' which needs the past participle.",
  },
  {
    id: "pt4-rw2-22",
    skill: "form-structure-sense",
    d: "hard",
    s: "A self-taught astronomer who ground his own telescope mirrors, ______",
    p: STEM.sec,
    c: [
      "William Herschel discovered the planet Uranus in 1781.",
      "the planet Uranus was discovered by William Herschel in 1781.",
      "William Herschel's discovery of Uranus came in 1781.",
      "Uranus was the planet that William Herschel discovered in 1781.",
    ],
    a: "C",
    e: "The opening phrase describes a person, so the next words must name that person: William Herschel. Otherwise the planet or the discovery is the 'self-taught astronomer.'",
  },
  {
    id: "pt4-rw2-23",
    skill: "transitions",
    d: "medium",
    s: "The team's first weather model predicted rainfall with impressive accuracy in coastal regions. In mountainous areas, ______ its predictions were often wrong by a wide margin.",
    p: STEM.transition,
    c: ["however,", "therefore,", "likewise,", "for example,"],
    a: "D",
    e: "Poor accuracy in the mountains contrasts with strong accuracy on the coast, so 'however' fits.",
  },
  {
    id: "pt4-rw2-24",
    skill: "transitions",
    d: "hard",
    s: "Emperor penguins breed during the Antarctic winter, when temperatures can fall below -40{deg}C. To survive, they huddle in tight groups, taking turns on the colder outer edge. ______ each bird spends only a short time exposed to the full force of the wind.",
    p: STEM.transition,
    c: ["In this way,", "Nevertheless,", "By contrast,", "Previously,"],
    a: "B",
    e: "The last sentence gives the result of the rotation just described, so 'In this way' fits.",
  },
  {
    id: "pt4-rw2-25",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "The axolotl is a salamander native to lakes near Mexico City.",
      "Unlike most salamanders, it keeps juvenile features, such as external gills, throughout its life.",
      "It can regenerate limbs and even parts of its heart and brain, which makes it of great interest to scientists.",
      "Wild axolotl populations have declined sharply because of pollution and urban development.",
    ),
    p: goal("explain both why the axolotl interests scientists and why it is endangered in the wild."),
    c: [
      "The axolotl, whose ability to regenerate limbs and even parts of its heart and brain makes it of great interest to scientists, has declined sharply in the wild because of pollution and urban development.",
      "The axolotl can regenerate limbs and even parts of its heart and brain.",
      "Unlike most salamanders, the axolotl keeps its external gills throughout its life.",
      "Wild axolotl populations near Mexico City have declined sharply.",
    ],
    a: "A",
    e: "The goal has two parts. Only the first choice gives both the reason for scientific interest (regeneration) and the cause of decline (pollution and development).",
  },
  {
    id: "pt4-rw2-26",
    skill: "rhetorical-synthesis",
    d: "hard",
    s: notes(
      "Researchers have long debated when people first reached the Americas.",
      "For decades, the dominant view held that people arrived about 13,000 years ago.",
      "In 2021, researchers reported human footprints at White Sands, New Mexico, dated to about 21,000 to 23,000 years ago.",
      "If the dates are accurate, people were in North America during the peak of the last ice age.",
    ),
    p: goal("explain how the White Sands finding challenges an earlier view."),
    c: [
      "Human footprints at White Sands, New Mexico, dated to about 21,000 to 23,000 years ago, suggest that people reached the Americas thousands of years earlier than the long-dominant estimate of about 13,000 years ago.",
      "In 2021, researchers reported finding human footprints at White Sands, New Mexico.",
      "Researchers have long debated when people first reached the Americas.",
      "For decades, the dominant view held that people arrived in the Americas about 13,000 years ago.",
    ],
    a: "D",
    e: "A challenge requires setting the new date against the old view. Only the first choice does both.",
  },
  {
    id: "pt4-rw2-27",
    skill: "rhetorical-synthesis",
    d: "medium",
    s: notes(
      "Economist Elinor Ostrom studied how communities manage shared resources.",
      "Many economists had argued that shared resources, such as fisheries and pastures, are inevitably overused.",
      "Ostrom documented many communities that had managed shared resources sustainably for centuries.",
      "In 2009, she became the first woman to win the Nobel Prize in Economic Sciences.",
    ),
    p: goal("present Ostrom's research as a challenge to a common assumption."),
    c: [
      "Although many economists argued that shared resources are inevitably overused, Elinor Ostrom documented many communities that had managed them sustainably for centuries.",
      "In 2009, Elinor Ostrom became the first woman to win the Nobel Prize in Economic Sciences.",
      "Elinor Ostrom studied how communities manage shared resources.",
      "Fisheries and pastures are examples of shared resources.",
    ],
    a: "C",
    e: "Only the first choice states the assumption and Ostrom's evidence against it.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 1                                                      */
/* ------------------------------------------------------------------ */

export const PT4_M1 = build([
  {
    id: "pt4-m1-01",
    skill: "linear-eq-1var",
    d: "easy",
    p: "What value of p is the solution to the equation 4(p - 2) = 20?",
    c: ["7", "3", "5.5", "22"],
    a: "D",
    e: "Divide by 4: p - 2 = 5, so p = 7.",
  },
  {
    id: "pt4-m1-02",
    skill: "percentages",
    d: "easy",
    p: "In a survey, 18 of 60 students said they walk to school. What percent of the surveyed students walk to school?",
    c: ["30%", "18%", "42%", "3%"],
    a: "B",
    e: "18/60 = 0.30, which is 30%.",
  },
  {
    id: "pt4-m1-03",
    skill: "exponential",
    d: "easy",
    p: "If 2^{x} = 32, what is the value of x?",
    c: ["5", "4", "16", "6"],
    a: "A",
    e: "32 = 2 {times} 2 {times} 2 {times} 2 {times} 2 = 2^{5}, so x = 5.",
  },
  {
    id: "pt4-m1-04",
    skill: "area-volume",
    d: "easy",
    p: "A cube has edges of length 4 inches. What is the volume of the cube, in cubic inches?",
    c: ["64", "16", "48", "96"],
    a: "C",
    e: "The volume of a cube is its edge length cubed: 4^3 = 64. (96 is the surface area.)",
  },
  {
    id: "pt4-m1-05",
    skill: "linear-eq-2var",
    d: "easy",
    p: "The point (a, 12) lies on the line y = 5x - 8 in the xy-plane. What is the value of a?",
    a: "4",
    e: "Substitute y = 12: 12 = 5a - 8, so 5a = 20 and a = 4.",
  },
  {
    id: "pt4-m1-06",
    skill: "data-distributions",
    d: "easy",
    fig: {
      kind: "bar",
      title: "Books Sold at a School Book Fair",
      yLabel: "Books sold",
      categories: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      series: [{ name: "Books", values: [14, 9, 17, 11, 20] }],
      y: [0, 25, 5],
    },
    p: "The bar graph shows the number of books sold at a school book fair on each of five days. What is the range of the number of books sold per day?",
    c: ["11", "20", "14.2", "9"],
    a: "D",
    e: "The range is the greatest value minus the least: 20 - 9 = 11. (14.2 is the mean.)",
  },
  {
    id: "pt4-m1-07",
    skill: "systems-linear",
    d: "medium",
    fig: {
      kind: "plot",
      axesAtOrigin: true,
      x: [-3, 6, 1],
      y: [-2, 8, 1],
      series: [{ type: "fn", f: (x) => x + 1 }, { type: "fn", f: (x) => -2 * x + 7, dashed: true }],
      alt: "Two lines: one rising with slope 1 through (0, 1), one falling with slope negative 2 through (0, 7). They cross at (2, 3).",
    },
    p: "The graphs of two linear equations are shown in the xy-plane. What is the solution (x, y) to the system formed by the two equations?",
    c: ["(2, 3)", "(3, 2)", "(0, 1)", "(0, 7)"],
    a: "A",
    e: "The solution is the point where the lines cross, (2, 3). It satisfies both y = x + 1 and y = -2x + 7.",
  },
  {
    id: "pt4-m1-08",
    skill: "equivalent-expressions",
    d: "medium",
    p: "Which expression is equivalent to 9x^2 - 25?",
    c: ["(3x - 5)(3x + 5)", "(3x - 5)^2", "(9x - 5)(x + 5)", "(3x + 5)^2"],
    a: "C",
    e: "9x^2 - 25 is a difference of squares, (3x)^2 - 5^2, which factors as (3x - 5)(3x + 5).",
  },
  {
    id: "pt4-m1-09",
    skill: "ratios-rates",
    d: "medium",
    p: "Maria typed 1,800 words in 40 minutes. At this rate, how many words would she type in 1.5 hours?",
    c: ["4,050", "2,700", "3,600", "67.5"],
    a: "B",
    e: "Her rate is 1,800/40 = 45 words per minute. 1.5 hours is 90 minutes, so she types 45 {times} 90 = 4,050 words.",
  },
  {
    id: "pt4-m1-10",
    skill: "systems-linear",
    d: "medium",
    s: "3a + 2b = 22\na + 2b = 10",
    p: "What is the value of a in the solution (a, b) to the given system of equations?",
    a: "6",
    e: "Subtract the second equation from the first: 2a = 12, so a = 6.",
  },
  {
    id: "pt4-m1-11",
    skill: "lines-angles-triangles",
    d: "medium",
    p: "The measures of the three angles of a triangle are 3x{deg}, (2x + 10){deg}, and 50{deg}. What is the value of x?",
    c: ["24", "26", "30", "70"],
    a: "D",
    e: "3x + 2x + 10 + 50 = 180, so 5x = 120 and x = 24.",
  },
  {
    id: "pt4-m1-12",
    skill: "exponential",
    d: "medium",
    p: "The mass, in grams, of a radioactive substance t days after it is measured is given by M(t) = 250(0.5)^{t/8}. How many days does it take for the mass to be halved?",
    c: ["8", "0.5", "250", "125"],
    a: "A",
    e: "The factor 0.5 is applied once each time t/8 increases by 1, that is, every 8 days. So the mass halves every 8 days.",
  },
  {
    id: "pt4-m1-13",
    skill: "probability",
    d: "medium",
    fig: {
      kind: "table",
      head: ["Blood type", "O", "A", "B", "AB"],
      rows: [["Number of donors", "88", "70", "30", "12"]],
      rowHeaders: true,
    },
    p: "The table shows the blood types of 200 donors at a blood drive. If one donor is selected at random, what is the probability that the donor has type A or type B blood?",
    c: ["1/2", "7/20", "3/20", "1/4"],
    a: "B",
    e: "70 + 30 = 100 of the 200 donors have type A or B, so the probability is 100/200 = 1/2.",
  },
  {
    id: "pt4-m1-14",
    skill: "linear-functions",
    d: "medium",
    p: "A phone plan costs $40 per month, which includes 500 text messages, plus $0.10 for each additional text message. Which function gives the monthly cost C, in dollars, for a customer who sends t text messages, where t > 500?",
    c: ["C(t) = 40 + 0.10(t - 500)", "C(t) = 40 + 0.10t", "C(t) = 40(t - 500) + 0.10", "C(t) = 0.10(t + 500) + 40"],
    a: "C",
    e: "Only messages beyond the first 500 cost extra, and there are t - 500 of them at $0.10 each, on top of the $40 base.",
  },
  {
    id: "pt4-m1-15",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The function f is defined by f(x) = x^2 - 5x + 2. What is the value of f(-3)?",
    a: "26",
    e: "f(-3) = (-3)^2 - 5(-3) + 2 = 9 + 15 + 2 = 26.",
  },
  {
    id: "pt4-m1-16",
    skill: "circles",
    d: "medium",
    p: "An arc of a circle with radius 10 has a length of 5{pi}. What is the measure, in degrees, of the arc's central angle?",
    c: ["90", "45", "180", "30"],
    a: "C",
    e: "The circumference is 20{pi}, and 5{pi} is 1/4 of it. One quarter of 360 degrees is 90 degrees.",
  },
  {
    id: "pt4-m1-17",
    skill: "data-distributions",
    d: "medium",
    p: "The mean of a student's first five test scores is 84. What score must the student earn on the sixth test so that the mean of all six scores is 86?",
    c: ["96", "88", "86", "92"],
    a: "A",
    e: "Six scores averaging 86 total 516, and the first five total 5 {times} 84 = 420. The sixth score must be 516 - 420 = 96.",
  },
  {
    id: "pt4-m1-18",
    skill: "systems-linear",
    d: "hard",
    p: "A chemist mixes a 20% acid solution with a 50% acid solution to make 30 liters of a 30% acid solution. How many liters of the 20% solution does the chemist use?",
    c: ["20", "10", "15", "18"],
    a: "D",
    e: "Let x liters be 20% and 30 - x be 50%. Acid: 0.20x + 0.50(30 - x) = 0.30(30) = 9. So 15 - 0.30x = 9, giving x = 20.",
  },
  {
    id: "pt4-m1-19",
    skill: "quadratics",
    d: "hard",
    p: "What is the sum of all the solutions to the equation (x - 4)(x^2 - 9) = 0?",
    a: "4",
    e: "The solutions are x = 4 and the solutions of x^2 = 9, which are 3 and -3. Their sum is 4 + 3 - 3 = 4.",
  },
  {
    id: "pt4-m1-20",
    skill: "right-triangles-trig",
    d: "medium",
    p: "In the xy-plane, point A has coordinates (-3, 2) and point B has coordinates (5, 8). What is the distance between points A and B?",
    a: "10",
    e: "The horizontal change is 8 and the vertical change is 6, so the distance is {sqrt}(8^2 + 6^2) = {sqrt}100 = 10.",
  },
  {
    id: "pt4-m1-21",
    skill: "nonlinear-functions",
    d: "hard",
    p: "The graph of the function f(x) = a(x - 2)^2 + 5, where a is a constant, passes through the point (4, -3). What is the value of a?",
    c: ["-2", "2", "-4", "1/2"],
    a: "B",
    e: "Substitute (4, -3): -3 = a(2)^2 + 5, so 4a = -8 and a = -2.",
  },
  {
    id: "pt4-m1-22",
    skill: "linear-functions",
    d: "hard",
    p: "In the xy-plane, line {l} has a slope of 3/4 and passes through the point (8, 1). If the point (k, 7) also lies on line {l}, what is the value of k?",
    c: ["16", "12.5", "10", "24"],
    a: "C",
    e: "The rise from y = 1 to y = 7 is 6. With slope 3/4, the run is 6 {times} 4/3 = 8, so k = 8 + 8 = 16.",
  },
]);

/* ------------------------------------------------------------------ */
/* Math, Module 2 (harder)                                             */
/* ------------------------------------------------------------------ */

export const PT4_M2 = build([
  {
    id: "pt4-m2-01",
    skill: "linear-eq-1var",
    d: "medium",
    p: "If (x + 5)/3 = (x - 1)/2, what is the value of x?",
    c: ["13", "7", "-13", "3"],
    a: "B",
    e: "Cross-multiply: 2(x + 5) = 3(x - 1), so 2x + 10 = 3x - 3 and x = 13.",
  },
  {
    id: "pt4-m2-02",
    skill: "percentages",
    d: "medium",
    p: "After a 15% discount, the price of a laptop is $850. What was the price of the laptop before the discount?",
    c: ["$1,000", "$977.50", "$722.50", "$865"],
    a: "A",
    e: "The sale price is 85% of the original: 0.85p = 850, so p = 1,000. Adding 15% to $850 gives $977.50, which is the common mistake.",
  },
  {
    id: "pt4-m2-03",
    skill: "equivalent-expressions",
    d: "medium",
    p: "Which expression is equivalent to {sqrt}(50x^{6}), where x > 0?",
    c: ["5x^3{sqrt}2", "25x^3{sqrt}2", "5x^{4}{sqrt}2", "2x^3{sqrt}5"],
    a: "D",
    e: "{sqrt}50 = {sqrt}(25 {times} 2) = 5{sqrt}2, and {sqrt}(x^{6}) = x^3 for x > 0. Together: 5x^3{sqrt}2.",
  },
  {
    id: "pt4-m2-04",
    skill: "linear-eq-2var",
    d: "medium",
    p: "The graph of 3x + 4y = 24 in the xy-plane crosses the x-axis at (a, 0) and the y-axis at (0, b). What is the value of a + b?",
    a: "14",
    e: "At y = 0, 3x = 24 so a = 8. At x = 0, 4y = 24 so b = 6. Then a + b = 14.",
  },
  {
    id: "pt4-m2-05",
    skill: "inference",
    d: "hard",
    p: "A researcher surveyed students at several high schools and found that students who reported eating breakfast every day had higher average test scores than students who did not. The students were not randomly assigned to eat or skip breakfast. Which conclusion is best supported by the study?",
    c: [
      "Eating breakfast daily is associated with higher test scores among the students surveyed, but the study cannot show that eating breakfast causes higher scores.",
      "Eating breakfast every day causes students to earn higher test scores.",
      "Skipping breakfast causes students to earn lower test scores at every high school.",
      "There is no relationship between eating breakfast and test scores.",
    ],
    a: "C",
    e: "Without random assignment, other differences between the groups could explain the scores, so the study shows an association only. It found a relationship, so the last choice is wrong.",
  },
  {
    id: "pt4-m2-06",
    skill: "exponential",
    d: "hard",
    p: "Which of the following is equivalent to (1/16)^{-x/4}?",
    c: ["2^{x}", "4^{x}", "2^{-x}", "(1/2)^{x}"],
    a: "A",
    e: "(1/16)^{-x/4} = 16^{x/4} = (2^{4})^{x/4} = 2^{x}.",
  },
  {
    id: "pt4-m2-07",
    skill: "right-triangles-trig",
    d: "hard",
    p: "Triangles ABC and DEF are similar right triangles, with right angles at C and F, and angle A corresponds to angle D. If tan A = 7/24 and DF = 72, what is the length of EF?",
    a: "21",
    e: "Similar triangles have equal corresponding angles, so tan D = tan A = 7/24. In triangle DEF, tan D = EF/DF, so EF = 72 {times} 7/24 = 21.",
  },
  {
    id: "pt4-m2-08",
    skill: "linear-eq-1var",
    d: "hard",
    p: "In the equation 5(x - b) = 3x - 2(4 - x), b is a constant. For what value of b does the equation have infinitely many solutions?",
    c: ["8/5", "8", "5/8", "-8/5"],
    a: "A",
    e: "The right side simplifies to 3x - 8 + 2x = 5x - 8, and the left side is 5x - 5b. They are identical when 5b = 8, so b = 8/5.",
  },
  {
    id: "pt4-m2-09",
    skill: "percentages",
    d: "hard",
    p: "In a city, 55% of residents are adults. Of the adults, 40% commute by bus, and of the residents who are not adults, 25% commute by bus. What percent of all the city's residents commute by bus?",
    c: ["33.25%", "32.5%", "65%", "22%"],
    a: "B",
    e: "Adults who ride: 0.55 {times} 0.40 = 0.22. Others who ride: 0.45 {times} 0.25 = 0.1125. Together, 0.3325, or 33.25%. Averaging 40% and 25% gives 32.5%, which ignores the group sizes.",
  },
  {
    id: "pt4-m2-10",
    skill: "quadratics",
    d: "hard",
    p: "What is the product of the solutions to the equation 3x^2 + 7x - 20 = 0?",
    a: "-20/3",
    alt: ["-6.666", "-6.667"],
    e: "Factor: (3x - 5)(x + 4) = 0, so the solutions are 5/3 and -4, whose product is -20/3. (For ax^2 + bx + c = 0 the product is always c/a.)",
  },
  {
    id: "pt4-m2-11",
    skill: "circles",
    d: "hard",
    p: "A circle in the xy-plane has its center at (4, -3) and is tangent to the x-axis. Which equation represents the circle?",
    c: [
      "(x - 4)^2 + (y + 3)^2 = 9",
      "(x + 4)^2 + (y - 3)^2 = 9",
      "(x - 4)^2 + (y + 3)^2 = 16",
      "(x - 4)^2 + (y + 3)^2 = 3",
    ],
    a: "D",
    e: "Tangent to the x-axis means the radius equals the center's distance from it, |-3| = 3. So r^2 = 9, and the equation is (x - 4)^2 + (y + 3)^2 = 9.",
  },
  {
    id: "pt4-m2-12",
    skill: "linear-eq-1var",
    d: "hard",
    p: "A car leaves a station traveling at 60 kilometers per hour. One hour later, a train leaves the same station traveling the same route at 80 kilometers per hour. How many hours after the train leaves will it catch up to the car?",
    c: ["3", "4", "1", "2"],
    a: "C",
    e: "After t hours the train has gone 80t and the car 60(t + 1). Setting them equal: 80t = 60t + 60, so t = 3.",
  },
  {
    id: "pt4-m2-13",
    skill: "nonlinear-functions",
    d: "hard",
    p: "The graph of the quadratic function f in the xy-plane has its vertex at (-1, -8), and one of its x-intercepts is (1, 0). What is the other x-intercept?",
    c: ["(-3, 0)", "(-1, 0)", "(3, 0)", "(-2, 0)"],
    a: "A",
    e: "A parabola is symmetric about the vertical line through its vertex, x = -1. The point (1, 0) is 2 units to the right, so the other intercept is 2 units to the left, at (-3, 0).",
  },
  {
    id: "pt4-m2-14",
    skill: "inference",
    d: "hard",
    p: "A line of best fit for a data set is y = 2x + 3. One of the data points is (5, 16). What is the actual y-value of this point minus the y-value predicted by the line of best fit?",
    c: ["3", "-3", "13", "16"],
    a: "D",
    e: "At x = 5 the line predicts 2(5) + 3 = 13. The actual value is 16, so actual minus predicted is 16 - 13 = 3.",
  },
  {
    id: "pt4-m2-15",
    skill: "nonlinear-functions",
    d: "medium",
    p: "The functions f and g are defined by f(x) = 3x - 2 and g(x) = x^2 + 1. What is the value of f(g(2))?",
    a: "13",
    e: "First g(2) = 4 + 1 = 5. Then f(5) = 15 - 2 = 13.",
  },
  {
    id: "pt4-m2-16",
    skill: "area-volume",
    d: "hard",
    fig: {
      kind: "diagram",
      w: 270,
      h: 130,
      items: [
        { t: "poly", pts: [[200, 10], [20, 10], [20, 130], [200, 130]], closed: false },
        { t: "line", a: [200, 10], b: [200, 130], dashed: true },
        { t: "arc", c: [200, 70], r: 60, from: -90, to: 90 },
        { t: "text", at: [110, 0], s: "12" },
        { t: "text", at: [8, 70], s: "8" },
      ],
      alt: "A 12 by 8 rectangle with a semicircle attached along its right side of length 8.",
    },
    p: "The figure shows a rectangle with length 12 and width 8, with a semicircle attached along one of its sides of length 8. What is the total area of the figure?",
    c: ["96 + 8{pi}", "96 + 16{pi}", "96 + 4{pi}", "104{pi}"],
    a: "B",
    e: "The rectangle's area is 12 {times} 8 = 96. The semicircle has diameter 8, so radius 4, and area (1/2){pi}(4)^2 = 8{pi}. The total is 96 + 8{pi}.",
  },
  {
    id: "pt4-m2-17",
    skill: "linear-functions",
    d: "hard",
    p: "In the xy-plane, a line through the origin passes through the points (3, -6) and (a, 10). What is the value of a?",
    c: ["-5", "5", "-20", "-3"],
    a: "C",
    e: "A line through the origin has the form y = kx. From (3, -6), k = -2. Then 10 = -2a, so a = -5.",
  },
  {
    id: "pt4-m2-18",
    skill: "exponential",
    d: "hard",
    p: "A population of 6,400 animals decreases by 25% every 3 years. At this rate, what will the population be 9 years from now?",
    c: ["2,700", "1,600", "4,800", "3,600"],
    a: "A",
    e: "Nine years is three 3-year periods, and each keeps 75%: 6,400 {times} 0.75^3 = 6,400 {times} 0.421875 = 2,700. Subtracting 25% of 6,400 three times gives 1,600, which is wrong.",
  },
  {
    id: "pt4-m2-19",
    skill: "right-triangles-trig",
    d: "hard",
    p: "Two sides of a right triangle have lengths 6 and 10. Which of the following gives all possible lengths of the third side?",
    c: ["8 or 2{sqrt}34", "8 only", "2{sqrt}34 only", "4 only"],
    a: "D",
    e: "If 10 is the hypotenuse, the third side is {sqrt}(100 - 36) = 8. If 6 and 10 are both legs, the hypotenuse is {sqrt}(36 + 100) = {sqrt}136 = 2{sqrt}34. Both are possible.",
  },
  {
    id: "pt4-m2-20",
    skill: "quadratics",
    d: "medium",
    p: "How many real solutions does the equation 2x^2 - 3x + 7 = 0 have?",
    c: ["Zero", "One", "Two", "Infinitely many"],
    a: "A",
    e: "The discriminant is (-3)^2 - 4(2)(7) = 9 - 56 = -47, which is negative, so there are no real solutions.",
  },
  {
    id: "pt4-m2-21",
    skill: "linear-inequalities",
    d: "hard",
    s: "y <= -x + 10\ny >= 2x - 5\nx >= 0",
    p: "The point (x, y) satisfies the given system of inequalities. What is the greatest possible value of x?",
    a: "5",
    e: "Both conditions on y can hold only if 2x - 5 <= -x + 10, so 3x <= 15 and x <= 5. At x = 5, y = 5 satisfies all three inequalities.",
  },
  {
    id: "pt4-m2-22",
    skill: "exponential",
    d: "hard",
    p: "The function f is defined by f(x) = 2^{x} + k, where k is a constant. The graph of y = f(x) passes through the point (3, 5). What is the value of f(5)?",
    a: "29",
    e: "f(3) = 8 + k = 5, so k = -3. Then f(5) = 32 - 3 = 29.",
  },
]);
