import { useEffect, useState } from "react";
import { Download, ImageOff } from "lucide-react";
import { ImageGeneration } from "@/components/ui/ai-chat-image-generation-1";
import { type AdvisorArtifact, getArtifactSignedUrl } from "@/hooks/useAdvisorArtifacts";

/**
 * A generated image, shown in the conversation.
 *
 * WHY THIS EXISTS RATHER THAN `ArtifactInlineCard`
 *
 * Images no longer appear in the Artifacts panel — see the note in
 * `useAdvisorArtifacts`. The card was a button whose whole purpose was to open
 * that panel focused on the item, so once images stopped being listed there,
 * pressing it would have opened a panel that does not contain the thing you
 * pressed. A picture is also not a document: the useful thing is to see it, not
 * to file it.
 *
 * So the image is rendered at a readable size, with a download for keeping it,
 * and the reveal wipe runs once while the signed URL is being fetched and the
 * bytes are arriving.
 */
export function InlineGeneratedImage({ artifact }: { artifact: AdvisorArtifact }) {
  const [url, setUrl] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    if (!artifact.file_path) {
      setFailed(true);
      return;
    }
    getArtifactSignedUrl(artifact)
      .then((u) => {
        if (cancelled) return;
        if (u) setUrl(u);
        else setFailed(true);
      })
      .catch(() => !cancelled && setFailed(true));
    return () => {
      cancelled = true;
    };
  }, [artifact]);

  if (failed) {
    return (
      <div className="mt-2 flex max-w-sm items-center gap-2 rounded-xl border border-border bg-card/80 px-3 py-2.5 text-xs text-muted-foreground">
        <ImageOff className="h-4 w-4 shrink-0" aria-hidden="true" />
        That image could not be loaded.
      </div>
    );
  }

  return (
    <figure className="mt-2 w-full max-w-sm">
      {/* `done` is the real event — the bytes having decoded — not a timer, so
          the wipe never finishes before the picture does. */}
      <ImageGeneration
        done={loaded}
        labels={{
          starting: "Setting up.",
          generating: "Creating your image. This takes a moment.",
          completed: artifact.title || "Image ready.",
        }}
      >
        {url ? (
          <img
            src={url}
            alt={artifact.title || "Image generated by the Pathforge advisor"}
            className="block w-full"
            loading="lazy"
            decoding="async"
            onLoad={() => setLoaded(true)}
            onError={() => setFailed(true)}
          />
        ) : (
          // Same box while the signed URL is in flight, so nothing jumps when
          // the picture replaces it.
          <div className="aspect-[4/3] w-full bg-gradient-to-br from-muted via-secondary/60 to-muted" />
        )}
      </ImageGeneration>

      {url && loaded && (
        <figcaption className="mt-1.5 flex items-center justify-between gap-2">
          <span className="truncate text-xs text-muted-foreground">{artifact.title}</span>
          <a
            href={url}
            download={`${(artifact.title || "image").replace(/[^a-z0-9-_ ]/gi, "").trim() || "image"}.png`}
            className="inline-flex shrink-0 items-center gap-1 text-xs text-accent hover:underline"
          >
            <Download className="h-3 w-3" aria-hidden="true" />
            Save
          </a>
        </figcaption>
      )}
    </figure>
  );
}
