import { useCallback, useEffect, useState } from "react";
import { Navigate, useSearchParams } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { Seo } from "@/components/Seo";

const DOWNLOAD_URL =
  "https://github.com/akkki8844/pathforge-app/releases/latest/download/Pathforge-Setup.exe";

/**
 * The browser half of desktop sign-in.
 *
 * The desktop app can't run OAuth in its own window — providers block embedded
 * webviews, and it would throw away the Google session the user already has
 * here. So it opens this page in the real browser, the normal `/auth` flow
 * runs, and this page hands the resulting session back over `pathforge://auth`.
 *
 * `state` is generated by the app for one Continue click and echoed back
 * untouched. The app refuses any deep link that doesn't carry the value it is
 * currently waiting on, which is what stops another process on the machine
 * from firing a pathforge:// link of its own.
 */
export default function AppLogin() {
  const { user, session, profile, loading, signOut } = useAuth();
  const [params] = useSearchParams();
  const state = params.get("state");
  const [handedOff, setHandedOff] = useState(false);

  const openApp = useCallback(() => {
    if (!session?.access_token || !session?.refresh_token) return;
    const url = new URL("pathforge://auth");
    url.searchParams.set("access_token", session.access_token);
    url.searchParams.set("refresh_token", session.refresh_token);
    if (state) url.searchParams.set("state", state);
    // Assigning rather than opening a window: a custom-scheme navigation in
    // the current tab is what triggers the OS handler without a popup blocker
    // getting a vote, and the page itself stays put.
    window.location.href = url.toString();
    setHandedOff(true);
  }, [session, state]);

  useEffect(() => {
    if (loading || !session) return;
    openApp();
  }, [loading, session, openApp]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <Loader2 className="h-6 w-6 animate-spin text-primary" />
      </div>
    );
  }

  // Not signed in yet: run the normal auth flow, then come back here with the
  // same `state` so the app still recognises the hand-off it asked for.
  if (!user || !session) {
    const back = `/app-login${state ? `?state=${encodeURIComponent(state)}` : ""}`;
    return <Navigate to={`/auth?redirect=${encodeURIComponent(back)}`} replace />;
  }

  const name = profile?.full_name || user.email?.split("@")[0] || "there";
  const initial = name.trim().charAt(0).toUpperCase();

  return (
    <div className="relative flex min-h-screen flex-col items-center justify-center bg-background px-6 font-display">
      <Seo
        title="Opening Pathforge"
        description="Handing your Pathforge session to the desktop app."
        path="/app-login"
        noindex
      />

      {/* Who this is about to sign in as. If the browser is logged into a
          different account than the one the user meant, this is the only place
          they can find that out before the app opens. */}
      <div className="absolute right-8 top-7 flex flex-col items-end gap-1.5">
        <div className="flex items-center gap-3.5">
          <div className="text-right leading-tight">
            <p className="text-[1.05rem] font-bold tracking-[-0.01em] text-foreground">{name}</p>
            <p className="text-[1.05rem] font-normal text-muted-foreground">{user.email}</p>
          </div>
          <div
            className="flex h-[3.4rem] w-[3.4rem] shrink-0 items-center justify-center rounded-full bg-primary text-[1.5rem] font-semibold text-primary-foreground"
            aria-hidden="true"
          >
            {initial}
          </div>
        </div>
        <button
          type="button"
          onClick={() => void signOut()}
          className="text-[1.05rem] font-normal text-muted-foreground underline underline-offset-[5px] transition-colors hover:text-foreground"
        >
          Sign Out
        </button>
      </div>

      <h1 className="text-center text-[3.25rem] font-bold leading-[1.05] tracking-[-0.035em] text-foreground">
        Opening Pathforge
      </h1>
      <p className="mt-6 text-center text-[1.2rem] font-normal text-muted-foreground">
        {handedOff ? "If the app has not opened, " : "Handing off to the app, "}
        <button
          type="button"
          onClick={openApp}
          className="font-medium text-foreground underline underline-offset-[5px]"
        >
          click here
        </button>
        .
      </p>

      <div className="absolute bottom-[12vh] flex flex-col items-center gap-5">
        <p className="text-[1.05rem] font-normal text-muted-foreground">
          Don't have Pathforge yet?
        </p>
        <a
          href={DOWNLOAD_URL}
          className="inline-flex h-[3.1rem] items-center rounded-[0.65rem] bg-muted px-6 text-[1.05rem] font-semibold tracking-[-0.01em] text-foreground transition-colors hover:bg-muted/70"
        >
          Download Pathforge
        </a>
      </div>
    </div>
  );
}
