// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my Pathforge profile",
  description: "Fetch the signed-in user's Pathforge profile: name/username/email plus onboarding data (grade, school, country, curriculum, GPA, intended major, target universities, application year).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pe }, { data: onboarding, error: oe }] = await Promise.all([
      client.from("profiles").select("username,full_name,email").eq("user_id", userId).maybeSingle(),
      client.from("onboarding_data").select(
        "grade,high_school_name,country,curriculum,gpa,gpa_range,standardized_test_type,standardized_test_score,intended_major,target_universities,application_year,extracurricular_level,areas_of_interest,career_direction,onboarding_completed"
      ).eq("user_id", userId).maybeSingle()
    ]);
    if (pe || oe) {
      return {
        content: [{ type: "text", text: (pe ?? oe).message }],
        isError: true
      };
    }
    const payload = { profile: profile ?? null, onboarding: onboarding ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-journey-score.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_journey_score_default = defineTool2({
  name: "get_journey_score",
  title: "Get my journey score",
  description: "Fetch the signed-in user's overall Pathforge journey score (0-100) and per-category progress toward their college application goals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("journey_scores").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { score: null }, null, 2) }],
      structuredContent: data ?? { score: null }
    };
  }
});

// src/lib/mcp/tools/get-subscription.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_subscription_default = defineTool3({
  name: "get_subscription",
  title: "Get my Pathforge plan",
  description: "Fetch the signed-in user's current Pathforge subscription plan (Free / Pro / Enterprise) and credit balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("subscriptions").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { plan: "free" }, null, 2) }],
      structuredContent: data ?? { plan: "free" }
    };
  }
});

// src/lib/mcp/tools/list-recommendations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recommendations_default = defineTool4({
  name: "list_readiness_reports",
  title: "List my readiness reports",
  description: "List the signed-in user's saved college readiness analyses (most recent first) with their scores and summary insights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("readiness_analyses").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { items: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aupymiiwhfnaoduvxyzt";
var mcp_default = defineMcp({
  name: "pathforge-mcp",
  title: "Pathforge",
  version: "0.1.0",
  instructions: "Pathforge MCP exposes read-only access to the signed-in student's college-prep data: profile & onboarding info, journey score, subscription plan, and saved readiness reports. Use these tools to personalize advice about their college applications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_journey_score_default, get_subscription_default, list_recommendations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
